# THIS IS AN INCOMPLETE PYPROJECT.TOML USED BY THE BUILD WHEEL SCRIPT TO CREATE A COMPLETE PYPROJECT.TOML.
version = "1.0.45"
description = "Application indicator which displays the current Star Trek™ stardate."
classifiers = [
  "Topic :: Games/Entertainment"
]

