#!/usr/bin/env python3
# -*- coding: utf-8 -*-


# The program below (excluding the data) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import time


def isExpired(): return getExpiry() < time.strftime( "%Y-%m-%d" )


# Obtain the non-UK port expiry date in YYYY-MM-DD.
def getExpiry(): return _UKHO_NON_UK_PORT_EXPIRY


def isValidPortID( portID ):
    isValid = False
    for port in _ports:
        if portID == port[ _INDEX_PORT_ID ]:
            isValid = True
            break

    return isValid


def getCountry( portID ): 
    country = None
    for port in _ports:
        if portID == port[ _INDEX_PORT_ID ]:
            country = port[ _INDEX_PORT_COUNTRY ]
            break

    return country


def getPortName( portID ): 
    portName = None
    for port in _ports:
        if portID == port[ _INDEX_PORT_ID ]:
            portName = port[ _INDEX_PORT_NAME ]
            break

    return portName


# Returns the port ID for the first matching country.
def getPortIDForCountry( country ):
    portID = None
    for port in _ports:
        if country == port[ _INDEX_PORT_COUNTRY ]:
            portID = port[ _INDEX_PORT_ID ]
            break

    return portID


def getPortIDForCountryAndPortName( country, portName ):
    portID = None
    for port in _ports:
        if country == port[ _INDEX_PORT_COUNTRY ] and portName == port[ _INDEX_PORT_NAME ]:
            portID = port[ _INDEX_PORT_ID ]
            break

    return portID


def getPortNamesForCountry( country ):
    portNames = [ ]
    for port in _ports:
        if port[ _INDEX_PORT_COUNTRY ] == country and port[ _INDEX_PORT_NAME ] not in portNames:
            portNames.append( port[ _INDEX_PORT_NAME ] )

    return portNames


def getCountries():
    countries = [ ]
    for port in _ports:
        if port[ _INDEX_PORT_COUNTRY ] not in countries:
            countries.append( port[ _INDEX_PORT_COUNTRY ] )

    return countries


def getFirstPortID(): return _ports[ 0 ][ _INDEX_PORT_ID ]


# Indices for each port's data.
_INDEX_PORT_ID = 0
_INDEX_PORT_NAME = 1
_INDEX_PORT_COUNTRY = 2


# © Crown Copyright and/or database rights.
# No part of this material may sold, distributed nor copies made.
# Reproduced by permission of the Controller of Her Majesty's Stationery Office and the UK Hydrographic Office.
# www.ukho.gov.uk
#
# Port ID. port name, country.
_UKHO_NonUKPorts = [
    [ "5145A", "Kuala Belait", "Brunei" ],
    [ "4680", "Kuala Bernam", "Peninsular Malaysia West Coast" ],
    [ "5150", "Kuala Bintulu", "Sarawak" ],
    [ "4899", "Kuala Dungun", "Peninsular Malaysia East Coast" ],
    [ "5154", "Kuala Igan", "Sarawak" ],
    [ "4760", "Kuala Lajau", "Sumatera North East Coast" ],
    [ "5139A", "Kuala Lawas", "Sarawak" ],
    [ "5141", "Kuala Limbang", "Sarawak" ],
    [ "5174A", "Kuala Lundu", "Sarawak" ],
    [ "5155", "Kuala Matu", "Sarawak" ],
    [ "5153", "Kuala Mukah", "Sarawak" ],
    [ "5148", "Kuala Niah", "Sarawak" ],
    [ "4758", "Kuala Niur", "Sumatera North East Coast" ],
    [ "5153B", "Kuala Oya", "Sarawak" ],
    [ "4895", "Kuala Pahang", "Peninsular Malaysia East Coast" ],
    [ "5156", "Kuala Paloh", "Sarawak" ],
    [ "5133", "Kuala Papar", "Sabah" ],
    [ "4658", "Kuala Perlis", "Peninsular Malaysia West Coast" ],
    [ "5157", "Kuala Rajang", "Sarawak" ],
    [ "4892", "Kuala Rompin", "Peninsular Malaysia East Coast" ],
    [ "5167", "Kuala Sadong", "Sarawak" ],
    [ "4683", "Kuala Selangor", "Peninsular Malaysia West Coast" ],
    [ "4779", "Kuala Siak", "Sumatera North East Coast" ],
    [ "5149", "Kuala Similajau", "Sarawak" ],
    [ "5151", "Kuala Tatau", "Sarawak" ],
    [ "4902", "Kuala Terengganu", "Peninsular Malaysia East Coast" ],
    [ "5208", "Kualapembuang", "Kalimantan" ],
    [ "5205", "Kualasapu", "Kalimantan" ],
    [ "4896", "Kuantan", "Peninsular Malaysia East Coast" ],
    [ "5125", "Kudat", "Sabah" ],
    [ "4707A", "Kukup", "Peninsular Malaysia West Coast" ],
    [ "5105", "Kunak", "Sabah" ],
    [ "3550", "Kuntaur", "The Gambia" ],
    [ "5414", "Kupang", "Timor" ],
    [ "8105", "Kushiro", "Japan Hokkaido East Coast" ],
    [ "4514", "Kutubdia Island", "Bangladesh" ],
    [ "5696", "Kwai Harbour", "Solomon Islands" ],
    [ "5262", "Kwandang Bay", "Sulawesi North Coast" ],
    [ "4552", "Kyaikkami (Amherst)", "Burma" ],
    [ "4525", "Kyaukpyu", "Burma" ],
    [ "1984", "Kyrenia", "Cyprus" ],
    [ "4587", "Kyunn Tann Shey (Bulet-Aw)", "Burma" ],
    [ "2133", "La Argentina", "Argentina" ],
    [ "1764", "La Carraca", "Spain" ],
    [ "1717", "La Coruna", "Spain" ],
    [ "3965A", "La Digue", "Seychelles" ],
    [ "1726", "La Guardia", "Spain" ],
    [ "9539", "La Libertad", "Ecuador" ],
    [ "1800", "La Maddalena", "Sardinia" ],
    [ "1835", "La Skhirra", "Tunisia" ],
    [ "4060", "Laasqoray", "Somalia" ],
    [ "5137", "Labuan (Victoria Harbour)", "Sabah" ],
    [ "4842", "Labuan Bangkai", "Sumatera South West Coast" ],
    [ "4790", "Labuan Bilik", "Sumatera North East Coast" ],
    [ "5446", "Labuha", "The Molucca Islands" ],
    [ "5346", "Labuhan", "Jawa North Coast" ],
    [ "5117", "Labuk Bay", "Sabah" ],
    [ "5979", "Lady Elliot Island", "Australia East Coast" ],
    [ "4302", "Laft", "Iran" ],
    [ "1749", "Lagos", "Portugal" ],
    [ "3635", "Lagos Bar", "Nigeria" ],
    [ "6263", "Lagrange Bay", "Australia North Coast" ],
    [ "2183", "Laguna", "Brazil" ],
    [ "5107", "Lahad Datu", "Sabah" ],
    [ "5445", "Laiwui", "The Molucca Islands" ],
    [ "3460", "Lajes (Flores)", "Azores" ],
    [ "5409", "Lamakera", "Flores" ],
    [ "3777", "Lamberts Bay", "South Africa" ],
    [ "5667A", "Lambi Bay", "Solomon Islands" ],
    [ "5039", "Laoang", "Philippine Islands" ],
    [ "3505", "Larache", "Morocco" ],
    [ "4968", "Larena", "Philippine Islands" ],
    [ "6248", "Large Islet", "Australia North Coast" ],
    [ "2335", "Las Cuevas Bay", "Trinidad" ],
    [ "4000", "Latham Island", "Tanzania" ],
    [ "839", "Latravik", "Iceland" ],
    [ "1478", "Lauwersoog", "Netherlands" ],
    [ "4285", "Lavar-E Saheli", "Iran" ],
    [ "4260A", "Lawhah Oilfield", "Saudi Arabia" ],
    [ "5158A", "Leba An", "Sarawak" ],
    [ "5032", "Legaspi", "Philippine Islands" ],
    [ "786A", "Leirvik", "Faeroe Islands" ],
    [ "2052", "Leith Harbour", "Antarctica" ],
    [ "6711A", "Leleuvia Island", "Fiji Islands" ],
    [ "2034", "Lemaire Island (Caleta Gloria)", "Antarctica" ],
    [ "5655", "Lever Harbour", "Solomon Islands" ],
    [ "6713", "Levuka", "Fiji Islands" ],
    [ "5237B", "Lhotuan Approaches", "Kalimantan" ],
    [ "6666", "Lifuka Island (Pangai)", "Tonga Islands" ],
    [ "5046", "Liloan", "Philippine Islands" ],
    [ "2257", "Limao", "Brazil" ],
    [ "1984B", "Limassol", "Cyprus" ],
    [ "718", "Limerick Dock", "Ireland" ],
    [ "3806", "Limpopo River Bar", "Mozambique" ],
    [ "4929", "Linapakan Island", "Philippine Islands" ],
    [ "2291", "Linden", "Guyana" ],
    [ "3986", "Lindi", "Tanzania" ],
    [ "3811", "Linga-Linga", "Mozambique" ],
    [ "5251", "Lingkas", "Kalimantan" ],
    [ "5306", "Lingkobu", "Sulawesi East Coast" ],
    [ "5402", "Linteh", "Flores" ],
    [ "5255", "Lirung", "Kalimantan" ],
    [ "2322", "Lisas Point", "Trinidad" ],
    [ "1741", "Lisbon", "Portugal" ],
    [ "711", "Liscannor", "Ireland" ],
    [ "4615", "Little Andaman", "Andaman Islands" ],
    [ "2455", "Little Bay", "Leeward Islands" ],
    [ "2532", "Little Inagua", "Bahama Islands" ],
    [ "2067", "Lively Settlement", "Falkland Islands" ],
    [ "9555", "Lobos De Afuera", "Peru" ],
    [ "7094A", "Lok On Pai", "China" ],
    [ "5654", "Lolomo Passage", "Solomon Islands" ],
    [ "4607", "Long Island", "Andaman Islands" ],
    [ "2543", "Long Island, Bahamas", "Bahama Islands" ],
    [ "7334", "Longxu Wan", "China" ],
    [ "1049", "Lopshen'Ga", "Russia" ],
    [ "9401", "Loreto", "Mexico" ],
    [ "2508", "Los Arroyos", "Cuba" ],
    [ "683", "Loughros More Bay", "Ireland" ],
    [ "5891", "Low Wooded Isle", "Australia East Coast" ],
    [ "3766", "Luderitz", "Namibia" ],
    [ "5721", "Luganville (Santo)", "Vanuatu" ],
    [ "2246", "Luis Correia", "Brazil" ],
    [ "5144", "Lumut", "Brunei" ],
    [ "4674", "Lumut Pier", "Peninsular Malaysia West Coast" ],
    [ "5048", "Maasin", "Philippine Islands" ],
    [ "1506", "Maassluis", "Netherlands" ],
    [ "2204", "Macae (Imbetiba)", "Brazil" ],
    [ "2258", "Macapa", "Brazil" ],
    [ "2238", "Macau", "Brazil" ],
    [ "2227", "Maceio", "Brazil" ],
    [ "3474", "Machico", "Madeira Islands" ],
    [ "4457", "Machilipatnam", "India East Coast" ],
    [ "3833", "Macuse", "Mozambique" ],
    [ "3644", "Madagho", "Nigeria" ],
    [ "4131A", "Madinat Yanbu As Sinaiyah", "Saudi Arabia" ],
    [ "4941", "Maestre De Campo Island", "Philippine Islands" ],
    [ "4157", "Magatinal Saghir", "Republic Of Yemen" ],
    [ "2099A", "Magellan Strait East Entrance", "Argentina" ],
    [ "6429A", "Mahanga", "New Zealand North Island" ],
    [ "4175", "Mahawt", "Oman" ],
    [ "1829A", "Mahdia", "Tunisia" ],
    [ "5270", "Majene", "Sulawesi West Coast" ],
    [ "4190A", "Majis (Sohar)", "Oman" ],
    [ "4182B", "Makalla Wabar", "Oman" ],
    [ "6442", "Makara Beach", "New Zealand North Island" ],
    [ "2300", "Makauria", "Guyana" ],
    [ "3690", "Malabo", "Equatorial Guinea" ],
    [ "1773", "Malaga", "Spain" ],
    [ "5682", "Malaghara Island", "Solomon Islands" ],
    [ "621", "Malahide", "Ireland" ],
    [ "6820", "Malakal Harbour", "Palau Islands" ],
    [ "7335", "Malan Wan", "China" ],
    [ "6720", "Malau", "Fiji Islands" ],
    [ "4405", "Male", "Maldive Islands" ],
    [ "5639A", "Maleivona Island", "Solomon Islands" ],
    [ "4571", "Mali Kyun (Fisher Bay)", "Burma" ],
    [ "1900", "Mali Losinj", "Croatia" ],
    [ "3686", "Malimba", "Cameroon" ],
    [ "4024", "Malindi", "Kenya" ],
    [ "2372A", "Malmok Bay", "Nederlandse Antillen" ],
    [ "5182", "Malu", "Tudjuh Kepulauan" ],
    [ "5076", "Mambajao", "Philippine Islands" ],
    [ "3680", "Man O War Bay", "Cameroon" ],
    [ "2338", "Man Of War Bay", "Tobago" ],
    [ "5260", "Manado", "Sulawesi North Coast" ],
    [ "6709", "Manava Cay", "Fiji Islands" ],
    [ "6607", "Manihiki", "Cook Islands North" ],
    [ "4987", "Manila", "Philippine Islands" ],
    [ "5316", "Maninili", "Sulawesi East Coast" ],
    [ "3430", "Manitsoq", "Greenland West Coast" ],
    [ "3685", "Manoka", "Cameroon" ],
    [ "4939", "Mansalay", "Philippine Islands" ],
    [ "6708", "Manuqila Bay", "Fiji Islands" ],
    [ "2503", "Manzanillo, Cuba", "Cuba" ],
    [ "3824", "Mapanda", "Mozambique" ],
    [ "3804", "Maputo", "Mozambique" ],
    [ "3834", "Maquivale", "Mozambique" ],
    [ "2156A", "Mar Del Ajo", "Argentina" ],
    [ "2154", "Mar Del Plata", "Argentina" ],
    [ "4169", "Marbat", "Oman" ],
    [ "4127", "Mardunah", "Saudi Arabia" ],
    [ "2067C", "Mare Harbour", "Falkland Islands" ],
    [ "3972", "Marie Louise Island", "Seychelles" ],
    [ "1723", "Marin", "Spain" ],
    [ "2026", "Marina Point", "Antarctica" ],
    [ "752", "Marino Point", "Ireland" ],
    [ "2002", "Marion Island", "Antarctica" ],
    [ "4260", "Marjan Oilfield", "Saudi Arabia" ],
    [ "4037", "Marka", "Somalia" ],
    [ "5651", "Marovo Lagoon (Karunohu Island)", "Solomon Islands" ],
    [ "1996", "Marsa Al Burayqah", "Libya" ],
    [ "4186C", "Marsa Al Murjan", "Oman" ],
    [ "4094", "Marsa Sha'B", "Egypt" ],
    [ "2209", "Martin Vaz Islets", "Brazil" ],
    [ "2554A", "Mastic Point", "Bahama Islands" ],
    [ "2511", "Matanzas", "Cuba" ],
    [ "2531", "Mathew Town", "Bahama Islands" ],
    [ "3805", "Matola", "Mozambique" ],
    [ "5406", "Maumere", "Flores" ],
    [ "2009", "Mawson", "Antarctica" ],
    [ "5671", "Mbungana Island", "Solomon Islands" ],
    [ "3828", "Mchenga", "Mozambique" ],
    [ "4009", "Mchengangazi Pass", "Tanzania" ],
    [ "4351", "Mehegam", "India West Coast" ],
    [ "4699", "Melaka", "Peninsular Malaysia West Coast" ],
    [ "2037", "Melchior Islands", "Antarctica" ],
    [ "1817", "Melilla", "Morocco" ],
    [ "717", "Mellon Point", "Ireland" ],
    [ "5258", "Menalu", "Kalimantan" ],
    [ "7948", "Mera", "Japan Honshu South Coast" ],
    [ "5542", "Merauke", "Irian Jaya" ],
    [ "4237", "Mesaieed (Musay'Id)", "Qatar" ],
    [ "4236", "Mesaieed Outer Channel Entrance", "Qatar" ],
    [ "4011", "Mesali Island", "Tanzania" ],
    [ "4812", "Meulaboh", "Sumatera South West Coast" ],
    [ "5239", "Miang Besar", "Kalimantan" ],
    [ "796", "Midvagur", "Faeroe Islands" ],
    [ "1746", "Milfontes", "Portugal" ],
    [ "4264", "Mina Ad Dawhah", "Kuwait" ],
    [ "4262", "Mina Al Ahmadi", "Kuwait" ],
    [ "4186B", "Mina Al Fahl", "Oman" ],
    [ "4253", "Mina Al Manama", "Bahrain" ],
    [ "4261", "Mina Az Zawr (Mina Saud)", "Kuwait" ],
    [ "4194", "Mina Diba", "Oman" ],
    [ "1991A", "Mina' Dumyat", "Egypt" ],
    [ "4252", "Mina Salman", "Bahrain" ],
    [ "4210", "Mina Zayid", "United Arab Emirates" ],
    [ "4210B", "Mina Zayid Approaches", "United Arab Emirates" ],
    [ "4595", "Mingalakyun", "Coco Group" ],
    [ "5147", "Miri", "Sarawak" ],
    [ "4431", "Mirissa", "Sri Lanka" ],
    [ "1997", "Misratah", "Libya" ],
    [ "7964", "Miyake Shima", "Japan Nanpo Shoto" ],
    [ "4010", "Mkoani", "Tanzania" ],
    [ "4007", "Mkokotoni Harbour", "Tanzania" ],
    [ "4961", "Moalbual", "Philippine Islands" ],
    [ "3847", "Mocambo", "Mozambique" ],
    [ "3860", "Mocimboa Da Praia", "Mozambique" ],
    [ "1520A", "Moerdijk", "Netherlands" ],
    [ "6640", "Moku O Loe", "Hawaiian Islands" ],
    [ "5938", "Molle Island", "Australia East Coast" ],
    [ "2050", "Moltke Harbour", "Antarctica" ],
    [ "3841", "Moma", "Mozambique" ],
    [ "3840", "Moma River Bar", "Mozambique" ],
    [ "5307", "Momo", "Sulawesi East Coast" ],
    [ "1829", "Monastir", "Tunisia" ],
    [ "5652", "Monggo Passage", "Solomon Islands" ],
    [ "4498A", "Mongla", "Bangladesh" ],
    [ "2268", "Montagne D'Argent", "French Guiana" ],
    [ "1790", "Monte Carlo", "Monaco" ],
    [ "2151", "Monte Hermoso", "Argentina" ],
    [ "1740E", "Montijo", "Portugal" ],
    [ "3983", "Moroni", "Comoro Islands" ],
    [ "2219", "Morro De Sao Paulo", "Brazil" ],
    [ "3831", "Morrubune", "Mozambique" ],
    [ "3789", "Mossel Bay", "South Africa" ],
    [ "4555", "Moulmein", "Burma" ],
    [ "3981", "Moutsamoudou", "Comoro Islands" ],
    [ "655", "Moville", "Ireland" ],
    [ "4486", "Moyapur", "India East Coast" ],
    [ "4013", "Msuka Bay", "Tanzania" ],
    [ "3985", "Mtwara Bay", "Tanzania" ],
    [ "6725", "Muanicula", "Fiji Islands" ],
    [ "4702", "Muar", "Peninsular Malaysia West Coast" ],
    [ "5143", "Muara", "Brunei" ],
    [ "5232", "Muara Bayur (Outer Bar)", "Kalimantan" ],
    [ "5250", "Muara Biwan", "Kalimantan" ],
    [ "5245", "Muara Kassei", "Kalimantan" ],
    [ "5230", "Muara Pegah (Outer Bar)", "Kalimantan" ],
    [ "2101A", "Muelle El Turbio", "Argentina" ],
    [ "2105", "Muelle Frigorifico", "Argentina" ],
    [ "4091", "Muhammad Qol", "Sudan" ],
    [ "7043", "Mulan Tou (Hainan Head)", "China" ],
    [ "6683", "Mulifanua", "Samoa Islands" ],
    [ "688", "Mullaghmore", "Ireland" ],
    [ "665", "Mulroy Bay Bar", "Ireland" ],
    [ "1721", "Muros", "Spain" ],
    [ "2443", "Mustique", "Windward Islands" ],
    [ "4249A", "Mutarid", "Bahrain" ],
    [ "4026", "Mwamba Wa Ziwaiu", "Kenya" ],
    [ "4581", "Myauk Gaung Island", "Burma" ],
    [ "4566", "Myinkwa-Aw", "Burma" ],
    [ "1054", "Mys Glubokiy", "Russia" ],
    [ "1041", "Mys Kerets", "Russia" ],
    [ "1051", "Mys Letniy Orlov", "Russia" ],
    [ "1069", "Mys Pon'Goma Navolok", "Russia" ],
    [ "1070", "Mys Solomenny", "Russia" ],
    [ "6708A", "Nabukeru", "Fiji Islands" ],
    [ "3850", "Nacala", "Mozambique" ],
    [ "6719A", "Naduri", "Fiji Islands" ],
    [ "4247", "Nagiyah", "Qatar" ],
    [ "4273", "Nahr Umr", "Iraq" ],
    [ "6710B", "Naigani", "Fiji Islands" ],
    [ "6724", "Nakama Creek", "Fiji Islands" ],
    [ "4286", "Nakhilu", "Iran" ],
    [ "3751", "Namibe", "Angola" ],
    [ "4621", "Nancowry Harbour", "Nicobar Islands" ],
    [ "3437", "Nanortalik", "Greenland West Coast" ],
    [ "6710A", "Nanukuloa", "Fiji Islands" ],
    [ "4509", "Narayanganj", "Bangladesh" ],
    [ "2331", "Nariva River (Cocal)", "Trinidad" ],
    [ "3434B", "Narsaq", "Greenland West Coast" ],
    [ "5077", "Nasipit Harbour", "Philippine Islands" ],
    [ "4825", "Natal", "Sumatera South West Coast" ],
    [ "6722", "Natewa", "Fiji Islands" ],
    [ "6764", "Nauru", "Kiribati" ],
    [ "1738", "Nazare", "Portugal" ],
    [ "5713", "Ndendo Island", "Santa Cruz Islands" ],
    [ "4250D", "Ne Fasht Al Adhm", "Bahrain" ],
    [ "4562A", "Ne Of North Ledge", "Burma" ],
    [ "6671", "Neiafu", "Tonga Islands" ],
    [ "2034A", "Neko Harbour", "Antarctica" ],
    [ "1480", "Nes", "Netherlands" ],
    [ "856", "Nes Farm", "Iceland" ],
    [ "2287", "New Amsterdam", "Guyana" ],
    [ "3657", "New Calabar River Bar", "Nigeria" ],
    [ "2079", "New Island", "Falkland Islands" ],
    [ "4211B", "New Musafah Channel (Inner)", "United Arab Emirates" ],
    [ "4211A", "New Musafah Channel (Outer)", "United Arab Emirates" ],
    [ "763", "New Ross", "Ireland" ],
    [ "1789", "Nice", "France" ],
    [ "2284", "Nickerie River", "Suriname" ],
    [ "2279A", "Nieuw Amsterdam", "Suriname" ],
    [ "1475C", "Nieuwe Statenzijl", "Netherlands" ],
    [ "1565", "Nieuwpoort", "Belgium" ],
    [ "4970", "Nin Bay", "Philippine Islands" ],
    [ "4166", "Nishtun", "Republic Of Yemen" ],
    [ "6604", "Niue Island", "Cook Islands South" ],
    [ "4456", "Nizampatam", "India East Coast" ],
    [ "6798", "Nomoi Islands", "Caroline Islands" ],
    [ "6664", "Nomuka", "Tonga Islands" ],
    [ "1493", "Noordwinning (Platform K13-A)", "Netherlands" ],
    [ "861", "Nordfjordhur (Nes)", "Iceland" ],
    [ "784", "Nordskali", "Faeroe Islands" ],
    [ "4510", "Norman'S Point", "Bangladesh" ],
    [ "2065A", "North Arm", "Falkland Islands" ],
    [ "4917", "North Danger Reef", "Central China Sea Reefs" ],
    [ "4408", "North Huvadhu", "Maldive Islands" ],
    [ "3419", "North Star Bay", "Greenland West Coast" ],
    [ "2074", "North West Islands", "Falkland Islands" ],
    [ "5759", "Noumea", "New Caledonia" ],
    [ "2213", "Nova Vicosa", "Brazil" ],
    [ "2168", "Nueva Palmira", "Uruguay" ],
    [ "2517", "Nuevitas", "Cuba" ],
    [ "6500", "Nugget Point", "New Zealand South Island" ],
    [ "5669", "Nughu Island", "Solomon Islands" ],
    [ "6660", "Nuku'Alofa", "Tonga Islands" ],
    [ "2541", "Nurse Channel", "Bahama Islands" ],
    [ "3447A", "Nyhavn", "Greenland East Coast" ],
    [ "3731", "N'Zeto", "Angola" ],
    [ "4070", "Obock", "Djibouti" ],
    [ "4275", "Odin Point", "Iraq" ],
    [ "7992", "Ofunato", "Japan Honshu East Coast" ],
    [ "3643", "Ogidigbe", "Nigeria" ],
    [ "848", "Olafsfjordhur", "Iceland" ],
    [ "825A", "Olafsvik", "Iceland" ],
    [ "2409", "Old Providence", "Nicaragua" ],
    [ "4808", "Olee Iheue", "Sumatera North East Coast" ],
    [ "5549", "Omati", "Papua New Guinea" ],
    [ "1484", "Oost Vlieland", "Netherlands" ],
    [ "1564", "Oostende", "Belgium" ],
    [ "3666", "Opobo River Entrance (Sandy Point)", "Nigeria" ],
    [ "1735", "Oporto (Porto)", "Portugal" ],
    [ "2491", "Oracabessa", "Jamaica" ],
    [ "2372", "Oranjestad", "Nederlandse Antillen" ],
    [ "1064", "Ostrov Anzerskiy", "Russia" ],
    [ "1062", "Ostrov Konev", "Russia" ],
    [ "1058", "Ostrov Mal Korepalka", "Russia" ],
    [ "1061", "Ostrov Molchanov", "Russia" ],
    [ "1073", "Ostrov Sryedniy Guba Keret", "Russia" ],
    [ "1060", "Ostrov Sumostrov", "Russia" ],
    [ "1066", "Ostrov Yuzhnyy Rombak", "Russia" ],
    [ "1908", "Otok Svetac", "Croatia" ],
    [ "1488", "Oudeschild", "Netherlands" ],
    [ "785", "Oyndarfjordur", "Faeroe Islands" ],
    [ "5073", "Ozamiz", "Philippine Islands" ],
    [ "1740A", "Paco De Arcos", "Portugal" ],
    [ "4573", "Padaw-Aw", "Burma" ],
    [ "3697", "Pagalu (Annobon)", "Equatorial Guinea" ],
    [ "6677", "Pago Pago", "Samoa Islands" ],
    [ "5101", "Pakalangan", "Sabah" ],
    [ "4851", "Palembang", "Sumatera East Coast" ],
    [ "3862", "Palma (Baia De Tungue)", "Mozambique" ],
    [ "1780", "Palma De Mallorca", "Spain" ],
    [ "6620", "Palmyra Island", "Line Islands" ],
    [ "5050", "Palompon", "Philippine Islands" ],
    [ "4937", "Paluan", "Philippine Islands" ],
    [ "4925", "Paly Island", "Philippine Islands" ],
    [ "1920", "Pandeleimon", "Greece" ],
    [ "4008", "Pangani Bay", "Tanzania" ],
    [ "5212", "Pangkoh", "Kalimantan" ],
    [ "4841", "Panjang", "Sumatera South West Coast" ],
    [ "4924", "Pankol", "Philippine Islands" ],
    [ "5421", "Pantai Wonreli", "Sermata Eilanden" ],
    [ "6580", "Papeete", "Iles De La Societe" ],
    [ "868", "Papey", "Iceland" ],
    [ "2280", "Paramaribo", "Suriname" ],
    [ "2191B", "Paranagua", "Brazil" ],
    [ "2195", "Parati", "Brazil" ],
    [ "2293", "Parika", "Guyana" ],
    [ "4703", "Parit Jawa", "Peninsular Malaysia West Coast" ],
    [ "6120", "Parsons Bay", "Tasmania" ],
    [ "4978", "Pasacao", "Philippine Islands" ],
    [ "1694", "Pasajes", "Spain" ],
    [ "5139B", "Pasar Lawas", "Sarawak" ],
    [ "5174B", "Pasar Lundu", "Sarawak" ],
    [ "3723", "Pass Mateba", "Angola" ],
    [ "2044", "Pastorizo Bay", "Antarctica" ],
    [ "5363", "Pasuruan", "Jawa East Coast" ],
    [ "5457", "Patani", "Halmahera" ],
    [ "4584", "Pawei Kyun", "Burma" ],
    [ "2167", "Paysandu", "Uruguay" ],
    [ "2407", "Pearl Cays", "Nicaragua" ],
    [ "2083A", "Pebble Island", "Falkland Islands" ],
    [ "2242A", "Pecem", "Brazil" ],
    [ "1740B", "Pedroucos", "Portugal" ],
    [ "5210", "Pegatan", "Kalimantan" ],
    [ "4742", "Pelabuhan Kijang", "Riau Kepulauan" ],
    [ "4686", "Pelabuhan Klang", "Peninsular Malaysia West Coast" ],
    [ "4654", "Pelabuhan Kuah", "Peninsular Malaysia West Coast" ],
    [ "4896A", "Pelabuhan Kuantan", "Peninsular Malaysia East Coast" ],
    [ "4862", "Pelabuhan Pangkalbalam", "Pulau Bangka" ],
    [ "5181", "Pelabuhan Serasan", "Tudjuh Kepulauan" ],
    [ "2561", "Pelican Harbour", "Bahama Islands" ],
    [ "5191", "Pemangkat", "Kalimantan" ],
    [ "3855", "Pemba", "Mozambique" ],
    [ "5170", "Pending", "Sarawak" ],
    [ "1739", "Peniche", "Portugal" ],
    [ "2563", "Pensacola Cay", "Bahama Islands" ],
    [ "3582", "Pepel", "Sierra Leone" ],
    [ "4850", "Peradjin", "Sumatera East Coast" ],
    [ "3658", "Percival Point", "Nigeria" ],
    [ "4413", "Peros Banhos", "Chagos Archipelago" ],
    [ "1500", "Petten (South)", "Netherlands" ],
    [ "6132", "Pieman River", "Tasmania" ],
    [ "2155", "Pinamar", "Argentina" ],
    [ "4663", "Pinang (Georgetown)", "Peninsular Malaysia West Coast" ],
    [ "4688", "Pintu Gedong", "Peninsular Malaysia West Coast" ],
    [ "5865", "Piper Island", "Australia East Coast" ],
    [ "4345", "Piram Island", "India West Coast" ],
    [ "2425", "Placencia", "Belize" ],
    [ "5072", "Plaridel", "Philippine Islands" ],
    [ "3791", "Plettenberg Bay", "South Africa" ],
    [ "1908A", "Ploce", "Croatia" ],
    [ "2339", "Plymouth", "Tobago" ],
    [ "6795", "Pohnpei Harbour", "Caroline Islands" ],
    [ "6007", "Point Danger", "Australia East Coast" ],
    [ "2324", "Point Fortin", "Trinidad" ],
    [ "4439", "Point Pedro", "Sri Lanka" ],
    [ "3721", "Pointe Bulabemba", "Angola" ],
    [ "3724", "Pointe Camoens", "Angola" ],
    [ "3950", "Pointe Des Galets", "La Reunion" ],
    [ "3571A", "Pointe Malouine", "Guinea" ],
    [ "3716", "Pointe Noire", "The Congo" ],
    [ "2323", "Pointe-A-Pierre", "Trinidad" ],
    [ "5065", "Pollok Harbour", "Philippine Islands" ],
    [ "2302", "Pomerun River Mouth", "Guyana" ],
    [ "3560", "Ponta Biombo", "Guinea-Bissau" ],
    [ "2249A", "Ponta Da Madeira", "Brazil" ],
    [ "3467", "Ponta Delgada", "Azores" ],
    [ "2221", "Ponta Do Alambique", "Brazil" ],
    [ "1750", "Ponta Do Altar", "Portugal" ],
    [ "2256A", "Ponta Do Ceu", "Brazil" ],
    [ "2192B", "Ponta Paranapua", "Brazil" ],
    [ "5195", "Pontianak", "Kalimantan" ],
    [ "5194", "Pontianak Outer Bar (Kleine Kapoeas)", "Kalimantan" ],
    [ "3794", "Port Alfred", "South Africa" ],
    [ "3733", "Port Ambriz", "Angola" ],
    [ "5030", "Port Anajao", "Philippine Islands" ],
    [ "4600", "Port Anson", "Andaman Islands" ],
    [ "4940", "Port Balanacan", "Philippine Islands" ],
    [ "4971", "Port Barrera", "Philippine Islands" ],
    [ "3788", "Port Beaufort", "South Africa" ],
    [ "6497", "Port Chalmers", "New Zealand South Island" ],
    [ "4605", "Port Cornwallis", "Andaman Islands" ],
    [ "3262", "Port De Boucherville", "Labrador" ],
    [ "4695", "Port Dickson", "Peninsular Malaysia West Coast" ],
    [ "2082C", "Port Egmont", "Falkland Islands" ],
    [ "3793", "Port Elizabeth", "South Africa" ],
    [ "2484", "Port Esquivel", "Jamaica" ],
    [ "3664", "Port Harcourt", "Nigeria" ],
    [ "2074B", "Port Howard", "Falkland Islands" ],
    [ "2007", "Port Jeanne D'Arc", "Antarctica" ],
    [ "5027", "Port Jose Panganiban", "Philippine Islands" ],
    [ "5064", "Port Lebak", "Philippine Islands" ],
    [ "3956", "Port Louis, Mauritius", "Mauritius Group" ],
    [ "4576", "Port Maria", "Burma" ],
    [ "3205", "Port Marnham", "Labrador" ],
    [ "4990", "Port Masinloc", "Philippine Islands" ],
    [ "2482", "Port Morant", "Jamaica" ],
    [ "3773", "Port Nolloth", "South Africa" ],
    [ "1067", "Port Of Kem'", "Russia" ],
    [ "2321", "Port Of Spain", "Trinidad" ],
    [ "5053", "Port Pilar", "Philippine Islands" ],
    [ "2483", "Port Royal", "Jamaica" ],
    [ "2418", "Port Royal, Honduras", "Honduras" ],
    [ "4168", "Port Salalah", "Oman" ],
    [ "2070", "Port Salvador Entrance", "Falkland Islands" ],
    [ "2072", "Port San Carlos", "Falkland Islands" ],
    [ "5013", "Port San Pio Quinto", "Philippine Islands" ],
    [ "5727", "Port Sandwich", "Vanuatu" ],
    [ "5088", "Port Siasi", "Sulu Archipelago" ],
    [ "3852", "Port Simuco", "Mozambique" ],
    [ "3679", "Port Sonara", "Nigeria" ],
    [ "3797", "Port St. John'S", "South Africa" ],
    [ "2077B", "Port Stephens", "Falkland Islands" ],
    [ "4186A", "Port Sultan Qaboos", "Oman" ],
    [ "4985", "Port Tilic", "Philippine Islands" ],
    [ "1782", "Port Vendres", "France" ],
    [ "3967", "Port Victoria", "Seychelles" ],
    [ "5732", "Port Vila", "Vanuatu" ],
    [ "4670", "Port Weld", "Peninsular Malaysia West Coast" ],
    [ "1749A", "Portimao", "Portugal" ],
    [ "3740", "Porto Amboim", "Angola" ],
    [ "2188", "Porto Belo", "Brazil" ],
    [ "2203", "Porto Buzios", "Brazil" ],
    [ "3459", "Porto Da Casa", "Azores" ],
    [ "3473", "Porto Da Cruz", "Madeira Islands" ],
    [ "3498", "Porto Da Praia", "Cape Verde Islands" ],
    [ "3844", "Porto De Angoche", "Mozambique" ],
    [ "2221B", "Porto De Aratu", "Brazil" ],
    [ "1736", "Porto De Aveiro", "Portugal" ],
    [ "3816", "Porto De Bartolomeu Dias", "Mozambique" ],
    [ "2254", "Porto De Breves", "Brazil" ],
    [ "3818", "Porto De Chiloane", "Mozambique" ],
    [ "3827", "Porto De Chinde", "Mozambique" ],
    [ "1752", "Porto De Faro-Olhao", "Portugal" ],
    [ "1733", "Porto De Leixoes", "Portugal" ],
    [ "3736", "Porto De Luanda", "Angola" ],
    [ "2221A", "Porto De Madre De Deus", "Brazil" ],
    [ "3838", "Porto De Moebase", "Mozambique" ],
    [ "2252B", "Porto De Mosqueiro", "Brazil" ],
    [ "3848", "Porto De Mozambique", "Mozambique" ],
    [ "2233", "Porto De Natal", "Brazil" ],
    [ "3836", "Porto De Pebane", "Mozambique" ],
    [ "2227A", "Porto De Pedras", "Brazil" ],
    [ "3496", "Porto De Sal Rei", "Cape Verde Islands" ],
    [ "2259", "Porto De Santana", "Brazil" ],
    [ "2198A", "Porto De Sepetiba (Itaguai)", "Brazil" ],
    [ "3820", "Porto De Sofala", "Mozambique" ],
    [ "2228A", "Porto De Suape", "Brazil" ],
    [ "3857", "Porto Do Ibo", "Mozambique" ],
    [ "3471", "Porto Do Moniz", "Madeira Islands" ],
    [ "2211A", "Porto Do Tubarao", "Brazil" ],
    [ "3563", "Porto Gole", "Guinea-Bissau" ],
    [ "3492", "Porto Grande De S. Vicente", "Cape Verde Islands" ],
    [ "3743", "Porto Lobito", "Angola" ],
    [ "1894A", "Porto Marghera", "Italy" ],
    [ "3475", "Porto Santo", "Madeira Islands" ],
    [ "2215", "Porto Seguro", "Brazil" ],
    [ "3564", "Porto Uana", "Guinea-Bissau" ],
    [ "2450A", "Portsmouth, Dominica", "Leeward Islands" ],
    [ "1700", "Portugalete (Bilbao)", "Spain" ],
    [ "5315", "Poso", "Sulawesi East Coast" ],
    [ "5839", "Possession Island", "Australia" ],
    [ "2041", "Potter Cove", "Antarctica" ],
    [ "1732", "Povoa De Varzim", "Portugal" ],
    [ "3466A", "Praia Da Vitoria", "Azores" ],
    [ "3965B", "Praslin", "Seychelles" ],
    [ "2439A", "Prickly Bay", "Windward Islands" ],
    [ "9893", "Primera Angostura", "Chile" ],
    [ "3767", "Prince Of Wales Bay", "Namibia" ],
    [ "2024", "Prospect Point", "Antarctica" ],
    [ "2147", "Puerto Belgrano", "Argentina" ],
    [ "9622", "Puerto Caldera", "Chile" ],
    [ "2344", "Puerto Carupano", "Venezuela" ],
    [ "9439", "Puerto Chiapas", "Mexico" ],
    [ "9671", "Puerto Corral", "Chile" ],
    [ "2149", "Puerto Cuatreros", "Argentina" ],
    [ "3488", "Puerto De Arrecife", "Canary Islands" ],
    [ "3485", "Puerto De La Luz", "Canary Islands" ],
    [ "1761", "Puerto De Santa Maria", "Spain" ],
    [ "2509B", "Puerto Del Mariel", "Cuba" ],
    [ "2109", "Puerto Deseado", "Argentina" ],
    [ "2148", "Puerto Ingeniero White", "Argentina" ],
    [ "2164", "Puerto La Plata", "Argentina" ],
    [ "9665", "Puerto Lebu", "Chile" ],
    [ "2126", "Puerto Madryn", "Argentina" ],
    [ "2117", "Puerto Melo", "Argentina" ],
    [ "2518", "Puerto Padre", "Cuba" ],
    [ "2502", "Puerto Pilon", "Cuba" ],
    [ "2127", "Puerto Piramide", "Argentina" ],
    [ "5052", "Puerto Princesa", "Philippine Islands" ],
    [ "2135", "Puerto Punta Colorado", "Argentina" ],
    [ "2146", "Puerto Rosales", "Argentina" ],
    [ "2136", "Puerto San Antonio", "Argentina" ],
    [ "2140", "Puerto San Blas", "Argentina" ],
    [ "2088", "Puerto San Juan Del Salvamento", "Argentina" ],
    [ "2103", "Puerto Santa Cruz Bar", "Argentina" ],
    [ "2121", "Puerto Santa Elena", "Argentina" ],
    [ "2170", "Puerto Sauce", "Uruguay" ],
    [ "2522", "Puerto Tanamo", "Cuba" ],
    [ "2087", "Puerto Vancouver", "Argentina" ],
    [ "2132", "Pueyrredon", "Argentina" ],
    [ "6610", "Pukapuka", "Cook Islands North" ],
    [ "4684", "Pulau Angsa", "Peninsular Malaysia West Coast" ],
    [ "4886", "Pulau Babi Besar", "Peninsular Malaysia East Coast" ],
    [ "5292", "Pulau Baleara", "Sulawesi West Coast" ],
    [ "5122", "Pulau Banggi", "Sabah" ],
    [ "5428", "Pulau Barakan", "Sermata Eilanden" ],
    [ "4755", "Pulau Beralas", "Lingga Kepulauan" ],
    [ "4655", "Pulau Beras Basah", "Peninsular Malaysia West Coast" ],
    [ "4894", "Pulau Berhala", "Peninsular Malaysia East Coast" ],
    [ "4756", "Pulau Berhala (Lingga Kepulauan)", "Lingga Kepulauan" ],
    [ "4859", "Pulau Besar", "Pulau Bangka" ],
    [ "4592", "Pulau Besin", "Burma" ],
    [ "4659", "Pulau Bidan", "Peninsular Malaysia West Coast" ],
    [ "4854", "Pulau Cebia", "Sumatera East Coast" ],
    [ "4865", "Pulau Celaka", "Pulau Bangka" ],
    [ "5341", "Pulau Damar Besar", "Jawa North Coast" ],
    [ "4860", "Pulau Dapur", "Pulau Bangka" ],
    [ "5276", "Pulau Dewakang Besar", "Sulawesi West Coast" ],
    [ "5293", "Pulau Galla Besar", "Sulawesi West Coast" ],
    [ "5436", "Pulau Geser", "The Molucca Islands" ],
    [ "5375", "Pulau Goagoa", "Madura" ],
    [ "4676", "Pulau Jarak", "Peninsular Malaysia West Coast" ],
    [ "5275", "Pulau Kalukalukuang", "Sulawesi West Coast" ],
    [ "5367", "Pulau Karangjamuang", "Jawa East Coast" ],
    [ "4675", "Pulau Katak", "Peninsular Malaysia West Coast" ],
    [ "5303", "Pulau Kokoila", "Sulawesi East Coast" ],
    [ "4870", "Pulau Langkuas", "Belitung" ],
    [ "5118", "Pulau Lankayan", "Sabah" ],
    [ "5178", "Pulau Laut", "Tudjuh Kepulauan" ],
    [ "5419", "Pulau Liran", "Sermata Eilanden" ],
    [ "5130", "Pulau Mangalum", "Sabah" ],
    [ "5127", "Pulau Mantanani Besar", "Sabah" ],
    [ "5187", "Pulau Mentebung", "Tudjuh Kepulauan" ],
    [ "5344", "Pulau Merak Besar", "Jawa North Coast" ],
    [ "4769", "Pulau Muda", "Sumatera North East Coast" ],
    [ "5341A", "Pulau Pari", "Jawa North Coast" ],
    [ "5499", "Pulau Peli", "Irian Jaya" ],
    [ "5337", "Pulau Rakit", "Jawa North Coast" ],
    [ "4810", "Pulau Raya", "Sumatera South West Coast" ],
    [ "4664", "Pulau Rimau", "Peninsular Malaysia West Coast" ],
    [ "4868", "Pulau Ru", "Belitung" ],
    [ "4809", "Pulau Rusa", "Sumatera South West Coast" ],
    [ "5274", "Pulau Sabaru", "Sulawesi West Coast" ],
    [ "5389", "Pulau Sailus Besar", "Lombok" ],
    [ "4746A", "Pulau Sambu", "Riau Kepulauan" ],
    [ "5374", "Pulau Sapudi", "Madura" ],
    [ "5390", "Pulau Sapuka Besar", "Lombok" ],
    [ "5174", "Pulau Satang Besar", "Sarawak" ],
    [ "5376", "Pulau Saubi", "Madura" ],
    [ "4875", "Pulau Selandu (Near)", "Belitung" ],
    [ "4867", "Pulau Seliu", "Belitung" ],
    [ "4866", "Pulau Simedang", "Pulau Bangka" ],
    [ "5180", "Pulau Subi Kecil", "Tudjuh Kepulauan" ],
    [ "5359", "Pulau Tabuan", "Jawa East Coast" ],
    [ "5111", "Pulau Tambisan", "Sabah" ],
    [ "5432", "Pulau Tayandu", "Sermata Eilanden" ],
    [ "4827", "Pulau Telo", "Sumatera South West Coast" ],
    [ "5193", "Pulau Temaju", "Kalimantan" ],
    [ "5282", "Pulau Tengah", "Sulawesi West Coast" ],
    [ "5121", "Pulau Tigabu", "Sabah" ],
    [ "5268", "Pulau Tobintah", "Sulawesi West Coast" ],
    [ "4832", "Pulau Tonggo", "Sumatera South West Coast" ],
    [ "4701", "Pulau Undan", "Peninsular Malaysia West Coast" ],
    [ "4858", "Pulau-Pulau Nangka", "Pulau Bangka" ],
    [ "5342", "Pulau-Pulau Seribu", "Jawa North Coast" ],
    [ "4453", "Pulicat", "India East Coast" ],
    [ "6804", "Puluwat Island", "Caroline Islands" ],
    [ "5140", "Punang", "Sarawak" ],
    [ "3822", "Pungue River Bar", "Mozambique" ],
    [ "2525", "Punta  Maisi", "Cuba" ],
    [ "1766", "Punta Camarinal", "Spain" ],
    [ "2520", "Punta Caranero", "Cuba" ],
    [ "1768A", "Punta Carnero", "Spain" ],
    [ "2382", "Punta De Palmas", "Venezuela" ],
    [ "2128", "Punta Delgada", "Argentina" ],
    [ "2199", "Punta Do Imbui", "Brazil" ],
    [ "2143", "Punta Laberinto", "Argentina" ],
    [ "2145", "Punta Lobos", "Argentina" ],
    [ "2101", "Punta Loyola (Puerto Gallegos)", "Argentina" ],
    [ "2156", "Punta Medanos", "Argentina" ],
    [ "2125", "Punta Ninfas", "Argentina" ],
    [ "2130", "Punta Norte", "Argentina" ],
    [ "2160", "Punta Piedras", "Argentina" ],
    [ "2104", "Punta Quilla", "Argentina" ],
    [ "2138", "Punta Redonda", "Argentina" ],
    [ "2150", "Punta Tejada", "Argentina" ],
    [ "2468", "Punta Tuna", "Puerto Rico" ],
    [ "2305", "Punta Waini", "Guyana" ],
    [ "5162", "Pusa", "Sarawak" ],
    [ "4496", "Pussur River Entrance", "Bangladesh" ],
    [ "4542", "Pyinsalu", "Burma" ],
    [ "4544", "Pymbong Beacon", "Burma" ],
    [ "4182A", "Qalhat Lng Terminal", "Oman" ],
    [ "4272", "Qarmat Ali Bar", "Iraq" ],
    [ "4165", "Qishn", "Republic Of Yemen" ],
    [ "3667", "Qua Iboe River Entrance", "Nigeria" ],
    [ "3423", "Quamarujuk", "Greenland West Coast" ],
    [ "3832", "Quelimane", "Mozambique" ],
    [ "9463", "Quepos", "Costa Rica" ],
    [ "2153", "Quequen", "Argentina" ],
    [ "656", "Quigley'S Point", "Ireland" ],
    [ "3722", "Quissanga", "Angola" ],
    [ "4253D", "Qurayyah Pier", "Bahrain" ],
    [ "4276", "Qurna", "Iraq" ],
    [ "4184", "Quryat", "Oman" ],
    [ "4056", "Raas Caseyr (Capo Guardafui)", "Somalia" ],
    [ "4048", "Raas Xaafuun", "Somalia" ],
    [ "4133", "Rabigh", "Saudi Arabia" ],
    [ "4503", "Rabnabad Channel (Patua)", "Bangladesh" ],
    [ "1520B", "Rak (North)", "Netherlands" ],
    [ "4737", "Ramunia Jetty", "Peninsular Malaysia South Coast" ],
    [ "6598", "Rarotonga (Avarua Harbour)", "Cook Islands South" ],
    [ "4235", "Ras Abu Qumayyis", "Qatar" ],
    [ "4265", "Ras Al Barshah (Beacon No. 2)", "Kuwait" ],
    [ "4212", "Ras Al Ghaf", "United Arab Emirates" ],
    [ "4180", "Ras Al Hadd", "Oman" ],
    [ "4250", "Ras Al Jamal", "Bahrain" ],
    [ "4146", "Ras Al Katib", "Republic Of Yemen" ],
    [ "4201", "Ras Al Khaymah", "United Arab Emirates" ],
    [ "4309", "Ras Al Kuh", "Iran" ],
    [ "4171", "Ras Al Madrakah", "Oman" ],
    [ "4182C", "Ras Ash Shajar", "Oman" ],
    [ "4196", "Ras Dillah", "Oman" ],
    [ "1843", "Ras El Ketef", "Tunisia" ],
    [ "4176", "Ras Hilf", "Oman" ],
    [ "1830", "Ras Kaboudia", "Tunisia" ],
    [ "4005", "Ras Kizimkazi", "Tanzania" ],
    [ "4242", "Ras Laffan", "Qatar" ],
    [ "4147", "Ras Mujamila", "Republic Of Yemen" ],
    [ "4051", "Ra'S Qalansiyah", "Suqutra" ],
    [ "4000A", "Ras Rangoni", "Tanzania" ],
    [ "4159", "Ras Safwan", "Republic Of Yemen" ],
    [ "4173", "Ras Sarab", "Oman" ],
    [ "4163", "Ras Sharmah", "Republic Of Yemen" ],
    [ "4178", "Ras Sheiblah", "Oman" ],
    [ "4246", "Ras 'Ushayrij", "Qatar" ],
    [ "4313", "Ras-E Tang", "Iran" ],
    [ "664", "Rathmullan", "Ireland" ],
    [ "852", "Raufarhofn", "Iceland" ],
    [ "2152", "Recalada", "Argentina" ],
    [ "2229", "Recife", "Brazil" ],
    [ "6268", "Red Bluff", "Australia North Coast" ],
    [ "2211C", "Regencia", "Brazil" ],
    [ "1074", "Reka Kovda", "Russia" ],
    [ "1079", "Reka Varzuga", "Russia" ],
    [ "5331", "Rembang", "Jawa North Coast" ],
    [ "7206", "Ren Yu", "China" ],
    [ "5867", "Restoration Island", "Australia East Coast" ],
    [ "828A", "Reykanes", "Iceland" ],
    [ "840", "Reykjarfjordhur", "Iceland" ],
    [ "819", "Reykjavik", "Iceland" ],
    [ "2102", "Ria Coig", "Argentina" ],
    [ "1719", "Ria De Camarinas", "Spain" ],
    [ "1718", "Ria De Corme E Laxe", "Spain" ],
    [ "1754", "Ria De Huelva Bar", "Spain" ],
    [ "3801", "Richards Bay", "South Africa" ],
    [ "825", "Rif", "Iceland" ],
    [ "3428", "Rifkol Island", "Greenland West Coast" ],
    [ "1898", "Rijeka (Fiume)", "Croatia" ],
    [ "751", "Ringaskiddy", "Ireland" ],
    [ "5729", "Ringdove Bay", "Vanuatu" ],
    [ "3699", "Rio Benito", "Equatorial Guinea" ],
    [ "2262", "Rio Cunani", "Brazil" ],
    [ "2200", "Rio De Janeiro", "Brazil" ],
    [ "3677", "Rio Del Rey Entrance", "Cameroon" ],
    [ "1734", "Rio Douro Entrance", "Portugal" ],
    [ "2422", "Rio Dulce Entrance", "Guatemala" ],
    [ "2179", "Rio Grande", "Brazil" ],
    [ "2097", "Rio Grande (Puerto)", "Argentina" ],
    [ "2096", "Rio Grande Entrance, Argentina", "Argentina" ],
    [ "1756", "Rio Guadalquivir Bar (Chipiona)", "Spain" ],
    [ "3570", "Rio Nunez Approaches", "Guinea" ],
    [ "2312", "Rio Pedernales (Lagoven Jetty)", "Venezuela" ],
    [ "2226", "Rio Sao Francisco Bar", "Brazil" ],
    [ "2385", "Riohacha", "Colombia" ],
    [ "5427", "Ritabel Bay", "Sermata Eilanden" ],
    [ "623", "River Boyne Bar", "Ireland" ],
    [ "2459", "Road Bay", "Leeward Islands" ],
    [ "748", "Roberts Cove", "Ireland" ],
    [ "3959", "Rodrigues", "Mauritius Group" ],
    [ "1905", "Rogoznica", "Croatia" ],
    [ "4943", "Romblon Island", "Philippine Islands" ],
    [ "2144", "Romero Chico", "Argentina" ],
    [ "2045", "Ronne Ice Shelf", "Antarctica" ],
    [ "1528", "Roompot Buiten", "Netherlands" ],
    [ "700", "Roonah Quay", "Ireland" ],
    [ "767", "Rosslare Europort", "Ireland" ],
    [ "1760", "Rota", "Spain" ],
    [ "2022", "Rothera Point", "Antarctica" ],
    [ "1508", "Rotterdam", "Netherlands" ],
    [ "6740", "Rotuma Island", "Fiji Islands" ],
    [ "5819", "Round Island", "Australia" ],
    [ "4176A", "Rounders Bay", "Oman" ],
    [ "705", "Roundstone Bay", "Ireland" ],
    [ "5648A", "Roviana Lagoon (Mbaraulu)", "Solomon Islands" ],
    [ "1898B", "Rovinj", "Croatia" ],
    [ "2081A", "Roy Cove", "Falkland Islands" ],
    [ "2551", "Royal Island Harbour", "Bahama Islands" ],
    [ "3647", "Rugged Point", "Nigeria" ],
    [ "6706", "Rukua", "Fiji Islands" ],
    [ "5433", "Rumahlusi", "Sermata Eilanden" ],
    [ "3984", "Ruvuma Bay", "Tanzania" ],
    [ "1736A", "S. Jacinto", "Portugal" ],
    [ "5447", "Sabatang", "The Molucca Islands" ],
    [ "5417", "Saenamo", "East Timor" ],
    [ "4529", "Sagu Kyun", "Burma" ],
    [ "4189B", "Saham", "Oman" ],
    [ "7124", "Sai Kung Hoi", "China" ],
    [ "4189", "Said Bin Sultan Naval Base", "Oman" ],
    [ "2461A", "Saint John", "Leeward Islands" ],
    [ "2275", "Saint Laurent Du Maroni", "French Guiana" ],
    [ "6830", "Saipan", "Marianas Islands" ],
    [ "5304", "Salabangka", "Sulawesi East Coast" ],
    [ "3996", "Salale", "Tanzania" ],
    [ "6030", "Salamander Bay", "Australia East Coast" ],
    [ "3779", "Saldanha", "South Africa" ],
    [ "2251", "Salinopolis", "Brazil" ],
    [ "4412", "Salomon Islands", "Chagos Archipelago" ],
    [ "2222", "Salvador", "Brazil" ],
    [ "5566", "Samarai Island", "Papua New Guinea" ],
    [ "5235", "Samarinda", "Kalimantan" ],
    [ "4958", "San Carlos", "Philippine Islands" ],
    [ "2165A", "San Fernando", "Argentina" ],
    [ "4972", "San Pascual", "Philippine Islands" ],
    [ "3610", "San Pedro", "Cote D'Ivoire" ],
    [ "2131", "San Roman", "Argentina" ],
    [ "2539", "San Salvador", "Bahama Islands" ],
    [ "4138", "Sanak Island, Saudi Arabia", "Saudi Arabia" ],
    [ "5327", "Sanana", "The Molucca Islands" ],
    [ "6654", "Sand Island", "Hawaiian Islands" ],
    [ "5115", "Sandakan", "Sabah" ],
    [ "815", "Sandgerdhi", "Iceland" ],
    [ "4490", "Sandhead", "India East Coast" ],
    [ "7219", "Sandu Dao", "China" ],
    [ "799", "Sandur", "Faeroe Islands" ],
    [ "3762", "Sandwich Harbour", "Namibia" ],
    [ "4507", "Sandwip Island", "Bangladesh" ],
    [ "1770A", "Sandy Bay", "Gibraltar" ],
    [ "2530", "Sandy Point", "Turks Islands" ],
    [ "5329", "Sangkapura Bay", "Jawa North Coast" ],
    [ "3460A", "Santa Cruz (Flores)", "Azores" ],
    [ "9520", "Santa Cruz (Galapagos Is)", "Ecuador" ],
    [ "3465", "Santa Cruz (Graciosa)", "Azores" ],
    [ "3480", "Santa Cruz De La Palma", "Canary Islands" ],
    [ "3484", "Santa Cruz De Tenerife", "Canary Islands" ],
    [ "1715", "Santa Marta De Ortigueira", "Spain" ],
    [ "1703", "Santander", "Spain" ],
    [ "2501", "Santiago", "Cuba" ],
    [ "2193", "Santos", "Brazil" ],
    [ "5173", "Santubong", "Sarawak" ],
    [ "5381", "Sanur", "Bali" ],
    [ "1722A", "Sanxenxo", "Spain" ],
    [ "2190", "Sao Francisco Do Sul", "Brazil" ],
    [ "2249", "Sao Luis", "Brazil" ],
    [ "2194", "Sao Sebastiao", "Brazil" ],
    [ "3642", "Sapele", "Nigeria" ],
    [ "4200", "Saqr Port (Mina Saqr)", "United Arab Emirates" ],
    [ "5158", "Sarikei", "Sarawak" ],
    [ "4210C", "Sas An Nakhl", "United Arab Emirates" ],
    [ "5636A", "Sasamungga", "Solomon Islands" ],
    [ "3611", "Sassandra Anchorage", "Cote D'Ivoire" ],
    [ "844", "Saudarkrokur", "Iceland" ],
    [ "2082B", "Saunders Island", "Falkland Islands" ],
    [ "2486", "Savanna La Mar", "Jamaica" ],
    [ "4087", "Sawakin", "Sudan" ],
    [ "4067", "Saylac", "Somalia" ],
    [ "4918", "Scarborough Shoal", "Central China Sea Reefs" ],
    [ "2336", "Scarborough, Tobago", "Tobago" ],
    [ "5949", "Scawfell Island", "Australia East Coast" ],
    [ "1503", "Scheveningen", "Netherlands" ],
    [ "1477", "Schiermonnikoog", "Netherlands" ],
    [ "1511", "Schoonhoven", "Netherlands" ],
    [ "3780", "Schrywers Hoek", "South Africa" ],
    [ "742", "Schull", "Ireland" ],
    [ "2055", "Scotia Bay", "Antarctica" ],
    [ "2018", "Scott Base", "Antarctica" ],
    [ "712", "Seafield Point", "Ireland" ],
    [ "3194", "Seal Cove", "Newfoundland" ],
    [ "667", "Seamount Bay", "Ireland" ],
    [ "4526", "Searle Point", "Burma" ],
    [ "5179", "Sedanau", "Tudjuh Kepulauan" ],
    [ "4187", "Seeb", "Oman" ],
    [ "5355", "Segoro Wedi Bay", "Jawa South Coast" ],
    [ "2139", "Segunda Barranca", "Argentina" ],
    [ "1740D", "Seixal", "Portugal" ],
    [ "3622", "Sekondi", "Ghana" ],
    [ "4746B", "Sekupang", "Riau Kepulauan" ],
    [ "4743", "Selat Kijang Entrance (North)", "Riau Kepulauan" ],
    [ "5177", "Selat Peninting", "Tudjuh Kepulauan" ],
    [ "5175", "Sematan", "Sarawak" ],
    [ "5369", "Sembilangan (Madura)", "Madura" ],
    [ "5333", "Semerang (Tanjung Emas)", "Jawa North Coast" ],
    [ "5103", "Semporna", "Sabah" ],
    [ "1899", "Senj", "Croatia" ],
    [ "2225A", "Sergipe Terminal", "Brazil" ],
    [ "5145", "Seria", "Brunei" ],
    [ "6246", "Serrurier (Long) Island", "Australia North Coast" ],
    [ "1743", "Sesimbra", "Portugal" ],
    [ "4904", "Setiu", "Peninsular Malaysia East Coast" ],
    [ "1744", "Setubal (Troia)", "Portugal" ],
    [ "1046", "Severodvinsk", "Russia" ],
    [ "1759", "Sevilla", "Spain" ],
    [ "2046", "Shackleton Base", "Antarctica" ],
    [ "2018A", "Shackleton Glacier", "Antarctica" ],
    [ "4274", "Shafi Creek", "Iraq" ],
    [ "4205", "Sharjah", "United Arab Emirates" ],
    [ "4125", "Sharm An Nu'Man", "Saudi Arabia" ],
    [ "4115", "Sharm Ash Shaykh (Sharm El Sheikh)", "Egypt" ],
    [ "4268", "Shatt Al Arab Outer Bar", "Iraq" ],
    [ "3586A", "Sheather Rock", "Sierra Leone" ],
    [ "3591", "Shebar Entrance", "Sierra Leone" ],
    [ "4028", "Shela", "Kenya" ],
    [ "3586", "Shenge Point", "Sierra Leone" ],
    [ "4191", "Shinas", "Oman" ],
    [ "2547", "Ship Channel", "Bahama Islands" ],
    [ "7239", "Shipu Gang", "China" ],
    [ "4050", "Shiq", "Suqutra" ],
    [ "4475", "Shortt Island", "India East Coast" ],
    [ "4156", "Shuqra", "Republic Of Yemen" ],
    [ "1904", "Sibenik", "Croatia" ],
    [ "4820", "Sibolga", "Sumatera South West Coast" ],
    [ "5159", "Sibu", "Sarawak" ],
    [ "5069", "Sibuco Bay", "Philippine Islands" ],
    [ "4185B", "Sidab", "Oman" ],
    [ "4560", "Sidaw Point", "Burma" ],
    [ "3520A", "Sidi Ifni", "Morocco" ],
    [ "1988A", "Sidon", "Lebanon" ],
    [ "5061", "Sigaboy", "Philippine Islands" ],
    [ "4805", "Sigli", "Sumatera North East Coast" ],
    [ "847", "Siglufjordhur", "Iceland" ],
    [ "2056", "Signy Island", "Antarctica" ],
    [ "5639", "Sikopo Island", "Solomon Islands" ],
    [ "4822", "Simanari", "Sumatera South West Coast" ],
    [ "3995", "Simba Uranga", "Tanzania" ],
    [ "3784", "Simon'S Town", "South Africa" ],
    [ "5169", "Simunjan", "Sarawak" ],
    [ "4547", "Sin Min Point (Elephant Point)", "Burma" ],
    [ "4568", "Sinbyubyin", "Burma" ],
    [ "1745", "Sines", "Portugal" ],
    [ "5155C", "Singat", "Sarawak" ],
    [ "4818", "Singkel", "Sumatera South West Coast" ],
    [ "2273", "Sinnamary", "French Guiana" ],
    [ "3601", "Sinoe Bay", "Liberia" ],
    [ "5139", "Sipitang", "Sabah" ],
    [ "4211", "Sir Abu Nu'Ayr", "United Arab Emirates" ],
    [ "4223", "Sir Bani Yas", "United Arab Emirates" ],
    [ "4324", "Sir Mouth", "Pakistan" ],
    [ "4520", "Sittwe", "Burma" ],
    [ "843", "Skagastrond", "Iceland" ],
    [ "1411", "Skagen", "Denmark" ],
    [ "788", "Skalafjordur", "Faeroe Islands" ],
    [ "798", "Skopun", "Faeroe Islands" ],
    [ "689", "Sligo Harbour (Oyster Island)", "Ireland" ],
    [ "1392", "Slipshavn", "Denmark" ],
    [ "704", "Slyne Head", "Ireland" ],
    [ "722", "Smerwick Harbour", "Ireland" ],
    [ "625", "Soldiers Point", "Ireland" ],
    [ "1065", "Solovetskiy", "Russia" ],
    [ "4321", "Sonmiani Harbour", "Pakistan" ],
    [ "3195", "Sops Island", "Newfoundland" ],
    [ "4976", "Sorsogon", "Philippine Islands" ],
    [ "795", "Sorvagur", "Faeroe Islands" ],
    [ "1988B", "Sour", "Lebanon" ],
    [ "4625", "South (Galatea) Bay", "Nicobar Islands" ],
    [ "2557", "South Riding Rock", "Bahama Islands" ],
    [ "2058", "Southern Thule", "Antarctica" ],
    [ "3720", "Soyo", "Angola" ],
    [ "2076", "Speedwell Island", "Falkland Islands" ],
    [ "1512", "Spijkenisse", "Netherlands" ],
    [ "1906", "Split", "Croatia" ],
    [ "3200", "St. Anthony", "Newfoundland" ],
    [ "5948", "St. Bees Island", "Australia East Coast" ],
    [ "2568", "St. David'S Island", "Bermuda" ],
    [ "2439", "St. George'S Harbour", "Windward Islands" ],
    [ "3778", "St. Helena Bay", "South Africa" ],
    [ "3771", "St. Helena Island", "Mid South Atlantic Islands" ],
    [ "2456", "St. Johns, Antigua", "Leeward Islands" ],
    [ "3951", "St. Leu", "La Reunion" ],
    [ "4517", "St. Martin'S Island", "Bangladesh" ],
    [ "3952", "St. Pierre", "La Reunion" ],
    [ "3973", "St. Pierre Island", "Seychelles" ],
    [ "6087", "Stack Island", "Tasmania" ],
    [ "2299", "Stampa Island", "Guyana" ],
    [ "2068", "Stanley", "Falkland Islands" ],
    [ "2534", "Start Point", "Bahama Islands" ],
    [ "1529", "Stavenisse", "Netherlands" ],
    [ "6173", "Stenhouse Bay", "Australia South Coast" ],
    [ "1942", "Steno Knimidas", "Greece" ],
    [ "2545A", "Steventon", "Bahama Islands" ],
    [ "4606", "Stewart Sound", "Andaman Islands" ],
    [ "866A", "Stodvarfjordhur", "Iceland" ],
    [ "812", "Stokkseyri", "Iceland" ],
    [ "2021", "Stonington", "Antarctica" ],
    [ "4608", "Strait Island", "Andaman Islands" ],
    [ "3256", "Stupart Bay", "Labrador" ],
    [ "827", "Stykkisholmur", "Iceland" ],
    [ "3604", "Subbubo Point", "Liberia" ],
    [ "834", "Sudhureyri", "Iceland" ],
    [ "4190", "Suhar", "Oman" ],
    [ "5200", "Sukadana", "Kalimantan" ],
    [ "5731", "Sulva Bay", "Vanuatu" ],
    [ "4240", "Sumaysimah", "Qatar" ],
    [ "4497", "Sundar Kota Reach", "Bangladesh" ],
    [ "5207", "Sungai Arutobal", "Kalimantan" ],
    [ "5214", "Sungai Barito (Outer Bar)", "Kalimantan" ],
    [ "4734", "Sungai Belungkor", "Peninsular Malaysia South Coast" ],
    [ "4907", "Sungai Besut", "Peninsular Malaysia East Coast" ],
    [ "5168", "Sungai Ensengie", "Sarawak" ],
    [ "4658A", "Sungai Kedah", "Peninsular Malaysia West Coast" ],
    [ "4897", "Sungai Kemaman", "Peninsular Malaysia East Coast" ],
    [ "5233", "Sungai Kutei (Muara Bayur)", "Kalimantan" ],
    [ "4873", "Sungai Manggar", "Belitung" ],
    [ "4848", "Sungai Palembang (Outer Bar)", "Sumatera East Coast" ],
    [ "5190", "Sungai Paloh", "Kalimantan" ],
    [ "5225", "Sungai Pasir Outer Bar", "Kalimantan" ],
    [ "5201", "Sungai Pawan (Tanjung Bawang)", "Kalimantan" ],
    [ "5172", "Sungai Sarawak (Pulau Lakei)", "Sarawak" ],
    [ "5216", "Sungai Tabanio", "Kalimantan" ],
    [ "4845", "Sungai Tulangbawang", "Sumatera East Coast" ],
    [ "4849", "Sungsang", "Sumatera East Coast" ],
    [ "4182", "Sur", "Oman" ],
    [ "5365", "Surabaya (Tanjungperak)", "Jawa East Coast" ],
    [ "2279", "Suriname River Entrance", "Suriname" ],
    [ "6705", "Suva Harbour", "Fiji Islands" ],
    [ "4353", "Suvali", "India West Coast" ],
    [ "6605", "Suwarrow Island", "Cook Islands North" ],
    [ "830", "Sveinseyri", "Iceland" ],
    [ "3760", "Swakopmund", "Namibia" ],
    [ "2074C", "Swan Island", "Falkland Islands" ],
    [ "3573", "Taboria", "Guinea" ],
    [ "3608", "Tabu River", "Cote D'Ivoire" ],
    [ "5257", "Tahuna", "Kalimantan" ],
    [ "7097", "Tai O", "China" ],
    [ "7132", "Tai Po Kau", "China" ],
    [ "7176A", "T'Ai-Chung Kang", "T'Ai-Wan" ],
    [ "6711", "Tailevu", "Fiji Islands" ],
    [ "3621", "Takoradi", "Ghana" ],
    [ "5618", "Talasea", "Bismarck Archipelago" ],
    [ "5322", "Talisei", "Sulawesi East Coast" ],
    [ "3520", "Tamajarusch", "Morocco" ],
    [ "2228", "Tamandare", "Brazil" ],
    [ "2084", "Tamar Pass", "Falkland Islands" ],
    [ "2230", "Tambau", "Brazil" ],
    [ "5294", "Tampunawu", "Sulawesi West Coast" ],
    [ "5226", "Tanahgrogot", "Kalimantan" ],
    [ "4257A", "Tanajib Pier", "Saudi Arabia" ],
    [ "5056", "Tandag", "Philippine Islands" ],
    [ "4014", "Tanga Bay", "Tanzania" ],
    [ "4431A", "Tangalla", "Sri Lanka" ],
    [ "1809", "Tanger", "Morocco" ],
    [ "1809B", "Tanger Mediterranee", "Morocco" ],
    [ "5438", "Taniwel", "The Molucca Islands" ],
    [ "4871", "Tanjung Batubedil", "Belitung" ],
    [ "4876", "Tanjung Batuhitam", "Belitung" ],
    [ "5156A", "Tanjung Bekakong", "Sarawak" ],
    [ "5244", "Tanjung Birai", "Kalimantan" ],
    [ "4751", "Tanjung Butun", "Lingga Kepulauan" ],
    [ "5345", "Tanjung Cikoneng", "Jawa North Coast" ],
    [ "5211", "Tanjung Damaran", "Kalimantan" ],
    [ "5189", "Tanjung Datu", "Kalimantan" ],
    [ "4660", "Tanjung Dawai", "Peninsular Malaysia West Coast" ],
    [ "5234", "Tanjung Dewa", "Kalimantan" ],
    [ "5156C", "Tanjung Kamis", "Sarawak" ],
    [ "4857", "Tanjung Kelian", "Pulau Bangka" ],
    [ "4698", "Tanjung Keling", "Peninsular Malaysia West Coast" ],
    [ "5204", "Tanjung Kualajelai", "Kalimantan" ],
    [ "4705", "Tanjung Laboh", "Peninsular Malaysia West Coast" ],
    [ "5272", "Tanjung Lasonrae", "Sulawesi West Coast" ],
    [ "5349", "Tanjung Layar", "Jawa North Coast" ],
    [ "5368", "Tanjung Modung", "Madura" ],
    [ "5222", "Tanjung Pamukan", "Kalimantan" ],
    [ "5386", "Tanjung Pandanan", "Lombok" ],
    [ "4879", "Tanjung Penawar", "Peninsular Malaysia East Coast" ],
    [ "4735", "Tanjung Pengelih", "Peninsular Malaysia South Coast" ],
    [ "4765", "Tanjung Rambut", "Sumatera North East Coast" ],
    [ "5196", "Tanjung Saleh", "Kalimantan" ],
    [ "4881", "Tanjung Sedili Kechil", "Peninsular Malaysia East Coast" ],
    [ "5249", "Tanjung Selor", "Kalimantan" ],
    [ "5176", "Tanjung Serabang", "Sarawak" ],
    [ "4733", "Tanjung Serindet", "Peninsular Malaysia South Coast" ],
    [ "5155B", "Tanjung Sidau", "Sarawak" ],
    [ "4731", "Tanjung Surat", "Peninsular Malaysia South Coast" ],
    [ "4703A", "Tanjung Tohor", "Peninsular Malaysia West Coast" ],
    [ "5142", "Tanjung Ujong Sapoh", "Brunei" ],
    [ "4741", "Tanjungpinang", "Riau Kepulauan" ],
    [ "4794", "Tanjungtiram", "Sumatera North East Coast" ],
    [ "4740", "Tanjunguban", "Riau Kepulauan" ],
    [ "7093", "Tap Shek Kok", "China" ],
    [ "6320", "Tapa Bay", "Australia North Coast" ],
    [ "4814", "Tapaktuan", "Sumatera South West Coast" ],
    [ "1998", "Tarabulus (Tripoli)", "Libya" ],
    [ "4356A", "Tarapur", "India West Coast" ],
    [ "6758", "Tarawa (Bairiki)", "Kiribati" ],
    [ "6759", "Tarawa (Betio)", "Kiribati" ],
    [ "715", "Tarbert Island", "Ireland" ],
    [ "1768", "Tarifa", "Spain" ],
    [ "4569", "Tavoy", "Burma" ],
    [ "5099", "Tawau", "Sabah" ],
    [ "4770", "Tebing Tingi", "Sumatera North East Coast" ],
    [ "5334", "Tegal", "Jawa North Coast" ],
    [ "5442", "Teluk Bara", "The Molucca Islands" ],
    [ "4829", "Teluk Bayur (Emma Haven)", "Sumatera South West Coast" ],
    [ "5437", "Teluk Bula", "The Molucca Islands" ],
    [ "4856", "Teluk Bulu", "Pulau Bangka" ],
    [ "4824", "Teluk Dalam", "Sumatera South West Coast" ],
    [ "4656", "Teluk Datai", "Peninsular Malaysia West Coast" ],
    [ "5404", "Teluk Ende", "Flores" ],
    [ "4836", "Teluk Enggano", "Sumatera South West Coast" ],
    [ "4657", "Teluk Ewa", "Peninsular Malaysia West Coast" ],
    [ "5452", "Teluk Galela", "Halmahera" ],
    [ "5459", "Teluk Gane", "Halmahera" ],
    [ "4679", "Teluk Intan", "Peninsular Malaysia West Coast" ],
    [ "5524", "Teluk Iteba", "Irian Jaya" ],
    [ "5441", "Teluk Kayeli", "The Molucca Islands" ],
    [ "4855", "Teluk Klabat", "Pulau Bangka" ],
    [ "5221", "Teluk Klumpang", "Kalimantan" ],
    [ "5309", "Teluk Lamala", "Sulawesi East Coast" ],
    [ "4801", "Teluk Langsa", "Sumatera North East Coast" ],
    [ "5302", "Teluk Lasolo", "Sulawesi East Coast" ],
    [ "5238", "Teluk Lombok", "Kalimantan" ],
    [ "5380", "Teluk Padang", "Bali" ],
    [ "5271", "Teluk Parepare", "Sulawesi West Coast" ],
    [ "4872", "Teluk Pering", "Belitung" ],
    [ "5209", "Teluk Sampit", "Kalimantan" ],
    [ "5396", "Teluk Sape", "Sumbawa" ],
    [ "5400", "Teluk Sendikari", "Sumba" ],
    [ "4730", "Teluk Sengat", "Peninsular Malaysia South Coast" ],
    [ "4831", "Teluk Siberut", "Sumatera South West Coast" ],
    [ "4816", "Teluk Sinabang", "Sumatera South West Coast" ],
    [ "5399", "Teluk Slawi", "Sumbawa" ],
    [ "5424", "Teluk Solat", "Sermata Eilanden" ],
    [ "5185", "Teluk Tambelan", "Tudjuh Kepulauan" ],
    [ "4889", "Teluk Tekek", "Peninsular Malaysia East Coast" ],
    [ "5443", "Teluk Tifu", "The Molucca Islands" ],
    [ "5312", "Teluk Togian", "Sulawesi East Coast" ],
    [ "5264", "Teluk Tolitoli", "Sulawesi North Coast" ],
    [ "5326", "Teluk Vesuvius", "The Molucca Islands" ],
    [ "5297", "Teluk Wajo", "Sulawesi West Coast" ],
    [ "5397", "Teluk Waworada", "Sumbawa" ],
    [ "3627", "Tema", "Ghana" ],
    [ "4761", "Tembilahan", "Sumatera North East Coast" ],
    [ "4597", "Temple Sound", "Andaman Islands" ],
    [ "3547", "Tendaba", "The Gambia" ],
    [ "5425", "Tepa Road", "Sermata Eilanden" ],
    [ "5456", "Tepeleu", "Halmahera" ],
    [ "2249C", "Terminal Da Alumar", "Brazil" ],
    [ "2208", "Terminal Da Ponta Do Ubu", "Brazil" ],
    [ "1536", "Terneuzen", "Netherlands" ],
    [ "1080", "Tetrino", "Russia" ],
    [ "4361", "Thana", "India West Coast" ],
    [ "4545A", "Thandeik", "Burma" ],
    [ "4579", "Thar Myar Ami", "Burma" ],
    [ "4582", "Thatchaung", "Burma" ],
    [ "2549", "The Bight", "Bahama Islands" ],
    [ "4480", "The Sandheads", "India East Coast" ],
    [ "1946", "Thessaloniki", "Greece" ],
    [ "832", "Thingeyri", "Iceland" ],
    [ "813A", "Thorlakshofn", "Iceland" ],
    [ "853", "Thorshofn", "Iceland" ],
    [ "1414", "Thorsminde", "Denmark" ],
    [ "5678", "Thousand Ships Bay", "Solomon Islands" ],
    [ "6088", "Three Hummock Island", "Tasmania" ],
    [ "1413", "Thyboron", "Denmark" ],
    [ "4945", "Tibiao", "Philippine Islands" ],
    [ "5067", "Ticauan Point", "Philippine Islands" ],
    [ "5134", "Tiga", "Sabah" ],
    [ "4501", "Tiger Point", "Bangladesh" ],
    [ "3682", "Tiko", "Cameroon" ],
    [ "4545", "Tinmahlwe", "Burma" ],
    [ "4144", "Tiqfash", "Republic Of Yemen" ],
    [ "4122", "Tiran Island (Johnson Point)", "Saudi Arabia" ],
    [ "3587", "Titibul Creek", "Sierra Leone" ],
    [ "5352", "Tjilauteurem", "Jawa South Coast" ],
    [ "2442", "Tobago Cays", "Windward Islands" ],
    [ "5314", "Tobelombangi", "Sulawesi East Coast" ],
    [ "2333", "Toco", "Trinidad" ],
    [ "3752", "Tombua (Porto Alexandre)", "Angola" ],
    [ "6606", "Tongareva (Penrhyn Island)", "Cook Islands North" ],
    [ "792", "Torshavn", "Faeroe Islands" ],
    [ "2461", "Tortola", "Leeward Islands" ],
    [ "2181", "Tramandai", "Brazil" ],
    [ "663", "Trawbreaga Bay", "Ireland" ],
    [ "1987", "Tripoli", "Lebanon" ],
    [ "5164", "Triso Darat", "Sarawak" ],
    [ "2060", "Tristan Da Cunha", "Antarctica" ],
    [ "800", "Trongisvagur", "Faeroe Islands" ],
    [ "7141", "Tsang Chau", "China" ],
    [ "7092", "Tsim Bei Tsui", "China" ],
    [ "7094", "Tsing Shan Wan", "China" ],
    [ "7102", "Tsing Yi", "China" ],
    [ "7102A", "Tsuen Wan", "China" ],
    [ "4910", "Tumpat", "Peninsular Malaysia East Coast" ],
    [ "2247", "Tutoia", "Brazil" ],
    [ "1908C", "Ubli (Lastovo)", "Croatia" ],
    [ "5366", "Ujung Pangkah", "Jawa East Coast" ],
    [ "5273", "Ujungpandang (Makassar)", "Sulawesi West Coast" ],
    [ "5702", "Uki Ni Masi Island", "Solomon Islands" ],
    [ "5170A", "Ulu Kuap", "Sarawak" ],
    [ "4250C", "Umais", "Bahrain" ],
    [ "4210A", "Umm Ad Dalkh", "United Arab Emirates" ],
    [ "4231", "Umm Al Hatab", "United Arab Emirates" ],
    [ "4266A", "Umm Al-Aseed (Beacon No. 15)", "Kuwait" ],
    [ "4203", "Umm Al-Qaiwain", "United Arab Emirates" ],
    [ "4247D", "Umm Bab", "Qatar" ],
    [ "4250B", "Umm Jalid", "Bahrain" ],
    [ "4267", "Umm Qasr", "Iraq" ],
    [ "4123", "Umm Qusur", "Saudi Arabia" ],
    [ "3998", "Usimbe", "Tanzania" ],
    [ "3423A", "Uummannaq", "Greenland West Coast" ],
    [ "4455", "Vadarevu", "India East Coast" ],
    [ "801", "Vagur", "Faeroe Islands" ],
    [ "1775", "Valencia", "Spain" ],
    [ "1880", "Valletta", "Malta" ],
    [ "3556", "Varela", "Guinea-Bissau" ],
    [ "6708B", "Vatia Wharf", "Fiji Islands" ],
    [ "829", "Vatneyri", "Iceland" ],
    [ "4406", "Vattaru", "Maldive Islands" ],
    [ "838", "Veidileysufjordhur", "Iceland" ],
    [ "6726", "Veitalacagi Point", "Fiji Islands" ],
    [ "858", "Vestdalseyri", "Iceland" ],
    [ "793", "Vestmanna", "Faeroe Islands" ],
    [ "1730", "Viana Do Castelo", "Portugal" ],
    [ "3571B", "Victoria (Rio Nunez)", "Guinea" ],
    [ "3957", "Vieux Grand Port", "Mauritius Group" ],
    [ "2446A", "Vieuxfort Bay", "Windward Islands" ],
    [ "1724", "Vigo", "Spain" ],
    [ "875", "Vik", "Iceland" ],
    [ "2253A", "Vila Do Conde", "Brazil" ],
    [ "3469", "Vila Do Porto", "Azores" ],
    [ "1741B", "Vila Franca De Xira", "Portugal" ],
    [ "1753", "Vila Real De Santo Antonio", "Portugal" ],
    [ "1722", "Villagarcia (Ria De Arousa)", "Spain" ],
    [ "5649", "Viru Harbour", "Solomon Islands" ],
    [ "1906A", "Vis", "Croatia" ],
    [ "6721", "Visonggo", "Fiji Islands" ],
    [ "2211", "Vitoria", "Brazil" ],
    [ "1507", "Vlaardingen", "Netherlands" ],
    [ "1534", "Vlissingen (Flushing)", "Netherlands" ],
    [ "1943", "Volos", "Greece" ],
    [ "855", "Vopnafjordhur", "Iceland" ],
    [ "4559", "Wa Kyun (Stag Island)", "Burma" ],
    [ "7122", "Waglan Island", "China" ],
    [ "5444", "Wai Lower", "The Molucca Islands" ],
    [ "7086", "Wailingding Dao", "China" ],
    [ "5401", "Waingapu Road", "Sumba" ],
    [ "6730A", "Wainiyabia", "Fiji Islands" ],
    [ "6502", "Waipapa Point", "New Zealand South Island" ],
    [ "6790", "Wake Island", "Marshall Islands" ],
    [ "2296", "Wakenaam", "Guyana" ],
    [ "2564", "Walker Cay", "Bahama Islands" ],
    [ "2067A", "Walker Creek", "Falkland Islands" ],
    [ "3761", "Walvis Bay", "Namibia" ],
    [ "654", "Warren Lighthouse", "Ireland" ],
    [ "3648", "Warri", "Nigeria" ],
    [ "4015", "Wasini Island", "Kenya" ],
    [ "762", "Waterford", "Ireland" ],
    [ "2045A", "Weddell Sea", "Antarctica" ],
    [ "1520", "Werkendam", "Netherlands" ],
    [ "727", "West Cove", "Ireland" ],
    [ "1483", "West Terschelling", "Netherlands" ],
    [ "1533A", "Westkapelle", "Netherlands" ],
    [ "5138", "Weston", "Sabah" ],
    [ "2082", "Westpoint Island", "Falkland Islands" ],
    [ "768", "Wexford Harbour", "Ireland" ],
    [ "2044A", "Whiskey Bay", "Antarctica" ],
    [ "613", "Wicklow", "Ireland" ],
    [ "2546", "Wide Opening", "Bahama Islands" ],
    [ "2032", "Wiencke Island (Port Lockroy)", "Antarctica" ],
    [ "2370", "Willemstad", "Nederlandse Antillen" ],
    [ "2450", "Woodbridge Bay", "Leeward Islands" ],
    [ "7163", "Xiamen Gang", "China" ],
    [ "4062", "Xiis", "Somalia" ],
    [ "6718", "Yadua Island", "Fiji Islands" ],
    [ "4131", "Yanbu Al Bahr", "Saudi Arabia" ],
    [ "5657", "Yandina", "Solomon Islands" ],
    [ "4548", "Yangon (Rangoon)", "Burma" ],
    [ "7249", "Yangxiaomao Dao", "China" ],
    [ "6815", "Yap Island", "Caroline Islands" ],
    [ "4561", "Ye Town", "Burma" ],
    [ "3578", "Yelibuya Sound", "Guinea" ],
    [ "755", "Youghal", "Ireland" ],
    [ "3640", "Youngtown", "Nigeria" ],
    [ "7106", "Yung Shue Wan", "China" ],
    [ "7262", "Yuxingnao Dao", "China" ],
    [ "4590", "Za Det Gyi Island (South Bay)", "Burma" ],
    [ "3449", "Zackenberg", "Greenland East Coast" ],
    [ "1902", "Zadar", "Croatia" ],
    [ "1901", "Zaliv Pantera", "Croatia" ],
    [ "5068", "Zamboanga", "Philippine Islands" ],
    [ "4006", "Zanzibar", "Tanzania" ],
    [ "4215", "Zaqqum Oilfield (Platform Zws)", "United Arab Emirates" ],
    [ "1562", "Zeebrugge", "Belgium" ],
    [ "7159", "Zhao'An Wan", "China" ],
    [ "4247B", "Zikrit", "Qatar" ],
    [ "1040", "Zimnyaya Zolotitsa", "Russia" ],
    [ "4219", "Zirku", "United Arab Emirates" ],
    [ "4220", "Zirku Terminal", "United Arab Emirates" ],
    [ "4027", "Ziwa La Juu", "Kenya" ] ]


# Reproduced under the Open Government Licence.
# www.nationalarchives.gov.uk/doc/open-government-licence
#
# Port ID. port name, country.
_UKHO_UKPorts = [
    [ "482A", "Aberdaron", "Wales" ],
    [ "244", "Aberdeen", "Scotland" ],
    [ "486", "Aberdovey", "Wales" ],
    [ "488A", "Aberporth", "Wales" ],
    [ "487", "Aberystwyth", "Wales" ],
    [ "114", "Albert Bridge", "England" ],
    [ "139", "Aldeburgh", "England" ],
    [ "109E", "Allington Lock", "England" ],
    [ "229A", "Alloa", "Scotland" ],
    [ "206", "Amble", "England" ],
    [ "477", "Amlwch", "Wales" ],
    [ "426", "Annan Waterfoot", "Scotland" ],
    [ "233", "Anstruther Easter", "Scotland" ],
    [ "338A", "Applecross", "Scotland" ],
    [ "536", "Appledore", "England" ],
    [ "241", "Arbroath", "Scotland" ],
    [ "371B", "Ardchattan Point", "Scotland" ],
    [ "631", "Ardglass", "Northern Ireland" ],
    [ "378", "Ardnave Point", "Scotland" ],
    [ "410", "Ardrossan", "Scotland" ],
    [ "440A", "Arnside", "England" ],
    [ "401", "Arrochar", "Scotland" ],
    [ "74B", "Arundel", "England" ],
    [ "413", "Ayr", "Scotland" ],
    [ "329", "Badcall Bay", "Scotland" ],
    [ "318", "Balivanich", "Scotland" ],
    [ "651", "Ballycastle Bay", "Northern Ireland" ],
    [ "290B", "Baltasound Pier", "Scotland" ],
    [ "247", "Banff", "Scotland" ],
    [ "637A", "Bangor", "Northern Ireland" ],
    [ "370A", "Barcaldine Pier", "Scotland" ],
    [ "482", "Bardsey Island", "Wales" ],
    [ "485", "Barmouth", "Wales" ],
    [ "539", "Barnstaple", "England" ],
    [ "314", "Barra (North Bay)", "Scotland" ],
    [ "316", "Barra Head", "Scotland" ],
    [ "439", "Barrow (Ramsden Dock)", "England" ],
    [ "513", "Barry", "Wales" ],
    [ "108B", "Bartlett Creek", "England" ],
    [ "122C", "Battlesbridge", "England" ],
    [ "135", "Bawdsey", "England" ],
    [ "354", "Bay Of Laig", "Scotland" ],
    [ "296", "Bay Of Quendale", "Scotland" ],
    [ "310B", "Bays Loch", "Scotland" ],
    [ "518", "Beachley (Aust)", "England" ],
    [ "472", "Beaumaris", "Wales" ],
    [ "108A", "Bee Ness", "England" ],
    [ "638", "Belfast", "Northern Ireland" ],
    [ "53B", "Bembridge Approaches", "England" ],
    [ "54", "Bembridge Harbour", "England" ],
    [ "522", "Berkeley", "England" ],
    [ "209", "Berwick", "England" ],
    [ "540", "Bideford", "England" ],
    [ "498", "Black Tar", "Wales" ],
    [ "445", "Blackpool", "England" ],
    [ "179", "Blacktoft", "England" ],
    [ "155A", "Blakeney", "England" ],
    [ "155", "Blakeney Bar", "England" ],
    [ "292", "Bluemull Sound", "Scotland" ],
    [ "204", "Blyth", "England" ],
    [ "73", "Bognor Regis", "England" ],
    [ "371C", "Bonawe", "Scotland" ],
    [ "544", "Boscastle", "England" ],
    [ "68B", "Bosham", "England" ],
    [ "166", "Boston, England", "England" ],
    [ "1606A", "Bouley Bay", "Channel Islands" ],
    [ "37", "Bournemouth", "England" ],
    [ "15A", "Bovisand Pier", "England" ],
    [ "406", "Bowling", "Scotland" ],
    [ "123", "Bradwell Waterside", "England" ],
    [ "129A", "Bramble Creek", "England" ],
    [ "1603", "Braye", "Channel Islands" ],
    [ "529", "Bridgwater", "England" ],
    [ "181", "Bridlington", "England" ],
    [ "29", "Bridport (West Bay)", "England" ],
    [ "126", "Brightlingsea", "England" ],
    [ "82", "Brighton Marina", "England" ],
    [ "341", "Broadford Bay", "Scotland" ],
    [ "102A", "Broadstairs", "England" ],
    [ "408", "Brodick Bay", "Scotland" ],
    [ "176A", "Brough", "England" ],
    [ "380", "Bruichladdich", "Scotland" ],
    [ "248", "Buckie", "Scotland" ],
    [ "42", "Bucklers Hard", "England" ],
    [ "543", "Bude", "England" ],
    [ "171A", "Bull Sand Fort", "England" ],
    [ "361", "Bunessan", "Scotland" ],
    [ "282A", "Bur Wick", "Scotland" ],
    [ "250", "Burghead", "Scotland" ],
    [ "158", "Burnham (Overy Staithe)", "England" ],
    [ "122", "Burnham-On-Crouch", "England" ],
    [ "528", "Burnham-On-Sea", "England" ],
    [ "230", "Burntisland", "Scotland" ],
    [ "291", "Burra Firth", "Scotland" ],
    [ "290", "Burra Voe (Yell Sound)", "Scotland" ],
    [ "271", "Burray Ness", "Scotland" ],
    [ "505", "Burry Port", "Wales" ],
    [ "63B", "Bursledon", "England" ],
    [ "177", "Burton Stather", "England" ],
    [ "475", "Caernarfon", "Wales" ],
    [ "143", "Caister-On-Sea", "England" ],
    [ "469", "Calf Sound", "Isle Of Man" ],
    [ "61", "Calshot Castle", "England" ],
    [ "393", "Campbeltown", "Scotland" ],
    [ "346", "Camus Nan Gall", "Scotland" ],
    [ "547A", "Cape Cornwall, England", "England" ],
    [ "514", "Cardiff", "Wales" ],
    [ "489A", "Cardigan (Town)", "Wales" ],
    [ "14B", "Cargreen", "England" ],
    [ "321A", "Carloway", "Scotland" ],
    [ "504A", "Carmarthen", "Wales" ],
    [ "393A", "Carradale", "Scotland" ],
    [ "639", "Carrickfergus", "Northern Ireland" ],
    [ "387", "Carsaig Bay", "Scotland" ],
    [ "359", "Carsaig Bay (Mull)", "Scotland" ],
    [ "314A", "Castlebay", "Scotland" ],
    [ "477A", "Cemaes Bay", "Wales" ],
    [ "109", "Chatham (Lock Approaches)", "England" ],
    [ "113A", "Chelsea Bridge", "England" ],
    [ "516", "Chepstow", "Wales" ],
    [ "30", "Chesil Beach", "England" ],
    [ "31", "Chesil Cove", "England" ],
    [ "462", "Chester", "England" ],
    [ "68", "Chichester Harbour (Entrance)", "England" ],
    [ "38", "Christchurch (Entrance)", "England" ],
    [ "38A", "Christchurch (Quay)", "England" ],
    [ "38B", "Christchurch (Tuckton)", "England" ],
    [ "128", "Clacton-On-Sea", "England" ],
    [ "36D", "Cleavel Point", "England" ],
    [ "525", "Clevedon", "England" ],
    [ "541", "Clovelly", "England" ],
    [ "406A", "Clydebank (Rothesay Dock)", "Scotland" ],
    [ "224", "Cockenzie", "Scotland" ],
    [ "127", "Colchester", "England" ],
    [ "653", "Coleraine", "Northern Ireland" ],
    [ "470", "Colwyn Bay", "Wales" ],
    [ "463", "Connah'S Quay", "England" ],
    [ "371A", "Connel", "Scotland" ],
    [ "471A", "Conwy", "Wales" ],
    [ "205", "Coquet Island", "England" ],
    [ "368", "Corpach", "Scotland" ],
    [ "367", "Corran", "Scotland" ],
    [ "110A", "Coryton", "England" ],
    [ "14C", "Cotehele Quay", "England" ],
    [ "399B", "Coulport", "Scotland" ],
    [ "4", "Coverack", "England" ],
    [ "60", "Cowes", "England" ],
    [ "383", "Craighouse", "Scotland" ],
    [ "365A", "Craignure", "Scotland" ],
    [ "627", "Cranfield Point", "Northern Ireland" ],
    [ "483A", "Criccieth", "Wales" ],
    [ "258", "Cromarty", "Scotland" ],
    [ "154", "Cromer", "England" ],
    [ "657", "Culmore Point", "Northern Ireland" ],
    [ "524", "Cumberland Basin Entrance", "England" ],
    [ "644", "Cushendun", "Northern Ireland" ],
    [ "495", "Dale Roads", "Wales" ],
    [ "108C", "Darnett Ness", "England" ],
    [ "23", "Dartmouth", "England" ],
    [ "98", "Deal", "England" ],
    [ "272", "Deer Sound", "Scotland" ],
    [ "68D", "Dell Quay", "England" ],
    [ "260", "Dingwall, Cromarty Firth", "Scotland" ],
    [ "637", "Donaghadee", "Northern Ireland" ],
    [ "349A", "Dornie Bridge", "Scotland" ],
    [ "468", "Douglas", "Isle Of Man" ],
    [ "89", "Dover", "England" ],
    [ "419", "Drummore", "Scotland" ],
    [ "437", "Duddon Bar", "England" ],
    [ "222", "Dunbar", "Scotland" ],
    [ "268", "Duncansby Head", "Scotland" ],
    [ "236", "Dundee", "Scotland" ],
    [ "87", "Dungeness", "England" ],
    [ "371", "Dunstaffnage Bay", "Scotland" ],
    [ "288", "Dury Voe", "Scotland" ],
    [ "310", "E. Loch Tarbert", "Scotland" ],
    [ "394", "East Loch Tarbert", "Scotland" ],
    [ "84", "Eastbourne", "England" ],
    [ "453", "Eastham", "England" ],
    [ "273A", "Egilsay", "Scotland" ],
    [ "526", "English And Welsh Grounds", "England" ],
    [ "522C", "Epney", "England" ],
    [ "111B", "Erith", "England" ],
    [ "293A", "Esha Ness (Hamna Voe)", "Scotland" ],
    [ "26B", "Exmouth (Approaches)", "England" ],
    [ "27", "Exmouth Dock", "England" ],
    [ "221", "Eyemouth", "Scotland" ],
    [ "285", "Fair Isle", "Scotland" ],
    [ "5", "Falmouth", "England" ],
    [ "402B", "Faslane", "Scotland" ],
    [ "107", "Faversham", "England" ],
    [ "133A", "Felixstowe Pier", "England" ],
    [ "504", "Ferryside", "Wales" ],
    [ "456A", "Fiddler'S Ferry", "England" ],
    [ "223", "Fidra", "Scotland" ],
    [ "182", "Filey Bay", "England" ],
    [ "490", "Fishguard", "Wales" ],
    [ "323", "Flannan Isles", "Scotland" ],
    [ "513A", "Flat Holm", "Wales" ],
    [ "444", "Fleetwood", "England" ],
    [ "177A", "Flixborough Wharf", "England" ],
    [ "88", "Folkestone", "England" ],
    [ "60A", "Folly Inn", "England" ],
    [ "53A", "Foreland (Lifeboat Slip)", "England" ],
    [ "448", "Formby", "England" ],
    [ "475A", "Fort Belan", "Wales" ],
    [ "255", "Fortrose", "Scotland" ],
    [ "296A", "Foula", "Scotland" ],
    [ "8", "Fowey", "England" ],
    [ "246", "Fraserburgh", "Scotland" ],
    [ "538", "Fremington", "England" ],
    [ "48", "Freshwater Bay", "England" ],
    [ "337", "Gairloch", "Scotland" ],
    [ "354A", "Galmisdale Pier (Eigg)", "Scotland" ],
    [ "402C", "Garelochhead", "Scotland" ],
    [ "422", "Garlieston", "Scotland" ],
    [ "452A", "Garston", "England" ],
    [ "297A", "Gills Bay", "Scotland" ],
    [ "414", "Girvan", "Scotland" ],
    [ "407", "Glasgow", "Scotland" ],
    [ "442", "Glasson Dock", "England" ],
    [ "351", "Glenelg Bay", "Scotland" ],
    [ "375", "Glengarrisdale Bay", "Scotland" ],
    [ "264", "Golspie", "Scotland" ],
    [ "180", "Goole", "England" ],
    [ "142", "Gorleston-On-Sea", "England" ],
    [ "357", "Gott Bay", "Scotland" ],
    [ "228", "Grangemouth", "Scotland" ],
    [ "226", "Granton", "Scotland" ],
    [ "111A", "Gravesend", "England" ],
    [ "142A", "Great Yarmouth (Britannia Pier)", "England" ],
    [ "404", "Greenock", "Scotland" ],
    [ "23A", "Greenway Quay", "England" ],
    [ "172", "Grimsby", "England" ],
    [ "106", "Grovehurst Jetty", "England" ],
    [ "455", "Hale Head", "England" ],
    [ "439C", "Halfway Shoal", "England" ],
    [ "115", "Hammersmith Bridge", "England" ],
    [ "188", "Hartlepool", "England" ],
    [ "131", "Harwich", "England" ],
    [ "85", "Hastings", "England" ],
    [ "499", "Haverfordwest", "Wales" ],
    [ "439B", "Haws Point", "England" ],
    [ "403", "Helensburgh", "Scotland" ],
    [ "4A", "Helford River (Entrance)", "England" ],
    [ "265", "Helmsdale", "Scotland" ],
    [ "104", "Herne Bay", "England" ],
    [ "424", "Hestan Island", "Scotland" ],
    [ "441", "Heysham", "England" ],
    [ "461", "Hilbre Island", "England" ],
    [ "294", "Hillswick", "Scotland" ],
    [ "530", "Hinkley Point", "England" ],
    [ "322", "Hirta (Bagh A' Bhaile)", "Scotland" ],
    [ "121A", "Holliwell Point", "England" ],
    [ "208", "Holy Island", "England" ],
    [ "478", "Holyhead", "Wales" ],
    [ "175", "Hull (Albert Dock)", "England" ],
    [ "174A", "Hull (Alexandra Dock)", "England" ],
    [ "174", "Hull (King George Dock)", "England" ],
    [ "122B", "Hullbridge", "England" ],
    [ "176", "Humber Bridge", "England" ],
    [ "172A", "Humber Sea Terminal", "England" ],
    [ "161", "Hunstanton", "England" ],
    [ "39", "Hurst Point", "England" ],
    [ "136C", "Iken Cliffs", "England" ],
    [ "535", "Ilfracombe", "England" ],
    [ "173", "Immingham", "England" ],
    [ "168", "Inner Dowsing Light", "England" ],
    [ "395", "Inveraray", "Scotland" ],
    [ "259", "Invergordon", "Scotland" ],
    [ "353", "Inverie Bay", "Scotland" ],
    [ "256", "Inverness", "Scotland" ],
    [ "519", "Inward Rocks", "England" ],
    [ "360", "Iona", "Scotland" ],
    [ "133", "Ipswich", "England" ],
    [ "411", "Irvine", "Scotland" ],
    [ "421", "Isle Of Whithorn", "Scotland" ],
    [ "68C", "Itchenor", "England" ],
    [ "14E", "Jupiter Point", "England" ],
    [ "178", "Keadby", "England" ],
    [ "275", "Kettletoft Pier", "Scotland" ],
    [ "115A", "Kew Bridge", "England" ],
    [ "629", "Kilkeel", "Northern Ireland" ],
    [ "632", "Killard Point", "Northern Ireland" ],
    [ "630A", "Killough Harbour", "Northern Ireland" ],
    [ "634", "Killyleagh", "Northern Ireland" ],
    [ "229", "Kincardine", "Scotland" ],
    [ "162", "King'S Lynn", "England" ],
    [ "327", "Kinlochbervie", "Scotland" ],
    [ "231", "Kirkcaldy", "Scotland" ],
    [ "422A", "Kirkcudbright Bay", "Scotland" ],
    [ "273", "Kirkwall", "Scotland" ],
    [ "301", "Kyle Of Durness", "Scotland" ],
    [ "349", "Kyle Of Lochalsh", "Scotland" ],
    [ "409", "Lamlash", "Scotland" ],
    [ "442A", "Lancaster", "England" ],
    [ "66", "Langstone Harbour", "England" ],
    [ "641", "Larne", "Northern Ireland" ],
    [ "164B", "Lawyer'S Creek", "England" ],
    [ "64", "Lee-On-The-Solent", "England" ],
    [ "225", "Leith", "Scotland" ],
    [ "287", "Lerwick", "Scotland" ],
    [ "310A", "Leverburgh", "Scotland" ],
    [ "321", "Little Bernera", "Scotland" ],
    [ "492B", "Little Haven", "Wales" ],
    [ "74", "Littlehampton (Entrance)", "England" ],
    [ "451", "Liverpool (Gladstone Dock)", "England" ],
    [ "3", "Lizard Point", "England" ],
    [ "480", "Llanddwyn Island", "Wales" ],
    [ "471", "Llandudno", "Wales" ],
    [ "505A", "Llanelli", "Wales" ],
    [ "522E", "Llanthony", "England" ],
    [ "340", "Loch A' Bhraige", "Scotland" ],
    [ "365", "Loch Aline", "Scotland" ],
    [ "384", "Loch Beag", "Scotland" ],
    [ "313", "Loch Boisdale", "Scotland" ],
    [ "311A", "Loch Carnan", "Scotland" ],
    [ "370B", "Loch Creran Head", "Scotland" ],
    [ "344", "Loch Dunvegan", "Scotland" ],
    [ "356", "Loch Eatharna", "Scotland" ],
    [ "368A", "Loch Eil Head", "Scotland" ],
    [ "345", "Loch Harport", "Scotland" ],
    [ "352", "Loch Hourn", "Scotland" ],
    [ "332", "Loch Inver", "Scotland" ],
    [ "328", "Loch Laxford", "Scotland" ],
    [ "369", "Loch Leven Head", "Scotland" ],
    [ "383A", "Loch Melfort", "Scotland" ],
    [ "355", "Loch Moidart", "Scotland" ],
    [ "330", "Loch Nedd", "Scotland" ],
    [ "393B", "Loch Ranza", "Scotland" ],
    [ "353B", "Loch Scresort (Rhum)", "Scotland" ],
    [ "309", "Loch Shell", "Scotland" ],
    [ "312", "Loch Skipport", "Scotland" ],
    [ "343", "Loch Snizort (Uig Bay)", "Scotland" ],
    [ "399C", "Lochgoilhead", "Scotland" ],
    [ "311", "Lochmaddy", "Scotland" ],
    [ "113", "London Bridge (Tower Pier)", "England" ],
    [ "659", "Londonderry", "Northern Ireland" ],
    [ "11", "Looe", "England" ],
    [ "14D", "Lopwell", "England" ],
    [ "249", "Lossiemouth", "Scotland" ],
    [ "8A", "Lostwithiel", "England" ],
    [ "274", "Loth", "Scotland" ],
    [ "141", "Lowestoft", "England" ],
    [ "420", "Luce Bay (Offshore Platform)", "Scotland" ],
    [ "34", "Lulworth Cove", "England" ],
    [ "542", "Lundy", "England" ],
    [ "28", "Lyme Regis", "England" ],
    [ "40", "Lymington", "England" ],
    [ "534", "Lynmouth", "England" ],
    [ "390", "Machrihanish", "Scotland" ],
    [ "123B", "Maldon", "England" ],
    [ "353A", "Mallaig", "Scotland" ],
    [ "103", "Margate", "England" ],
    [ "493", "Martin'S Haven", "Wales" ],
    [ "433", "Maryport", "England" ],
    [ "1603A", "Maseline Pier", "Channel Islands" ],
    [ "254", "Mcdermott Base", "Scotland" ],
    [ "262", "Meikle Ferry", "Scotland" ],
    [ "336", "Mellon Charles", "Scotland" ],
    [ "473", "Menai Bridge", "Wales" ],
    [ "232", "Methil", "Scotland" ],
    [ "7", "Mevagissey", "England" ],
    [ "290A", "Mid Yell", "Scotland" ],
    [ "186", "Middlesbrough (Dock Entrance)", "England" ],
    [ "496", "Milford Haven", "Wales" ],
    [ "398", "Millport", "Scotland" ],
    [ "532", "Minehead", "England" ],
    [ "139A", "Minsmere Sluice", "England" ],
    [ "522D", "Minsterworth", "England" ],
    [ "132", "Mistley", "England" ],
    [ "476A", "Moelfre", "Wales" ],
    [ "242", "Montrose", "Scotland" ],
    [ "440B", "Morecambe", "England" ],
    [ "464", "Mostyn Docks", "England" ],
    [ "270", "Muckle Skerry", "Scotland" ],
    [ "508", "Mumbles", "Wales" ],
    [ "34A", "Mupe Bay", "England" ],
    [ "70", "Nab Tower", "England" ],
    [ "253", "Nairn", "Scotland" ],
    [ "520", "Narlwood Rocks", "England" ],
    [ "336A", "Nato Jetty", "Scotland" ],
    [ "109D", "New Hythe", "England" ],
    [ "488", "New Quay", "Wales" ],
    [ "236A", "Newburgh", "Scotland" ],
    [ "630", "Newcastle (N. Ireland)", "Northern Ireland" ],
    [ "203", "Newcastle-Upon-Tyne", "England" ],
    [ "83", "Newhaven", "England" ],
    [ "515", "Newport", "Wales" ],
    [ "60B", "Newport (Isle Of Wight)", "England" ],
    [ "546", "Newquay", "England" ],
    [ "628A", "Newry (Victoria Lock)", "Northern Ireland" ],
    [ "497", "Neyland", "Wales" ],
    [ "122A", "North Fambridge", "England" ],
    [ "207", "North Sunderland (Northumberland)", "England" ],
    [ "112", "North Woolwich", "England" ],
    [ "68A", "Northney", "England" ],
    [ "372", "Oban", "Scotland" ],
    [ "136", "Orford Haven Bar", "England" ],
    [ "137", "Orford Ness", "England" ],
    [ "136A", "Orford Quay", "England" ],
    [ "379", "Orsay", "Scotland" ],
    [ "123A", "Osea Island", "England" ],
    [ "289", "Out Skerries", "Scotland" ],
    [ "163", "Outer Westmark Knock", "England" ],
    [ "178A", "Owston Ferry", "England" ],
    [ "545", "Padstow", "England" ],
    [ "72", "Pagham", "England" ],
    [ "7A", "Par", "England" ],
    [ "466", "Peel", "Isle Of Man" ],
    [ "2", "Penzance (Newlyn)", "England" ],
    [ "546A", "Perranporth", "England" ],
    [ "236B", "Perth", "Scotland" ],
    [ "245", "Peterhead", "Scotland" ],
    [ "277", "Pierowall", "Scotland" ],
    [ "339", "Plockton", "Scotland" ],
    [ "14", "Plymouth (Devonport)", "England" ],
    [ "36", "Poole (Entrance)", "England" ],
    [ "36A", "Poole Harbour", "England" ],
    [ "533", "Porlock Bay", "England" ],
    [ "370", "Port Appin", "Scotland" ],
    [ "382", "Port Askaig", "Scotland" ],
    [ "489", "Port Cardigan", "Wales" ],
    [ "474", "Port Dinorwic", "Wales" ],
    [ "381", "Port Ellen", "Scotland" ],
    [ "469A", "Port Erin", "Isle Of Man" ],
    [ "405", "Port Glasgow", "Scotland" ],
    [ "544A", "Port Isaac", "England" ],
    [ "523", "Port Of Bristol (Avonmouth)", "England" ],
    [ "468A", "Port St. Mary", "Isle Of Man" ],
    [ "164", "Port Sutton Bridge", "England" ],
    [ "510", "Port Talbot", "Wales" ],
    [ "420A", "Port William", "Scotland" ],
    [ "636", "Portavogie", "Northern Ireland" ],
    [ "481", "Porth Dinllaen", "Wales" ],
    [ "479A", "Porth Trecastell", "Wales" ],
    [ "481A", "Porth Ysgaden", "Wales" ],
    [ "512", "Porthcawl", "Wales" ],
    [ "491", "Porthgain", "Wales" ],
    [ "2A", "Porthleven", "England" ],
    [ "484", "Porthmadog", "Wales" ],
    [ "524A", "Portishead", "England" ],
    [ "33", "Portland", "England" ],
    [ "261", "Portmahomack", "Scotland" ],
    [ "300", "Portnancon", "Scotland" ],
    [ "415", "Portpatrick", "Scotland" ],
    [ "342", "Portree", "Scotland" ],
    [ "652", "Portrush", "Northern Ireland" ],
    [ "65", "Portsmouth", "England" ],
    [ "36B", "Pottery Pier", "England" ],
    [ "446", "Preston", "England" ],
    [ "483", "Pwllheli", "Wales" ],
    [ "633A", "Quoile Barrier", "Northern Ireland" ],
    [ "467", "Ramsey", "Isle Of Man" ],
    [ "492", "Ramsey Sound", "Wales" ],
    [ "102", "Ramsgate", "England" ],
    [ "276", "Rapness", "Scotland" ],
    [ "643", "Red Bay, Northern Ireland", "Northern Ireland" ],
    [ "63", "Redbridge", "England" ],
    [ "431", "Redkirk", "Scotland" ],
    [ "402A", "Rhu Marina", "Scotland" ],
    [ "99", "Richborough", "England" ],
    [ "116", "Richmond Lock", "England" ],
    [ "658", "River Foyle (Lisahally)", "Northern Ireland" ],
    [ "509A", "River Neath Entrance", "Wales" ],
    [ "235", "River Tay Bar", "Scotland" ],
    [ "185", "River Tees Entrance", "England" ],
    [ "202", "River Tyne (North Shields)", "England" ],
    [ "17", "River Yealm Entrance", "England" ],
    [ "439A", "Roa Island", "England" ],
    [ "109B", "Rochester (Strood Pier)", "England" ],
    [ "121B", "Rochford", "England" ],
    [ "324", "Rockall", "Scotland" ],
    [ "304", "Rona", "Scotland" ],
    [ "402", "Rosneath", "Scotland" ],
    [ "227", "Rosyth", "Scotland" ],
    [ "399", "Rothesay Bay", "Scotland" ],
    [ "377", "Rubh' A' Mhail", "Scotland" ],
    [ "396", "Rubha A' Bhodaich", "Scotland" ],
    [ "371D", "Rubha Na Ceige", "Scotland" ],
    [ "58", "Ryde", "England" ],
    [ "86", "Rye (Approaches)", "England" ],
    [ "86A", "Rye (Harbour)", "England" ],
    [ "117", "S.E. Long Sand", "England" ],
    [ "20", "Salcombe", "England" ],
    [ "363", "Salen", "Scotland" ],
    [ "364A", "Salen, Sound Of Mull", "Scotland" ],
    [ "14A", "Saltash", "England" ],
    [ "53", "Sandown", "England" ],
    [ "374", "Scalasaig", "Scotland" ],
    [ "295", "Scalloway", "Scotland" ],
    [ "183", "Scarborough", "England" ],
    [ "318A", "Scolpaig", "Scotland" ],
    [ "298", "Scrabster", "Scotland" ],
    [ "523B", "Sea Mills", "England" ],
    [ "452", "Seacombe (Alfred Dock)", "England" ],
    [ "189", "Seaham", "England" ],
    [ "373", "Seil Sound", "Scotland" ],
    [ "69", "Selsey Bill", "England" ],
    [ "548", "Sennen Cove", "England" ],
    [ "522A", "Sharpness Dock", "England" ],
    [ "108", "Sheerness", "England" ],
    [ "338", "Shieldaig", "Scotland" ],
    [ "317", "Shillay", "Scotland" ],
    [ "523A", "Shirehampton", "England" ],
    [ "116A", "Shivering Sand", "England" ],
    [ "81", "Shoreham", "England" ],
    [ "432", "Silloth", "England" ],
    [ "167", "Skegness", "England" ],
    [ "494", "Skomer Island", "Wales" ],
    [ "136B", "Slaughden Quay", "England" ],
    [ "492A", "Solva", "Wales" ],
    [ "389", "Sound Of Gigha", "Scotland" ],
    [ "362", "Sound Of Ulva", "Scotland" ],
    [ "635", "South Rock", "Northern Ireland" ],
    [ "62", "Southampton", "England" ],
    [ "391", "Southend, Kintyre", "Scotland" ],
    [ "110", "Southend-On-Sea", "England" ],
    [ "425", "Southerness Point", "Scotland" ],
    [ "447", "Southport", "England" ],
    [ "140", "Southwold", "England" ],
    [ "171", "Spurn Head", "England" ],
    [ "1606", "St. Catherine Bay", "Channel Islands" ],
    [ "14F", "St. Germans", "England" ],
    [ "1605", "St. Helier", "Channel Islands" ],
    [ "547", "St. Ives", "England" ],
    [ "1", "St. Mary'S", "England" ],
    [ "281", "St. Mary'S (Scapa Flow)", "Scotland" ],
    [ "1604", "St. Peter Port", "Channel Islands" ],
    [ "525A", "St. Thomas'S Head", "England" ],
    [ "482B", "St. Tudwal'S Roads", "Wales" ],
    [ "501", "Stackpole Quay", "Wales" ],
    [ "43", "Stansore Point", "England" ],
    [ "27A", "Starcross", "England" ],
    [ "21", "Start Point", "England" ],
    [ "513B", "Steep Holm", "Wales" ],
    [ "229B", "Stirling", "Scotland" ],
    [ "23B", "Stoke Gabriel (Duncannon)", "England" ],
    [ "243", "Stonehaven", "Scotland" ],
    [ "308", "Stornoway", "Scotland" ],
    [ "633", "Strangford", "Northern Ireland" ],
    [ "414A", "Stranraer", "Scotland" ],
    [ "297", "Stroma", "Scotland" ],
    [ "280", "Stromness", "Scotland" ],
    [ "517", "Sudbrook", "England" ],
    [ "299", "Sule Skerry", "Scotland" ],
    [ "293", "Sullom Voe", "Scotland" ],
    [ "285A", "Sumburgh (Grutness Voe)", "Scotland" ],
    [ "190", "Sunderland", "England" ],
    [ "171B", "Sunk Dredged Channel", "England" ],
    [ "130", "Sunk Head", "England" ],
    [ "35", "Swanage", "England" ],
    [ "509", "Swansea", "Wales" ],
    [ "165", "Tabs Head", "England" ],
    [ "333", "Tanera Mor", "Scotland" ],
    [ "436", "Tarn Point", "England" ],
    [ "187", "Tees (Newport) Bridge", "England" ],
    [ "26", "Teignmouth (Approaches)", "England" ],
    [ "26A", "Teignmouth (New Quay)", "England" ],
    [ "502", "Tenby", "Wales" ],
    [ "396A", "Tighnabruaich", "Scotland" ],
    [ "111", "Tilbury", "England" ],
    [ "279", "Tingwall", "Scotland" ],
    [ "364", "Tobermory", "Scotland" ],
    [ "289A", "Toft Pier", "Scotland" ],
    [ "27C", "Topsham", "England" ],
    [ "430", "Torduff Point", "Scotland" ],
    [ "25", "Torquay", "England" ],
    [ "46", "Totland Bay", "England" ],
    [ "23C", "Totnes", "England" ],
    [ "479", "Trearddur Bay", "Wales" ],
    [ "480A", "Trefor", "Wales" ],
    [ "412", "Troon", "Scotland" ],
    [ "5A", "Truro", "England" ],
    [ "476", "Trwyn Dinmor", "Wales" ],
    [ "27B", "Turf Lock", "England" ],
    [ "15", "Turnchapel", "England" ],
    [ "334", "Ullapool", "Scotland" ],
    [ "440", "Ulverston", "England" ],
    [ "109A", "Upnor", "England" ],
    [ "51", "Ventnor", "England" ],
    [ "545A", "Wadebridge", "England" ],
    [ "129", "Walton-On-The-Naze", "England" ],
    [ "36C", "Wareham (River Frome)", "England" ],
    [ "628", "Warrenpoint", "Northern Ireland" ],
    [ "63A", "Warsash", "England" ],
    [ "531", "Watchet", "England" ],
    [ "522B", "Wellhouse Rock", "England" ],
    [ "157A", "Wells", "England" ],
    [ "157", "Wells Bar", "England" ],
    [ "399A", "Wemyss Bay", "Scotland" ],
    [ "294A", "West Burra Firth", "Scotland" ],
    [ "320", "West Loch Tarbert", "Scotland" ],
    [ "124", "West Mersea", "England" ],
    [ "161A", "West Stones", "England" ],
    [ "527", "Weston-Super-Mare", "England" ],
    [ "121", "Whitaker Beacon", "England" ],
    [ "184", "Whitby", "England" ],
    [ "521", "White House", "England" ],
    [ "273B", "Whitehall", "Scotland" ],
    [ "435", "Whitehaven", "England" ],
    [ "247A", "Whitehills", "Scotland" ],
    [ "12", "Whitsand Bay", "England" ],
    [ "105", "Whitstable Approaches", "England" ],
    [ "267", "Wick", "Scotland" ],
    [ "282", "Widewall Bay", "Scotland" ],
    [ "456", "Widnes", "England" ],
    [ "144", "Winterton-On-Sea", "England" ],
    [ "164A", "Wisbech", "England" ],
    [ "163A", "Wisbech Cut", "England" ],
    [ "134A", "Woodbridge", "England" ],
    [ "134", "Woodbridge Haven", "England" ],
    [ "434", "Workington", "England" ],
    [ "75", "Worthing", "England" ],
    [ "109C", "Wouldham", "England" ],
    [ "443", "Wyre Lighthouse", "England" ],
    [ "45", "Yarmouth", "England" ],
    [ "537", "Yelland Marsh", "England" ] ]


_UKHO_NON_UK_PORT_EXPIRY = "2017-09-26" # The license for UKHO non-UK ports expires after this date.


# Port data.
#
# Port ID. port name, country.
_ports = _UKHO_UKPorts if isExpired() else ( _UKHO_UKPorts + _UKHO_NonUKPorts )