#!/usr/bin/env python3
# -*- coding: utf-8 -*-


# The program below (excluding the data) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import time


def isExpired(): return getExpiry() < time.strftime( "%Y-%m-%d" )


# Obtain the non-UK port expiration date in YYYY-MM-DD.
def getExpiry(): return "2018-09-14"


def isValidPortID( portID ):
    isValid = False
    for port in _ports:
        if portID == port[ _INDEX_PORT_ID ]:
            isValid = True
            break

    return isValid


def getCountry( portID ): 
    country = None
    for port in _ports:
        if portID == port[ _INDEX_PORT_ID ]:
            country = port[ _INDEX_PORT_COUNTRY ]
            break

    return country


def getPortName( portID ): 
    portName = None
    for port in _ports:
        if portID == port[ _INDEX_PORT_ID ]:
            portName = port[ _INDEX_PORT_NAME ]
            break

    return portName


# Returns the port ID for the first matching country.
def getPortIDForCountry( country ):
    portID = None
    for port in _ports:
        if country == port[ _INDEX_PORT_COUNTRY ]:
            portID = port[ _INDEX_PORT_ID ]
            break

    return portID


def getPortIDForCountryAndPortName( country, portName ):
    portID = None
    for port in _ports:
        if country == port[ _INDEX_PORT_COUNTRY ] and portName == port[ _INDEX_PORT_NAME ]:
            portID = port[ _INDEX_PORT_ID ]
            break

    return portID


def getPortNamesForCountry( country ):
    portNames = [ ]
    for port in _ports:
        if port[ _INDEX_PORT_COUNTRY ] == country and port[ _INDEX_PORT_NAME ] not in portNames:
            portNames.append( port[ _INDEX_PORT_NAME ] )

    return portNames


def getCountries():
    countries = [ ]
    for port in _ports:
        if port[ _INDEX_PORT_COUNTRY ] not in countries:
            countries.append( port[ _INDEX_PORT_COUNTRY ] )

    return countries


def getFirstPortID(): return _ports[ 0 ][ _INDEX_PORT_ID ]


# Indices for each port's data.
_INDEX_PORT_ID = 0
_INDEX_PORT_NAME = 1
_INDEX_PORT_COUNTRY = 2


# © Crown Copyright and/or database rights.
# Reproduced by permission of the\nController of Her Majesty’s Stationery Office and the UK Hydrographic Office.
# http://www.GOV.uk/UKHO
#
# Port ID. port name, country.
_ports = [
    [ "1", "St.Mary'S", "England" ],
    [ "2", "Penzance (Newlyn)", "England" ],
    [ "2A", "Porthleven", "England" ],
    [ "3", "Lizard Point", "England" ],
    [ "4", "Coverack", "England" ],
    [ "4A", "Helford River (Entrance)", "England" ],
    [ "5", "Falmouth", "England" ],
    [ "5A", "Truro", "England" ],
    [ "7", "Mevagissey", "England" ],
    [ "7A", "Par", "England" ],
    [ "8", "Fowey", "England" ],
    [ "8A", "Lostwithiel", "England" ],
    [ "11", "Looe", "England" ],
    [ "12", "Whitsand Bay", "England" ],
    [ "14", "Plymouth (Devonport)", "England" ],
    [ "14A", "Saltash", "England" ],
    [ "14B", "Cargreen", "England" ],
    [ "14C", "Cotehele Quay", "England" ],
    [ "14E", "Jupiter Point", "England" ],
    [ "14D", "Lopwell", "England" ],
    [ "14F", "St. Germans", "England" ],
    [ "15", "Turnchapel", "England" ],
    [ "15A", "Bovisand Pier", "England" ],
    [ "17", "River Yealm Entrance", "England" ],
    [ "20", "Salcombe", "England" ],
    [ "21", "Start Point", "England" ],
    [ "23", "Dartmouth", "England" ],
    [ "23A", "Greenway Quay", "England" ],
    [ "23B", "Stoke Gabriel (Duncannon)", "England" ],
    [ "23C", "Totnes", "England" ],
    [ "25", "Torquay", "England" ],
    [ "26", "Teignmouth (Approaches)", "England" ],
    [ "26A", "Teignmouth (New Quay)", "England" ],
    [ "26B", "Exmouth (Approaches)", "England" ],
    [ "27", "Exmouth Dock", "England" ],
    [ "27A", "Starcross", "England" ],
    [ "27B", "Turf Lock", "England" ],
    [ "27C", "Topsham", "England" ],
    [ "28", "Lyme Regis", "England" ],
    [ "29", "Bridport (West Bay)", "England" ],
    [ "30", "Chesil Beach", "England" ],
    [ "31", "Chesil Cove", "England" ],
    [ "33", "Portland", "England" ],
    [ "34A", "Mupe Bay", "England" ],
    [ "34", "Lulworth Cove", "England" ],
    [ "35", "Swanage", "England" ],
    [ "36", "Poole (Entrance)", "England" ],
    [ "36A", "Poole Harbour", "England" ],
    [ "36B", "Pottery Pier", "England" ],
    [ "36C", "Wareham (River Frome)", "England" ],
    [ "36D", "Cleavel Point", "England" ],
    [ "37", "Bournemouth", "England" ],
    [ "38", "Christchurch (Entrance)", "England" ],
    [ "38A", "Christchurch (Quay)", "England" ],
    [ "38B", "Christchurch (Tuckton)", "England" ],
    [ "39", "Hurst Point", "England" ],
    [ "40", "Lymington", "England" ],
    [ "42", "Bucklers Hard", "England" ],
    [ "43", "Stansore Point", "England" ],
    [ "45", "Yarmouth", "England" ],
    [ "46", "Totland Bay", "England" ],
    [ "48", "Freshwater Bay", "England" ],
    [ "51", "Ventnor", "England" ],
    [ "53", "Sandown", "England" ],
    [ "53A", "Foreland (Lifeboat Slip)", "England" ],
    [ "53B", "Bembridge Approaches", "England" ],
    [ "54", "Bembridge Harbour", "England" ],
    [ "58", "Ryde", "England" ],
    [ "60", "Cowes", "England" ],
    [ "60A", "Folly Inn", "England" ],
    [ "60B", "Newport", "England" ],
    [ "61", "Calshot Castle", "England" ],
    [ "62", "Southampton", "England" ],
    [ "63", "Redbridge", "England" ],
    [ "63A", "Warsash", "England" ],
    [ "63B", "Bursledon", "England" ],
    [ "64", "Lee-On-The-Solent", "England" ],
    [ "65", "Portsmouth", "England" ],
    [ "66", "Langstone Harbour", "England" ],
    [ "68", "Chichester Harbour (Entrance)", "England" ],
    [ "68A", "Northney", "England" ],
    [ "68C", "Itchenor", "England" ],
    [ "68B", "Bosham", "England" ],
    [ "68D", "Dell Quay", "England" ],
    [ "69", "Selsey Bill", "England" ],
    [ "70", "Nab Tower", "England" ],
    [ "72", "Pagham", "England" ],
    [ "73", "Bognor Regis", "England" ],
    [ "74", "Littlehampton (Entrance)", "England" ],
    [ "74B", "Arundel", "England" ],
    [ "75", "Worthing", "England" ],
    [ "81", "Shoreham", "England" ],
    [ "82", "Brighton Marina", "England" ],
    [ "83", "Newhaven", "England" ],
    [ "84", "Eastbourne", "England" ],
    [ "84A", "Sovereign Harbour", "England" ],
    [ "85", "Hastings", "England" ],
    [ "86", "Rye (Approaches)", "England" ],
    [ "86A", "Rye (Harbour)", "England" ],
    [ "87", "Dungeness", "England" ],
    [ "88", "Folkestone", "England" ],
    [ "89", "Dover", "England" ],
    [ "98", "Deal", "England" ],
    [ "99", "Richborough", "England" ],
    [ "102", "Ramsgate", "England" ],
    [ "102A", "Broadstairs", "England" ],
    [ "103", "Margate", "England" ],
    [ "104", "Herne Bay", "England" ],
    [ "105", "Whitstable Approaches", "England" ],
    [ "106", "Grovehurst Jetty", "England" ],
    [ "107", "Faversham", "England" ],
    [ "108", "Sheerness", "England" ],
    [ "108A", "Bee Ness", "England" ],
    [ "108B", "Bartlett Creek", "England" ],
    [ "108C", "Darnett Ness", "England" ],
    [ "109", "Chatham (Lock Approaches)", "England" ],
    [ "109B", "Rochester (Strood Pier)", "England" ],
    [ "109C", "Wouldham", "England" ],
    [ "109D", "New Hythe", "England" ],
    [ "109E", "Allington Lock", "England" ],
    [ "109A", "Upnor", "England" ],
    [ "110", "Southend-On-Sea", "England" ],
    [ "110A", "Coryton", "England" ],
    [ "111", "Tilbury", "England" ],
    [ "111A", "Gravesend", "England" ],
    [ "111B", "Erith", "England" ],
    [ "112", "North Woolwich", "England" ],
    [ "113", "London Bridge (Tower Pier)", "England" ],
    [ "113A", "Chelsea Bridge", "England" ],
    [ "114", "Albert Bridge", "England" ],
    [ "115", "Hammersmith Bridge", "England" ],
    [ "115A", "Kew Bridge", "England" ],
    [ "116", "Richmond Lock", "England" ],
    [ "116A", "Shivering Sand", "England" ],
    [ "117", "S.E. Long Sand", "England" ],
    [ "121", "Whitaker Beacon", "England" ],
    [ "121A", "Holliwell Point", "England" ],
    [ "121B", "Rochford", "England" ],
    [ "122", "Burnham-On-Crouch", "England" ],
    [ "122A", "North Fambridge", "England" ],
    [ "122B", "Hullbridge", "England" ],
    [ "122C", "Battlesbridge", "England" ],
    [ "123", "Bradwell Waterside", "England" ],
    [ "123A", "Osea Island", "England" ],
    [ "123B", "Maldon", "England" ],
    [ "124", "West Mersea", "England" ],
    [ "126", "Brightlingsea", "England" ],
    [ "127", "Colchester", "England" ],
    [ "128", "Clacton-On-Sea", "England" ],
    [ "129", "Walton-On-The-Naze", "England" ],
    [ "129A", "Bramble Creek", "England" ],
    [ "130", "Sunk Head", "England" ],
    [ "131", "Harwich", "England" ],
    [ "132", "Mistley", "England" ],
    [ "133", "Ipswich", "England" ],
    [ "133A", "Felixstowe Pier", "England" ],
    [ "134", "Woodbridge Haven", "England" ],
    [ "134A", "Woodbridge", "England" ],
    [ "135", "Bawdsey", "England" ],
    [ "136", "Orford Haven Bar", "England" ],
    [ "136B", "Slaughden Quay", "England" ],
    [ "136A", "Orford Quay", "England" ],
    [ "136C", "Iken Cliffs", "England" ],
    [ "137", "Orford Ness", "England" ],
    [ "139", "Aldeburgh", "England" ],
    [ "139A", "Minsmere Sluice", "England" ],
    [ "140", "Southwold", "England" ],
    [ "141", "Lowestoft", "England" ],
    [ "142", "Gorleston-On-Sea", "England" ],
    [ "142A", "Great Yarmouth (Britannia Pier)", "England" ],
    [ "143", "Caister-On-Sea", "England" ],
    [ "144", "Winterton-On-Sea", "England" ],
    [ "154", "Cromer", "England" ],
    [ "155", "Blakeney Bar", "England" ],
    [ "155A", "Blakeney", "England" ],
    [ "157A", "Wells", "England" ],
    [ "157", "Wells Bar", "England" ],
    [ "158", "Burnham (Overy Staithe)", "England" ],
    [ "161", "Hunstanton", "England" ],
    [ "161A", "West Stones", "England" ],
    [ "162", "King'S Lynn", "England" ],
    [ "163", "Outer Westmark Knock", "England" ],
    [ "163A", "Wisbech Cut", "England" ],
    [ "164", "Port Sutton Bridge", "England" ],
    [ "164A", "Wisbech", "England" ],
    [ "164B", "Lawyer'S Creek", "England" ],
    [ "165", "Tabs Head", "England" ],
    [ "166", "Boston, England", "England" ],
    [ "167", "Skegness", "England" ],
    [ "168", "Inner Dowsing Light", "England" ],
    [ "171", "Spurn Head", "England" ],
    [ "171A", "Bull Sand Fort", "England" ],
    [ "171B", "Sunk Dredged Channel", "England" ],
    [ "172", "Grimsby", "England" ],
    [ "172A", "Humber Sea Terminal", "England" ],
    [ "173", "Immingham", "England" ],
    [ "174", "Hull (King George Dock)", "England" ],
    [ "174A", "Hull (Alexandra Dock)", "England" ],
    [ "175", "Hull (Albert Dock)", "England" ],
    [ "176", "Humber Bridge", "England" ],
    [ "176A", "Brough", "England" ],
    [ "177", "Burton Stather", "England" ],
    [ "177A", "Flixborough Wharf", "England" ],
    [ "178", "Keadby", "England" ],
    [ "178A", "Owston Ferry", "England" ],
    [ "179", "Blacktoft", "England" ],
    [ "180", "Goole", "England" ],
    [ "181", "Bridlington", "England" ],
    [ "182", "Filey Bay", "England" ],
    [ "183", "Scarborough", "England" ],
    [ "184", "Whitby", "England" ],
    [ "185", "River Tees Entrance", "England" ],
    [ "186", "Middlesbrough (Dock Entrance)", "England" ],
    [ "187", "Tees (Newport) Bridge", "England" ],
    [ "188", "Hartlepool", "England" ],
    [ "189", "Seaham", "England" ],
    [ "190", "Sunderland", "England" ],
    [ "202", "River Tyne (North Shields)", "England" ],
    [ "203", "Newcastle-Upon-Tyne", "England" ],
    [ "204", "Blyth", "England" ],
    [ "205", "Coquet Island", "England" ],
    [ "206", "Amble", "England" ],
    [ "207", "North Sunderland (Northumberland)", "England" ],
    [ "208", "Holy Island", "England" ],
    [ "209", "Berwick", "England" ],
    [ "221", "Eyemouth", "Scotland" ],
    [ "222", "Dunbar", "Scotland" ],
    [ "223", "Fidra", "Scotland" ],
    [ "224", "Cockenzie", "Scotland" ],
    [ "225", "Leith", "Scotland" ],
    [ "226", "Granton", "Scotland" ],
    [ "227", "Rosyth", "Scotland" ],
    [ "228", "Grangemouth", "Scotland" ],
    [ "229", "Kincardine", "Scotland" ],
    [ "229A", "Alloa", "Scotland" ],
    [ "229B", "Stirling", "Scotland" ],
    [ "230", "Burntisland", "Scotland" ],
    [ "231", "Kirkcaldy", "Scotland" ],
    [ "232", "Methil", "Scotland" ],
    [ "233", "Anstruther Easter", "Scotland" ],
    [ "235", "River Tay Bar", "Scotland" ],
    [ "236", "Dundee", "Scotland" ],
    [ "236A", "Newburgh", "Scotland" ],
    [ "236B", "Perth", "Scotland" ],
    [ "241", "Arbroath", "Scotland" ],
    [ "242", "Montrose", "Scotland" ],
    [ "243", "Stonehaven", "Scotland" ],
    [ "244", "Aberdeen", "Scotland" ],
    [ "245", "Peterhead", "Scotland" ],
    [ "246", "Fraserburgh", "Scotland" ],
    [ "247A", "Whitehills", "Scotland" ],
    [ "247", "Banff", "Scotland" ],
    [ "248", "Buckie", "Scotland" ],
    [ "249", "Lossiemouth", "Scotland" ],
    [ "250", "Burghead", "Scotland" ],
    [ "253", "Nairn", "Scotland" ],
    [ "254", "Mcdermott Base", "Scotland" ],
    [ "255", "Fortrose", "Scotland" ],
    [ "256", "Inverness", "Scotland" ],
    [ "258", "Cromarty", "Scotland" ],
    [ "259", "Invergordon", "Scotland" ],
    [ "260", "Dingwall, Cromarty Firth", "Scotland" ],
    [ "261", "Portmahomack", "Scotland" ],
    [ "262", "Meikle Ferry", "Scotland" ],
    [ "264", "Golspie", "Scotland" ],
    [ "265", "Helmsdale", "Scotland" ],
    [ "267", "Wick", "Scotland" ],
    [ "268", "Duncansby Head", "Scotland" ],
    [ "270", "Muckle Skerry", "Scotland" ],
    [ "271", "Burray Ness", "Scotland" ],
    [ "272", "Deer Sound", "Scotland" ],
    [ "273", "Kirkwall", "Scotland" ],
    [ "273A", "Egilsay", "Scotland" ],
    [ "273B", "Whitehall", "Scotland" ],
    [ "274", "Loth", "Scotland" ],
    [ "275", "Kettletoft Pier", "Scotland" ],
    [ "276", "Rapness", "Scotland" ],
    [ "277", "Pierowall", "Scotland" ],
    [ "279", "Tingwall", "Scotland" ],
    [ "280", "Stromness", "Scotland" ],
    [ "281", "St. Mary'S (Scapa Flow)", "Scotland" ],
    [ "282A", "Bur Wick", "Scotland" ],
    [ "282", "Widewall Bay", "Scotland" ],
    [ "285", "Fair Isle", "Scotland" ],
    [ "285A", "Sumburgh (Grutness Voe)", "Scotland" ],
    [ "287", "Lerwick", "Scotland" ],
    [ "288", "Dury Voe", "Scotland" ],
    [ "289", "Out Skerries", "Scotland" ],
    [ "289A", "Toft Pier", "Scotland" ],
    [ "290", "Burra Voe (Yell Sound)", "Scotland" ],
    [ "290A", "Mid Yell", "Scotland" ],
    [ "290B", "Baltasound Pier", "Scotland" ],
    [ "291", "Burra Firth", "Scotland" ],
    [ "292", "Bluemull Sound", "Scotland" ],
    [ "293", "Sullom Voe", "Scotland" ],
    [ "293A", "Esha Ness (Hamna Voe)", "Scotland" ],
    [ "294A", "West Burra Firth", "Scotland" ],
    [ "294", "Hillswick", "Scotland" ],
    [ "295", "Scalloway", "Scotland" ],
    [ "296", "Bay Of Quendale", "Scotland" ],
    [ "296A", "Foula", "Scotland" ],
    [ "297A", "Gills Bay", "Scotland" ],
    [ "297", "Stroma", "Scotland" ],
    [ "298", "Scrabster", "Scotland" ],
    [ "299", "Sule Skerry", "Scotland" ],
    [ "300", "Portnancon", "Scotland" ],
    [ "301", "Kyle Of Durness", "Scotland" ],
    [ "304", "Rona", "Scotland" ],
    [ "308", "Stornoway", "Scotland" ],
    [ "309", "Loch Shell", "Scotland" ],
    [ "310", "E. Loch Tarbert", "Scotland" ],
    [ "310A", "Leverburgh", "Scotland" ],
    [ "310B", "Bays Loch", "Scotland" ],
    [ "311A", "Loch Carnan", "Scotland" ],
    [ "311", "Lochmaddy", "Scotland" ],
    [ "312", "Loch Skipport", "Scotland" ],
    [ "313", "Loch Boisdale", "Scotland" ],
    [ "314A", "Castlebay", "Scotland" ],
    [ "314", "Barra (North Bay)", "Scotland" ],
    [ "316", "Barra Head", "Scotland" ],
    [ "317", "Shillay", "Scotland" ],
    [ "318A", "Scolpaig", "Scotland" ],
    [ "318", "Balivanich", "Scotland" ],
    [ "320", "West Loch Tarbert", "Scotland" ],
    [ "321A", "Carloway", "Scotland" ],
    [ "321", "Little Bernera", "Scotland" ],
    [ "322", "Hirta (Bagh A' Bhaile)", "Scotland" ],
    [ "323", "Flannan Isles", "Scotland" ],
    [ "324", "Rockall", "Scotland" ],
    [ "327", "Kinlochbervie", "Scotland" ],
    [ "328", "Loch Laxford", "Scotland" ],
    [ "329", "Badcall Bay", "Scotland" ],
    [ "330", "Loch Nedd", "Scotland" ],
    [ "332", "Loch Inver", "Scotland" ],
    [ "333", "Tanera Mor", "Scotland" ],
    [ "334", "Ullapool", "Scotland" ],
    [ "336", "Mellon Charles", "Scotland" ],
    [ "336A", "Nato Jetty", "Scotland" ],
    [ "337", "Gairloch", "Scotland" ],
    [ "338A", "Applecross", "Scotland" ],
    [ "338", "Shieldaig", "Scotland" ],
    [ "339", "Plockton", "Scotland" ],
    [ "340", "Loch A' Bhraige", "Scotland" ],
    [ "341", "Broadford Bay", "Scotland" ],
    [ "342", "Portree", "Scotland" ],
    [ "343", "Loch Snizort (Uig Bay)", "Scotland" ],
    [ "344", "Loch Dunvegan", "Scotland" ],
    [ "345", "Loch Harport", "Scotland" ],
    [ "346", "Camus Nan Gall", "Scotland" ],
    [ "349", "Kyle Of Lochalsh", "Scotland" ],
    [ "349A", "Dornie Bridge", "Scotland" ],
    [ "351", "Glenelg Bay", "Scotland" ],
    [ "352", "Loch Hourn", "Scotland" ],
    [ "353A", "Mallaig", "Scotland" ],
    [ "353B", "Loch Scresort (Rhum)", "Scotland" ],
    [ "353", "Inverie Bay", "Scotland" ],
    [ "354A", "Galmisdale Pier (Eigg)", "Scotland" ],
    [ "354", "Bay Of Laig", "Scotland" ],
    [ "355", "Loch Moidart", "Scotland" ],
    [ "356", "Loch Eatharna", "Scotland" ],
    [ "357", "Gott Bay", "Scotland" ],
    [ "359", "Carsaig Bay (Mull)", "Scotland" ],
    [ "360", "Iona", "Scotland" ],
    [ "361", "Bunessan", "Scotland" ],
    [ "362", "Sound Of Ulva", "Scotland" ],
    [ "363", "Salen", "Scotland" ],
    [ "364", "Tobermory", "Scotland" ],
    [ "364A", "Salen, Sound Of Mull", "Scotland" ],
    [ "365A", "Craignure", "Scotland" ],
    [ "365", "Loch Aline", "Scotland" ],
    [ "367", "Corran", "Scotland" ],
    [ "368", "Corpach", "Scotland" ],
    [ "368A", "Loch Eil Head", "Scotland" ],
    [ "369", "Loch Leven Head", "Scotland" ],
    [ "370", "Port Appin", "Scotland" ],
    [ "370A", "Barcaldine Pier", "Scotland" ],
    [ "370B", "Loch Creran Head", "Scotland" ],
    [ "371B", "Ardchattan Point", "Scotland" ],
    [ "371C", "Bonawe", "Scotland" ],
    [ "371D", "Rubha Na Ceige", "Scotland" ],
    [ "371", "Dunstaffnage Bay", "Scotland" ],
    [ "371A", "Connel", "Scotland" ],
    [ "372", "Oban", "Scotland" ],
    [ "373", "Seil Sound", "Scotland" ],
    [ "374", "Scalasaig", "Scotland" ],
    [ "375", "Glengarrisdale Bay", "Scotland" ],
    [ "377", "Rubh' A' Mhail", "Scotland" ],
    [ "378", "Ardnave Point", "Scotland" ],
    [ "379", "Orsay", "Scotland" ],
    [ "380", "Bruichladdich", "Scotland" ],
    [ "381", "Port Ellen", "Scotland" ],
    [ "382", "Port Askaig", "Scotland" ],
    [ "383", "Craighouse", "Scotland" ],
    [ "383A", "Loch Melfort", "Scotland" ],
    [ "384", "Loch Beag", "Scotland" ],
    [ "387", "Carsaig Bay", "Scotland" ],
    [ "389", "Sound Of Gigha", "Scotland" ],
    [ "390", "Machrihanish", "Scotland" ],
    [ "391", "Southend, Kintyre", "Scotland" ],
    [ "393", "Campbeltown", "Scotland" ],
    [ "393A", "Carradale", "Scotland" ],
    [ "393B", "Loch Ranza", "Scotland" ],
    [ "394", "East Loch Tarbert", "Scotland" ],
    [ "395", "Inveraray", "Scotland" ],
    [ "396", "Rubha A' Bhodaich", "Scotland" ],
    [ "396A", "Tighnabruaich", "Scotland" ],
    [ "398", "Millport", "Scotland" ],
    [ "399", "Rothesay Bay", "Scotland" ],
    [ "399B", "Coulport", "Scotland" ],
    [ "399C", "Lochgoilhead", "Scotland" ],
    [ "399A", "Wemyss Bay", "Scotland" ],
    [ "401", "Arrochar", "Scotland" ],
    [ "402", "Rosneath", "Scotland" ],
    [ "402A", "Rhu Marina", "Scotland" ],
    [ "402B", "Faslane", "Scotland" ],
    [ "402C", "Garelochhead", "Scotland" ],
    [ "403", "Helensburgh", "Scotland" ],
    [ "404", "Greenock", "Scotland" ],
    [ "405", "Port Glasgow", "Scotland" ],
    [ "406A", "Clydebank (Rothesay Dock)", "Scotland" ],
    [ "406", "Bowling", "Scotland" ],
    [ "407", "Glasgow", "Scotland" ],
    [ "408", "Brodick Bay", "Scotland" ],
    [ "409", "Lamlash", "Scotland" ],
    [ "410", "Ardrossan", "Scotland" ],
    [ "411", "Irvine", "Scotland" ],
    [ "412", "Troon", "Scotland" ],
    [ "413", "Ayr", "Scotland" ],
    [ "414", "Girvan", "Scotland" ],
    [ "414A", "Stranraer", "Scotland" ],
    [ "415", "Portpatrick", "Scotland" ],
    [ "419", "Drummore", "Scotland" ],
    [ "420", "Luce Bay (Offshore Platform)", "Scotland" ],
    [ "420A", "Port William", "Scotland" ],
    [ "421", "Isle Of Whithorn", "Scotland" ],
    [ "422", "Garlieston", "Scotland" ],
    [ "422A", "Kirkcudbright Bay", "Scotland" ],
    [ "424", "Hestan Island", "Scotland" ],
    [ "425", "Southerness Point", "Scotland" ],
    [ "426", "Annan Waterfoot", "Scotland" ],
    [ "430", "Torduff Point", "Scotland" ],
    [ "431", "Redkirk", "Scotland" ],
    [ "432", "Silloth", "England" ],
    [ "433", "Maryport", "England" ],
    [ "434", "Workington", "England" ],
    [ "435", "Whitehaven", "England" ],
    [ "436", "Tarn Point", "England" ],
    [ "437", "Duddon Bar", "England" ],
    [ "439", "Barrow (Ramsden Dock)", "England" ],
    [ "439A", "Roa Island", "England" ],
    [ "439B", "Haws Point", "England" ],
    [ "439C", "Halfway Shoal", "England" ],
    [ "440", "Ulverston", "England" ],
    [ "440A", "Arnside", "England" ],
    [ "440B", "Morecambe", "England" ],
    [ "441", "Heysham", "England" ],
    [ "442", "Glasson Dock", "England" ],
    [ "442A", "Lancaster", "England" ],
    [ "443", "Wyre Lighthouse", "England" ],
    [ "444", "Fleetwood", "England" ],
    [ "445", "Blackpool", "England" ],
    [ "446", "Preston", "England" ],
    [ "447", "Southport", "England" ],
    [ "448", "Formby", "England" ],
    [ "451", "Liverpool (Gladstone Dock)", "England" ],
    [ "452", "Seacombe (Alfred Dock)", "England" ],
    [ "452A", "Garston", "England" ],
    [ "453", "Eastham", "England" ],
    [ "455", "Hale Head", "England" ],
    [ "456", "Widnes", "England" ],
    [ "456A", "Fiddler'S Ferry", "England" ],
    [ "461", "Hilbre Island", "England" ],
    [ "462", "Chester", "England" ],
    [ "463", "Connah'S Quay", "England" ],
    [ "464", "Mostyn Docks", "England" ],
    [ "466", "Peel", "Isle Of Man" ],
    [ "467", "Ramsey", "Isle Of Man" ],
    [ "468", "Douglas", "Isle Of Man" ],
    [ "468A", "Port St. Mary", "Isle Of Man" ],
    [ "469A", "Port Erin", "Isle Of Man" ],
    [ "469", "Calf Sound", "Isle Of Man" ],
    [ "470", "Colwyn Bay", "Wales" ],
    [ "471", "Llandudno", "Wales" ],
    [ "471A", "Conwy", "Wales" ],
    [ "472", "Beaumaris", "Wales" ],
    [ "473", "Menai Bridge", "Wales" ],
    [ "474", "Port Dinorwic", "Wales" ],
    [ "475", "Caernarfon", "Wales" ],
    [ "475A", "Fort Belan", "Wales" ],
    [ "476", "Trwyn Dinmor", "Wales" ],
    [ "476A", "Moelfre", "Wales" ],
    [ "477", "Amlwch", "Wales" ],
    [ "477A", "Cemaes Bay", "Wales" ],
    [ "478", "Holyhead", "Wales" ],
    [ "479", "Trearddur Bay", "Wales" ],
    [ "479A", "Porth Trecastell", "Wales" ],
    [ "480", "Llanddwyn Island", "Wales" ],
    [ "480A", "Trefor", "Wales" ],
    [ "481", "Porth Dinllaen", "Wales" ],
    [ "481A", "Porth Ysgaden", "Wales" ],
    [ "482A", "Aberdaron", "Wales" ],
    [ "482B", "St. Tudwal'S Roads", "Wales" ],
    [ "482", "Bardsey Island", "Wales" ],
    [ "483", "Pwllheli", "Wales" ],
    [ "483A", "Criccieth", "Wales" ],
    [ "484", "Porthmadog", "Wales" ],
    [ "485", "Barmouth", "Wales" ],
    [ "486", "Aberdovey", "Wales" ],
    [ "487", "Aberystwyth", "Wales" ],
    [ "488A", "Aberporth", "Wales" ],
    [ "488", "New Quay", "Wales" ],
    [ "489", "Port Cardigan", "Wales" ],
    [ "489A", "Cardigan (Town)", "Wales" ],
    [ "490", "Fishguard", "Wales" ],
    [ "491", "Porthgain", "Wales" ],
    [ "492", "Ramsey Sound", "Wales" ],
    [ "492A", "Solva", "Wales" ],
    [ "492B", "Little Haven", "Wales" ],
    [ "493", "Martin'S Haven", "Wales" ],
    [ "494", "Skomer Island", "Wales" ],
    [ "495", "Dale Roads", "Wales" ],
    [ "496", "Milford Haven", "Wales" ],
    [ "497", "Neyland", "Wales" ],
    [ "498", "Black Tar", "Wales" ],
    [ "499", "Haverfordwest", "Wales" ],
    [ "501", "Stackpole Quay", "Wales" ],
    [ "502", "Tenby", "Wales" ],
    [ "504", "Ferryside", "Wales" ],
    [ "504A", "Carmarthen", "Wales" ],
    [ "505", "Burry Port", "Wales" ],
    [ "505A", "Llanelli", "Wales" ],
    [ "508", "Mumbles", "Wales" ],
    [ "509", "Swansea", "Wales" ],
    [ "509A", "River Neath Entrance", "Wales" ],
    [ "510", "Port Talbot", "Wales" ],
    [ "512", "Porthcawl", "Wales" ],
    [ "513", "Barry", "Wales" ],
    [ "513A", "Flat Holm", "Wales" ],
    [ "513B", "Steep Holm", "Wales" ],
    [ "514", "Cardiff", "Wales" ],
    [ "515", "Newport", "Wales" ],
    [ "516", "Chepstow", "Wales" ],
    [ "517", "Sudbrook", "England" ],
    [ "518", "Beachley (Aust)", "England" ],
    [ "519", "Inward Rocks", "England" ],
    [ "520", "Narlwood Rocks", "England" ],
    [ "521", "White House", "England" ],
    [ "522", "Berkeley", "England" ],
    [ "522B", "Wellhouse Rock", "England" ],
    [ "522A", "Sharpness Dock", "England" ],
    [ "522C", "Epney", "England" ],
    [ "522D", "Minsterworth", "England" ],
    [ "522E", "Llanthony", "England" ],
    [ "523", "Port Of Bristol (Avonmouth)", "England" ],
    [ "523A", "Shirehampton", "England" ],
    [ "523B", "Sea Mills", "England" ],
    [ "524", "Cumberland Basin Entrance", "England" ],
    [ "524A", "Portishead", "England" ],
    [ "525A", "St. Thomas'S Head", "England" ],
    [ "525", "Clevedon", "England" ],
    [ "526", "English And Welsh Grounds", "England" ],
    [ "527", "Weston-Super-Mare", "England" ],
    [ "528", "Burnham-On-Sea", "England" ],
    [ "529", "Bridgwater", "England" ],
    [ "530", "Hinkley Point", "England" ],
    [ "531", "Watchet", "England" ],
    [ "532", "Minehead", "England" ],
    [ "533", "Porlock Bay", "England" ],
    [ "534", "Lynmouth", "England" ],
    [ "535", "Ilfracombe", "England" ],
    [ "536", "Appledore", "England" ],
    [ "537", "Yelland Marsh", "England" ],
    [ "538", "Fremington", "England" ],
    [ "539", "Barnstaple", "England" ],
    [ "540", "Bideford", "England" ],
    [ "541", "Clovelly", "England" ],
    [ "542", "Lundy", "England" ],
    [ "543", "Bude", "England" ],
    [ "544", "Boscastle", "England" ],
    [ "544A", "Port Isaac", "England" ],
    [ "545", "Padstow", "England" ],
    [ "545A", "Wadebridge", "England" ],
    [ "546", "Newquay", "England" ],
    [ "546A", "Perranporth", "England" ],
    [ "547", "St. Ives", "England" ],
    [ "547A", "Cape Cornwall, England", "England" ],
    [ "548", "Sennen Cove", "England" ],
    [ "607", "Courtown", "Ireland" ],
    [ "611", "Arklow", "Ireland" ],
    [ "613", "Wicklow", "Ireland" ],
    [ "614", "Greystones", "Ireland" ],
    [ "615", "Dun Laoghaire", "Ireland" ],
    [ "616", "Dublin Bar", "Ireland" ],
    [ "617", "Dublin (North Wall)", "Ireland" ],
    [ "618", "Howth", "Ireland" ],
    [ "621", "Malahide", "Ireland" ],
    [ "622", "Balbriggan", "Ireland" ],
    [ "623", "River Boyne Entrance", "Ireland" ],
    [ "624", "Dunany Point", "Ireland" ],
    [ "625A", "Dundalk", "Ireland" ],
    [ "625", "Soldiers Point", "Ireland" ],
    [ "626", "Greenore", "Ireland" ],
    [ "627", "Cranfield Point", "Northern Ireland" ],
    [ "628", "Warrenpoint", "Northern Ireland" ],
    [ "628A", "Newry (Victoria Lock)", "Northern Ireland" ],
    [ "629", "Kilkeel", "Northern Ireland" ],
    [ "630", "Newcastle (N. Ireland)", "Northern Ireland" ],
    [ "630A", "Killough Harbour", "Northern Ireland" ],
    [ "631", "Ardglass", "Northern Ireland" ],
    [ "632", "Killard Point", "Northern Ireland" ],
    [ "633A", "Quoile Barrier", "Northern Ireland" ],
    [ "633", "Strangford", "Northern Ireland" ],
    [ "634", "Killyleagh", "Northern Ireland" ],
    [ "635", "South Rock", "Northern Ireland" ],
    [ "636", "Portavogie", "Northern Ireland" ],
    [ "637A", "Bangor", "Northern Ireland" ],
    [ "637", "Donaghadee", "Northern Ireland" ],
    [ "638", "Belfast", "Northern Ireland" ],
    [ "639", "Carrickfergus", "Northern Ireland" ],
    [ "641", "Larne", "Northern Ireland" ],
    [ "643", "Red Bay, Northern Ireland", "Northern Ireland" ],
    [ "644", "Cushendun", "Northern Ireland" ],
    [ "651", "Ballycastle Bay", "Northern Ireland" ],
    [ "652", "Portrush", "Northern Ireland" ],
    [ "653", "Coleraine", "Northern Ireland" ],
    [ "654", "Warren Lighthouse", "Ireland" ],
    [ "655", "Moville", "Ireland" ],
    [ "656", "Quigley'S Point", "Ireland" ],
    [ "657", "Culmore Point", "Northern Ireland" ],
    [ "658", "River Foyle (Lisahally)", "Northern Ireland" ],
    [ "659", "Londonderry", "Northern Ireland" ],
    [ "660", "Culdaff Bay", "Ireland" ],
    [ "661", "Inishtrahull", "Ireland" ],
    [ "662", "Bulbinbeg", "Ireland" ],
    [ "663", "Trawbreaga Bay", "Ireland" ],
    [ "664A", "Fanad Head", "Ireland" ],
    [ "664", "Rathmullan", "Ireland" ],
    [ "665", "Mulroy Bay Bar", "Ireland" ],
    [ "666", "Fanny'S Bay", "Ireland" ],
    [ "667", "Seamount Bay", "Ireland" ],
    [ "668", "Cranford Bay", "Ireland" ],
    [ "671", "Downies Bay", "Ireland" ],
    [ "672", "Inishbofin Bay", "Ireland" ],
    [ "681", "Gweedore Harbour", "Ireland" ],
    [ "682", "Burtonport", "Ireland" ],
    [ "683", "Loughros More Bay", "Ireland" ],
    [ "685", "Killybegs", "Ireland" ],
    [ "686", "Donegal Harbour (Salt Hill Quay)", "Ireland" ],
    [ "688", "Mullaghmore", "Ireland" ],
    [ "689", "Sligo Harbour (Oyster Island)", "Ireland" ],
    [ "690", "Ballysadare Bay (Culleenamore)", "Ireland" ],
    [ "692", "Killala Bay (Inishcrone)", "Ireland" ],
    [ "693", "Ballyglass (Broadhaven)", "Ireland" ],
    [ "694", "Blacksod Quay", "Ireland" ],
    [ "695", "Inishbiggle", "Ireland" ],
    [ "696", "Clare Island", "Ireland" ],
    [ "697", "Inishgort", "Ireland" ],
    [ "700", "Roonah Quay", "Ireland" ],
    [ "701", "Killary Harbour", "Ireland" ],
    [ "702", "Bofin Harbour", "Ireland" ],
    [ "703", "Clifden Bay", "Ireland" ],
    [ "704", "Slyne Head", "Ireland" ],
    [ "705", "Roundstone Bay", "Ireland" ],
    [ "706", "Kilkieran Cove", "Ireland" ],
    [ "707", "Inishmore (Killeany Bay)", "Ireland" ],
    [ "709", "Galway", "Ireland" ],
    [ "711", "Liscannor", "Ireland" ],
    [ "712", "Seafield Point", "Ireland" ],
    [ "713A", "Carrigaholt", "Ireland" ],
    [ "713", "Kilbaha Bay", "Ireland" ],
    [ "714", "Kilrush", "Ireland" ],
    [ "715", "Tarbert Island", "Ireland" ],
    [ "716", "Foynes Island", "Ireland" ],
    [ "717", "Mellon Point", "Ireland" ],
    [ "718", "Limerick Dock", "Ireland" ],
    [ "719", "Coney Island", "Ireland" ],
    [ "721", "Fenit Pier", "Ireland" ],
    [ "722", "Smerwick Harbour", "Ireland" ],
    [ "723", "Dingle Harbour", "Ireland" ],
    [ "724", "Cromane Point", "Ireland" ],
    [ "725", "Knights Town", "Ireland" ],
    [ "726", "Ballinskelligs Bay Castle", "Ireland" ],
    [ "727", "West Cove", "Ireland" ],
    [ "728", "Dunkerron Harbour", "Ireland" ],
    [ "731", "Ballycrovane Harbour", "Ireland" ],
    [ "732", "Black Ball Harbour", "Ireland" ],
    [ "733", "Castletown Bearhaven", "Ireland" ],
    [ "734", "Bantry", "Ireland" ],
    [ "736", "Dunbeacon Harbour", "Ireland" ],
    [ "737", "Dunmanus Harbour", "Ireland" ],
    [ "741", "Crookhaven", "Ireland" ],
    [ "742", "Schull", "Ireland" ],
    [ "743", "Baltimore, Ireland", "Ireland" ],
    [ "744", "Castletownshend", "Ireland" ],
    [ "745", "Clonakilty Bay", "Ireland" ],
    [ "746", "Courtmacsherry", "Ireland" ],
    [ "747", "Kinsale", "Ireland" ],
    [ "748", "Roberts Cove", "Ireland" ],
    [ "750", "Cobh", "Ireland" ],
    [ "751", "Ringaskiddy", "Ireland" ],
    [ "752", "Marino Point", "Ireland" ],
    [ "753", "Cork City", "Ireland" ],
    [ "754", "Ballycotton", "Ireland" ],
    [ "755", "Youghal", "Ireland" ],
    [ "756", "Dungarvan Harbour", "Ireland" ],
    [ "761", "Dunmore East", "Ireland" ],
    [ "761A", "Cheekpoint", "Ireland" ],
    [ "761B", "Kilmokea Point", "Ireland" ],
    [ "762", "Waterford", "Ireland" ],
    [ "763", "New Ross", "Ireland" ],
    [ "764", "Baginbun Head", "Ireland" ],
    [ "764A", "Fethard-On-Sea", "Ireland" ],
    [ "765", "Great Saltee", "Ireland" ],
    [ "766", "Carnsore Point", "Ireland" ],
    [ "767", "Rosslare Europort", "Ireland" ],
    [ "768", "Wexford Harbour", "Ireland" ],
    [ "821", "Hvammsvik", "Iceland" ],
    [ "822", "Akranes", "Iceland" ],
    [ "835A", "Isafjordhur", "Iceland" ],
    [ "842", "Hrutafjordhur", "Iceland" ],
    [ "847", "Siglufjordhur", "Iceland" ],
    [ "849", "Akureyri", "Iceland" ],
    [ "849A", "Hrisey", "Iceland" ],
    [ "867A", "Djupivogur", "Iceland" ],
    [ "1040", "Zimnyaya Zolotitsa", "Russia" ],
    [ "1041", "Mys Kerets", "Russia" ],
    [ "1042", "Berezovyy Bar", "Russia" ],
    [ "1046", "Severodvinsk", "Russia" ],
    [ "1049", "Lopshen'Ga", "Russia" ],
    [ "1051", "Mys Letniy Orlov", "Russia" ],
    [ "1052", "Guba Pushlakhta", "Russia" ],
    [ "1054", "Mys Glubokiy", "Russia" ],
    [ "1058", "Ostrov Mal Korepalka", "Russia" ],
    [ "1060", "Ostrov Sumostrov", "Russia" ],
    [ "1061", "Ostrov Molchanov", "Russia" ],
    [ "1062", "Ostrov Konev", "Russia" ],
    [ "1064", "Ostrov Anzerskiy", "Russia" ],
    [ "1065", "Solovetskiy", "Russia" ],
    [ "1066", "Ostrov Yuzhnyy Rombak", "Russia" ],
    [ "1067", "Port Of Kem'", "Russia" ],
    [ "1069", "Mys Pon'Goma Navolok", "Russia" ],
    [ "1070", "Mys Solomenny", "Russia" ],
    [ "1071", "Kalgalaksha", "Russia" ],
    [ "1073", "Ostrov Sryedniy Guba Keret", "Russia" ],
    [ "1074", "Reka Kovda", "Russia" ],
    [ "1079", "Reka Varzuga", "Russia" ],
    [ "1080", "Tetrino", "Russia" ],
    [ "1539", "Antwerp (Prosperpolder)", "Belgium" ],
    [ "1603", "Braye", "Channel Islands" ],
    [ "1603A", "Maseline Pier", "Channel Islands" ],
    [ "1604", "St. Peter Port", "Channel Islands" ],
    [ "1605", "St. Helier", "Channel Islands" ],
    [ "1606", "St. Catherine Bay", "Channel Islands" ],
    [ "1606A", "Bouley Bay", "Channel Islands" ],
    [ "1770", "Gibraltar", "Gibraltar" ],
    [ "1770A", "Sandy Bay", "Gibraltar" ],
    [ "1773A", "Almeria", "Spain" ],
    [ "1774", "Alicante", "Spain" ],
    [ "1780", "Palma De Mallorca", "Spain" ],
    [ "1782", "Port Vendres", "France" ],
    [ "1789", "Nice", "France" ],
    [ "1790", "Monte Carlo", "Monaco" ],
    [ "1794", "Ajaccio", "Corsica" ],
    [ "1800", "La Maddalena", "Sardinia" ],
    [ "1811", "Ensenada De Tetouan", "Morocco" ],
    [ "1817", "Melilla", "Morocco" ],
    [ "1820", "Arzew", "Algeria" ],
    [ "1822", "Alger (Algiers)", "Algeria" ],
    [ "1827", "Bizerte", "Tunisia" ],
    [ "1829", "Monastir", "Tunisia" ],
    [ "1829A", "Mahdia", "Tunisia" ],
    [ "1830", "Ras Kaboudia", "Tunisia" ],
    [ "1830A", "Canal Des Kerkennah, North Entrance", "Tunisia" ],
    [ "1831", "Bancs Kerkenah, East Point", "Tunisia" ],
    [ "1832", "Bordj El Hassar", "Tunisia" ],
    [ "1833", "Kerkennah Banks, South Point", "Tunisia" ],
    [ "1835", "La Skhirra", "Tunisia" ],
    [ "1837", "Bou Grara", "Tunisia" ],
    [ "1839", "Adjim Bar", "Tunisia" ],
    [ "1843", "Ras El Ketef", "Tunisia" ],
    [ "1880", "Valletta", "Malta" ],
    [ "1894A", "Porto Marghera", "Italy" ],
    [ "1908A", "Ploce", "Croatia" ],
    [ "1908B", "Korcula", "Croatia" ],
    [ "1908C", "Ubli (Lastovo)", "Croatia" ],
    [ "1920", "Pandeleimon", "Greece" ],
    [ "1921", "Galaxidi", "Greece" ],
    [ "1922", "Korinthos (Corinth)", "Greece" ],
    [ "1940", "Chalkis (S. Of Bridge)", "Greece" ],
    [ "1941", "Chalkis (N. Of Bridge)", "Greece" ],
    [ "1942", "Steno Knimidas", "Greece" ],
    [ "1943", "Volos", "Greece" ],
    [ "1946", "Thessaloniki", "Greece" ],
    [ "1950", "Aydincik Koqu", "Asia Minor And Grecian Archipelago" ],
    [ "1968", "Ayvalik", "Asia Minor And Grecian Archipelago" ],
    [ "1969", "Izmir (Smyrna)", "Asia Minor And Grecian Archipelago" ],
    [ "1983", "Dhavlos", "Cyprus" ],
    [ "1984", "Kyrenia", "Cyprus" ],
    [ "1984A", "Akrotiri", "Cyprus" ],
    [ "1984B", "Limassol", "Cyprus" ],
    [ "1985", "Famagusta", "Cyprus" ],
    [ "1987", "Trablous (Tripoli)", "Lebanon" ],
    [ "1987A", "Jounie", "Lebanon" ],
    [ "1988", "Beirut", "Lebanon" ],
    [ "1988A", "Saida (Sidon)", "Lebanon" ],
    [ "1988B", "Sour (Tyr)", "Lebanon" ],
    [ "1989", "Hefa (Haifa)", "Israel" ],
    [ "1990", "Ashdod", "Israel" ],
    [ "1991A", "Mina' Dumyat", "Egypt" ],
    [ "1993", "El-Sallum", "Egypt" ],
    [ "1996", "Marsa Al Burayqah", "Libya" ],
    [ "1997", "Misratah", "Libya" ],
    [ "1998", "Tarabulus (Tripoli)", "Libya" ],
    [ "2006A", "Baie Norvegienne", "Antarctica" ],
    [ "2007", "Port Jeanne D'Arc", "Antarctica" ],
    [ "2007A", "Baie Larose", "Antarctica" ],
    [ "2009", "Mawson", "Antarctica" ],
    [ "2010", "Heard Island", "Antarctica" ],
    [ "2012", "Gauss Station", "Antarctica" ],
    [ "2018", "Scott Base", "Antarctica" ],
    [ "2018A", "Shackleton Glacier", "Antarctica" ],
    [ "2019", "Kainan Bay", "Antarctica" ],
    [ "2020", "Eklund Islands", "Antarctica" ],
    [ "2020A", "Hobbs Pool", "Antarctica" ],
    [ "2020B", "Ablation Lake", "Antarctica" ],
    [ "2021", "Stonington", "Antarctica" ],
    [ "2022", "Rothera Point", "Antarctica" ],
    [ "2023", "Detaille Island", "Antarctica" ],
    [ "2024", "Prospect Point", "Antarctica" ],
    [ "2026", "Marina Point", "Antarctica" ],
    [ "2032", "Wiencke Island (Port Lockroy)", "Antarctica" ],
    [ "2033", "Dorian Bay", "Antarctica" ],
    [ "2034", "Lemaire Island (Caleta Gloria)", "Antarctica" ],
    [ "2036", "Gerlache Strait (Nansen Island)", "Antarctica" ],
    [ "2039A", "Harmony Cove", "Antarctica" ],
    [ "2040", "Admiralty Bay", "Antarctica" ],
    [ "2041", "Potter Cove", "Antarctica" ],
    [ "2041A", "Ardley Cove", "Antarctica" ],
    [ "2041C", "Gibbs Island", "Antarctica" ],
    [ "2042", "Elephant Island", "Antarctica" ],
    [ "2042A", "Clarence Island", "Antarctica" ],
    [ "2043", "Hope Bay", "Antarctica" ],
    [ "2044", "Pastorizo Bay", "Antarctica" ],
    [ "2044A", "Whiskey Bay", "Antarctica" ],
    [ "2045", "Ronne Ice Shelf", "Antarctica" ],
    [ "2045A", "Weddell Sea", "Antarctica" ],
    [ "2046", "Shackleton Base", "Antarctica" ],
    [ "2050", "Moltke Harbour", "Antarctica" ],
    [ "2051", "King Edward Cove", "Antarctica" ],
    [ "2052", "Leith Harbour", "Antarctica" ],
    [ "2052A", "Bay Of Isles", "Antarctica" ],
    [ "2053", "Elsehul", "Antarctica" ],
    [ "2055", "Scotia Bay", "Antarctica" ],
    [ "2056", "Signy Island", "Antarctica" ],
    [ "2059", "Gough Island", "Antarctica" ],
    [ "2060", "Tristan Da Cunha", "Antarctica" ],
    [ "2065", "Fanny Cove Creek", "Falkland Islands" ],
    [ "2065A", "North Arm", "Falkland Islands" ],
    [ "2065B", "Bleaker Island", "Falkland Islands" ],
    [ "2066", "Adventure Sound", "Falkland Islands" ],
    [ "2067", "Lively Settlement", "Falkland Islands" ],
    [ "2067A", "Walker Creek", "Falkland Islands" ],
    [ "2067B", "Darwin Harbour (Goose Green)", "Falkland Islands" ],
    [ "2067C", "Mare Harbour", "Falkland Islands" ],
    [ "2067D", "Fitzroy Creek", "Falkland Islands" ],
    [ "2068", "Stanley", "Falkland Islands" ],
    [ "2069", "Berkeley Sound", "Falkland Islands" ],
    [ "2070", "Port Salvador Entrance", "Falkland Islands" ],
    [ "2072", "Port San Carlos", "Falkland Islands" ],
    [ "2073", "Ajax Bay", "Falkland Islands" ],
    [ "2074", "North West Islands", "Falkland Islands" ],
    [ "2074A", "Brenton Loch", "Falkland Islands" ],
    [ "2074B", "Port Howard", "Falkland Islands" ],
    [ "2074C", "Swan Island", "Falkland Islands" ],
    [ "2074D", "Egg Harbour", "Falkland Islands" ],
    [ "2075", "Great Island", "Falkland Islands" ],
    [ "2076", "Speedwell Island", "Falkland Islands" ],
    [ "2077", "Fox Bay", "Falkland Islands" ],
    [ "2077A", "Albemarle", "Falkland Islands" ],
    [ "2077B", "Port Stephens", "Falkland Islands" ],
    [ "2078", "Dyke Island", "Falkland Islands" ],
    [ "2079", "New Island", "Falkland Islands" ],
    [ "2079A", "Gull Harbour", "Falkland Islands" ],
    [ "2081", "Chartres", "Falkland Islands" ],
    [ "2081A", "Roy Cove", "Falkland Islands" ],
    [ "2082", "Westpoint Island", "Falkland Islands" ],
    [ "2082A", "Hill Cove", "Falkland Islands" ],
    [ "2082B", "Saunders Island", "Falkland Islands" ],
    [ "2082C", "Port Egmont", "Falkland Islands" ],
    [ "2082D", "Keppel Sound", "Falkland Islands" ],
    [ "2083", "Golding Island", "Falkland Islands" ],
    [ "2083A", "Pebble Island", "Falkland Islands" ],
    [ "2084", "Tamar Pass", "Falkland Islands" ],
    [ "2096", "Rio Grande Entrance, Argentina", "Argentina" ],
    [ "2101", "Punta Loyola (Puerto Gallegos)", "Argentina" ],
    [ "2103", "Puerto Santa Cruz Bar", "Argentina" ],
    [ "2106", "Bahia Laura", "Argentina" ],
    [ "2110", "Bahia Uruguay", "Argentina" ],
    [ "2116", "Isla Tova", "Argentina" ],
    [ "2117", "Puerto Melo", "Argentina" ],
    [ "2124", "Bahia Engano (Puerto Rawson)", "Argentina" ],
    [ "2126", "Puerto Madryn", "Argentina" ],
    [ "2145A", "Canal Principal (Buoy No. 12)", "Argentina" ],
    [ "2147", "Puerto Belgrano", "Argentina" ],
    [ "2160", "Punta Piedras", "Argentina" ],
    [ "2163", "Banco Chico", "Argentina" ],
    [ "2167", "Paysandu", "Uruguay" ],
    [ "2168", "Nueva Palmira", "Uruguay" ],
    [ "2170", "Puerto Sauce", "Uruguay" ],
    [ "2268", "Montagne D'Argent", "French Guiana" ],
    [ "2269", "Degrad Des Cannes", "French Guiana" ],
    [ "2272", "Ilot Brigandin", "French Guiana" ],
    [ "2273", "Sinnamary", "French Guiana" ],
    [ "2275", "Saint Laurent Du Maroni", "French Guiana" ],
    [ "2282", "Coppename River", "Suriname" ],
    [ "2287", "New Amsterdam", "Guyana" ],
    [ "2288", "Belfield", "Guyana" ],
    [ "2289", "Demarara Light Buoy", "Guyana" ],
    [ "2290", "Georgetown", "Guyana" ],
    [ "2291", "Linden", "Guyana" ],
    [ "2292", "Bluejacket Beacon", "Guyana" ],
    [ "2293", "Parika", "Guyana" ],
    [ "2294", "Fort Island", "Guyana" ],
    [ "2296", "Wakenaam", "Guyana" ],
    [ "2298", "Aliki", "Guyana" ],
    [ "2299", "Stampa Island", "Guyana" ],
    [ "2300", "Makauria", "Guyana" ],
    [ "2301", "Bartica", "Guyana" ],
    [ "2302", "Pomerun River Mouth", "Guyana" ],
    [ "2303", "Charity", "Guyana" ],
    [ "2305", "Punta Waini", "Guyana" ],
    [ "2308", "Isla Tercera", "Venezuela" ],
    [ "2312", "Rio Pedernales (Lagoven Jetty)", "Venezuela" ],
    [ "2315", "Guanoco", "Venezuela" ],
    [ "2316", "Carapita", "Venezuela" ],
    [ "2319", "Gaspar Grande", "Trinidad" ],
    [ "2321", "Port Of Spain", "Trinidad" ],
    [ "2322", "Lisas Point", "Trinidad" ],
    [ "2323", "Pointe-A-Pierre", "Trinidad" ],
    [ "2324", "Point Fortin", "Trinidad" ],
    [ "2325", "Bonasse Pier", "Trinidad" ],
    [ "2327", "Herine (Erin) Bay", "Trinidad" ],
    [ "2329", "Guayaguayare Bay", "Trinidad" ],
    [ "2331", "Nariva River (Cocal)", "Trinidad" ],
    [ "2332", "Guayamare Point", "Trinidad" ],
    [ "2333", "Toco", "Trinidad" ],
    [ "2335", "Las Cuevas Bay", "Trinidad" ],
    [ "2336", "Scarborough, Tobago", "Tobago" ],
    [ "2338", "Man Of War Bay", "Tobago" ],
    [ "2339", "Plymouth", "Tobago" ],
    [ "2344", "Puerto Carupano", "Venezuela" ],
    [ "2381", "Bahia El Tablazo", "Venezuela" ],
    [ "2382", "Punta De Palmas", "Venezuela" ],
    [ "2385", "Riohacha", "Colombia" ],
    [ "2403", "Greytown", "Nicaragua" ],
    [ "2404", "Bluefields Bluff", "Nicaragua" ],
    [ "2405", "Great Corn Island", "Nicaragua" ],
    [ "2407", "Pearl Cays", "Nicaragua" ],
    [ "2409", "Old Providence", "Nicaragua" ],
    [ "2412", "Cabo Gracias A Dios", "Nicaragua" ],
    [ "2417", "Isla De Guanaja", "Honduras" ],
    [ "2418", "Port Royal, Honduras", "Honduras" ],
    [ "2419", "Coxen Hole Pier", "Honduras" ],
    [ "2422", "Rio Dulce Entrance", "Guatemala" ],
    [ "2424", "Hunting Cay", "Belize" ],
    [ "2425", "Placencia", "Belize" ],
    [ "2426", "Carrie Bow Cay", "Belize" ],
    [ "2428", "Belize City", "Belize" ],
    [ "2437", "Bridgetown", "Windward Islands" ],
    [ "2439", "St. George'S Harbour", "Windward Islands" ],
    [ "2439A", "Prickly Bay", "Windward Islands" ],
    [ "2439B", "Secret Harbour", "Windward Islands" ],
    [ "2441", "Hillsborough Bay", "Windward Islands" ],
    [ "2441A", "Clifton Harbour", "Windward Islands" ],
    [ "2442", "Tobago Cays", "Windward Islands" ],
    [ "2442A", "Charlestown Bay", "Windward Islands" ],
    [ "2443", "Mustique", "Windward Islands" ],
    [ "2444", "Kingstown", "Windward Islands" ],
    [ "2446A", "Vieux Fort Bay", "Windward Islands" ],
    [ "2450", "Woodbridge Bay", "Leeward Islands" ],
    [ "2450A", "Portsmouth, Dominica", "Leeward Islands" ],
    [ "2455", "Little Bay", "Leeward Islands" ],
    [ "2456", "St. Johns, Antigua", "Leeward Islands" ],
    [ "2457", "English Harbour", "Leeward Islands" ],
    [ "2459", "Road Bay", "Leeward Islands" ],
    [ "2460", "Anegada", "Leeward Islands" ],
    [ "2461", "Tortola", "Leeward Islands" ],
    [ "2461A", "Saint John", "Leeward Islands" ],
    [ "2468", "Punta Tuna", "Puerto Rico" ],
    [ "2482", "Port Morant", "Jamaica" ],
    [ "2483", "Port Royal", "Jamaica" ],
    [ "2484", "Port Esquivel", "Jamaica" ],
    [ "2485", "Black River", "Jamaica" ],
    [ "2486", "Savanna La Mar", "Jamaica" ],
    [ "2491", "Oracabessa", "Jamaica" ],
    [ "2494", "Blower Rock", "Jamaica" ],
    [ "2495", "Banco Serranilla", "Jamaica" ],
    [ "2498", "George Town", "Cayman Islands" ],
    [ "2498A", "Newlands Barcadere", "Cayman Islands" ],
    [ "2498B", "Gun Bay (East End, Public Dock)", "Cayman Islands" ],
    [ "2499", "West End", "Cayman Islands" ],
    [ "2501", "Santiago", "Cuba" ],
    [ "2502", "Puerto Pilon", "Cuba" ],
    [ "2503", "Manzanillo, Cuba", "Cuba" ],
    [ "2506", "Cienfuegos", "Cuba" ],
    [ "2508", "Los Arroyos", "Cuba" ],
    [ "2509", "Bahia Honda", "Cuba" ],
    [ "2509A", "Bahia De Cabanas", "Cuba" ],
    [ "2509B", "Puerto Del Mariel", "Cuba" ],
    [ "2511", "Matanzas", "Cuba" ],
    [ "2512", "Cardenas", "Cuba" ],
    [ "2513", "Isabela", "Cuba" ],
    [ "2515", "Cayo Paredon Grande", "Cuba" ],
    [ "2516", "Bahia Nuevitas Entrance", "Cuba" ],
    [ "2517", "Nuevitas", "Cuba" ],
    [ "2518", "Puerto Padre", "Cuba" ],
    [ "2520", "Punta Caranero", "Cuba" ],
    [ "2521", "Antilla", "Cuba" ],
    [ "2522", "Puerto Tanamo", "Cuba" ],
    [ "2525", "Punta  Maisi", "Cuba" ],
    [ "2529", "Grand Turk", "Turks Islands" ],
    [ "2530", "Sandy Point", "Turks Islands" ],
    [ "2531", "Mathew Town", "Bahama Islands" ],
    [ "2532", "Little Inagua", "Bahama Islands" ],
    [ "2534", "Start Point", "Bahama Islands" ],
    [ "2536", "Datum Bay", "Bahama Islands" ],
    [ "2539", "San Salvador", "Bahama Islands" ],
    [ "2541", "Nurse Channel", "Bahama Islands" ],
    [ "2543", "Long Island, Bahamas", "Bahama Islands" ],
    [ "2545A", "Steventon", "Bahama Islands" ],
    [ "2545", "Exuma Harbour", "Bahama Islands" ],
    [ "2546", "Wide Opening", "Bahama Islands" ],
    [ "2547", "Ship Channel", "Bahama Islands" ],
    [ "2549A", "Bannerman Town", "Bahama Islands" ],
    [ "2549", "The Bight", "Bahama Islands" ],
    [ "2551", "Royal Island Harbour", "Bahama Islands" ],
    [ "2554", "Fresh Creek", "Bahama Islands" ],
    [ "2554A", "Mastic Point", "Bahama Islands" ],
    [ "2555", "Great Stirrup Cay", "Bahama Islands" ],
    [ "2557", "South Riding Rock", "Bahama Islands" ],
    [ "2559", "Elbow Cay", "Bahama Islands" ],
    [ "2561", "Pelican Harbour", "Bahama Islands" ],
    [ "2562", "Green Turtle Cay", "Bahama Islands" ],
    [ "2563", "Pensacola Cay", "Bahama Islands" ],
    [ "2564", "Walker Cay", "Bahama Islands" ],
    [ "2566", "Freeport Harbour", "Bahama Islands" ],
    [ "2568", "Saint David'S Island", "Bermuda" ],
    [ "2569", "Bermuda (Saint George'S Island)", "Bermuda" ],
    [ "2570", "Great Sound", "Bermuda" ],
    [ "3460A", "Santa Cruz (Flores)", "Azores" ],
    [ "3470", "Funchal", "Madeira Islands" ],
    [ "3520A", "Sidi Ifni", "Morocco" ],
    [ "3542", "Gambia Fairway", "The Gambia" ],
    [ "3543", "Buniada Point", "The Gambia" ],
    [ "3544", "Banjul", "The Gambia" ],
    [ "3545", "Dog Island", "The Gambia" ],
    [ "3546", "James Island, Gambia", "The Gambia" ],
    [ "3547", "Tendaba", "The Gambia" ],
    [ "3548", "Balingo", "The Gambia" ],
    [ "3549", "Kau-Ur", "The Gambia" ],
    [ "3550", "Kuntaur", "The Gambia" ],
    [ "3550A", "Georgetown, Gambia", "The Gambia" ],
    [ "3550B", "Bansang", "The Gambia" ],
    [ "3550C", "Fatoto", "The Gambia" ],
    [ "3558", "Farim", "Guinea-Bissau" ],
    [ "3564", "Porto Uana", "Guinea-Bissau" ],
    [ "3565", "Bambadinca", "Guinea-Bissau" ],
    [ "3570", "Rio Nunez Approaches", "Guinea" ],
    [ "3571A", "Pointe Malouine", "Guinea" ],
    [ "3571B", "Victoria (Rio Nunez)", "Guinea" ],
    [ "3573", "Taboria", "Guinea" ],
    [ "3574", "Dubreka", "Guinea" ],
    [ "3577", "Ile Tannah", "Guinea" ],
    [ "3578", "Yelibuya Sound", "Guinea" ],
    [ "3580", "Freetown", "Sierra Leone" ],
    [ "3582", "Pepel", "Sierra Leone" ],
    [ "3583", "Jui", "Sierra Leone" ],
    [ "3584", "Banana Islands", "Sierra Leone" ],
    [ "3586", "Shenge Point", "Sierra Leone" ],
    [ "3586A", "Sheather Rock", "Sierra Leone" ],
    [ "3587", "Titibul Creek", "Sierra Leone" ],
    [ "3587A", "Falcon Point", "Sierra Leone" ],
    [ "3587B", "Governor Hill Point", "Sierra Leone" ],
    [ "3589", "Bonthe", "Sierra Leone" ],
    [ "3591", "Shebar Entrance", "Sierra Leone" ],
    [ "3592", "Gallinas River", "Sierra Leone" ],
    [ "3594", "Cape Mount", "Liberia" ],
    [ "3596", "Farmington River", "Liberia" ],
    [ "3597", "Buchanan", "Liberia" ],
    [ "3599", "Cestos Bay", "Liberia" ],
    [ "3600", "Baffu Bay", "Liberia" ],
    [ "3601", "Sinoe Bay", "Liberia" ],
    [ "3602", "King Wills Town", "Liberia" ],
    [ "3604", "Subbubo Point", "Liberia" ],
    [ "3606", "Cape Palmas", "Liberia" ],
    [ "3608", "Tabu River", "Cote D'Ivoire" ],
    [ "3610", "San Pedro", "Cote D'Ivoire" ],
    [ "3611", "Sassandra Anchorage", "Cote D'Ivoire" ],
    [ "3613", "Grand Lahou", "Cote D'Ivoire" ],
    [ "3619", "Axim", "Ghana" ],
    [ "3620", "Dix Cove", "Ghana" ],
    [ "3621", "Takoradi", "Ghana" ],
    [ "3622", "Sekondi", "Ghana" ],
    [ "3624", "Cape Coast", "Ghana" ],
    [ "3626", "Accra", "Ghana" ],
    [ "3627", "Tema", "Ghana" ],
    [ "3628", "Ada Panya (Riverside)", "Ghana" ],
    [ "3633", "Cotonou", "Benin" ],
    [ "3635", "Lagos Bar", "Nigeria" ],
    [ "3635A", "Badagry Creek", "Nigeria" ],
    [ "3636", "Apapa", "Nigeria" ],
    [ "3638", "Benin River Bar", "Nigeria" ],
    [ "3640", "Youngtown", "Nigeria" ],
    [ "3641", "Koko", "Nigeria" ],
    [ "3642", "Sapele", "Nigeria" ],
    [ "3643", "Ogidigbe", "Nigeria" ],
    [ "3644", "Madagho", "Nigeria" ],
    [ "3647", "Rugged Point", "Nigeria" ],
    [ "3648", "Warri", "Nigeria" ],
    [ "3649", "Forcados River Bar", "Nigeria" ],
    [ "3650", "Forcados", "Nigeria" ],
    [ "3651", "Burutu", "Nigeria" ],
    [ "3654", "Akassa", "Nigeria" ],
    [ "3655", "Brass", "Nigeria" ],
    [ "3656", "Degema", "Nigeria" ],
    [ "3657", "New Calabar River Bar", "Nigeria" ],
    [ "3658", "Percival Point", "Nigeria" ],
    [ "3659", "Bakana", "Nigeria" ],
    [ "3660", "Bugama", "Nigeria" ],
    [ "3661", "Bonny River Approaches", "Nigeria" ],
    [ "3661A", "Bonny River Bar", "Nigeria" ],
    [ "3662", "Bonny Town", "Nigeria" ],
    [ "3663", "Ford Point", "Nigeria" ],
    [ "3664", "Port Harcourt", "Nigeria" ],
    [ "3666", "Opobo River Entrance (Sandy Point)", "Nigeria" ],
    [ "3667", "Qua Iboe River Entrance", "Nigeria" ],
    [ "3668", "Calabar River No. 2 Buoy", "Nigeria" ],
    [ "3668A", "Bakassi Bank", "Nigeria" ],
    [ "3669", "Jamestown", "Nigeria" ],
    [ "3671", "James Island", "Nigeria" ],
    [ "3673", "Calabar", "Nigeria" ],
    [ "3675", "Inikoi Island", "Nigeria" ],
    [ "3676", "Esu Errorup", "Nigeria" ],
    [ "3677", "Rio Del Rey Entrance", "Cameroon" ],
    [ "3679", "Port Sonara", "Nigeria" ],
    [ "3680", "Man O War Bay", "Cameroon" ],
    [ "3681", "Bimbia River Entrance", "Cameroon" ],
    [ "3682", "Tiko", "Cameroon" ],
    [ "3683", "Cap Cameroun", "Cameroon" ],
    [ "3684", "Douala", "Cameroon" ],
    [ "3685", "Manoka", "Cameroon" ],
    [ "3686", "Malimba", "Cameroon" ],
    [ "3688", "Kribi", "Cameroon" ],
    [ "3697", "Pagalu (Annobon)", "Equatorial Guinea" ],
    [ "3704", "Cap Esterias", "Gabon" ],
    [ "3708", "Kondjo Entrance", "Gabon" ],
    [ "3713", "Baie De Mayumba", "Gabon" ],
    [ "3716", "Pointe-Noire", "The Congo" ],
    [ "3721", "Pointe Bulabemba", "Angola" ],
    [ "3770", "Ascension Island", "Mid South Atlantic Islands" ],
    [ "3771", "St. Helena Island", "Mid South Atlantic Islands" ],
    [ "3777", "Lamberts Bay", "South Africa" ],
    [ "3794", "Port Alfred", "South Africa" ],
    [ "3804", "Maputo", "Mozambique" ],
    [ "3806", "Limpopo River Bar", "Mozambique" ],
    [ "3820", "Porto De Sofala", "Mozambique" ],
    [ "3822", "Pungue River Bar", "Mozambique" ],
    [ "3823", "Beira", "Mozambique" ],
    [ "3824", "Mapanda", "Mozambique" ],
    [ "3826", "Inhamissengo Entrance", "Mozambique" ],
    [ "3828", "Mchenga", "Mozambique" ],
    [ "3833", "Macuse", "Mozambique" ],
    [ "3834", "Maquivale", "Mozambique" ],
    [ "3838", "Porto De Moebase", "Mozambique" ],
    [ "3840", "Moma River Bar", "Mozambique" ],
    [ "3843", "Angoche (Canal Do Sul)", "Mozambique" ],
    [ "3847", "Mocambo", "Mozambique" ],
    [ "3850", "Nacala", "Mozambique" ],
    [ "3852", "Port Simuco", "Mozambique" ],
    [ "3855", "Pemba", "Mozambique" ],
    [ "3950", "Pointe Des Galets", "La Reunion" ],
    [ "3951", "St. Leu", "La Reunion" ],
    [ "3952", "St. Pierre", "La Reunion" ],
    [ "3956", "Port Louis, Mauritius", "Mauritius Group" ],
    [ "3957", "Vieux Grand Port", "Mauritius Group" ],
    [ "3959", "Rodrigues", "Mauritius Group" ],
    [ "3960", "Cargados Carajos", "Mauritius Group" ],
    [ "3961", "Agalega Islands", "Mauritius Group" ],
    [ "3962", "Coetivy Island", "Seychelles" ],
    [ "3963", "Ile Aux Vaches", "Seychelles" ],
    [ "3964", "Ile Denis", "Seychelles" ],
    [ "3965A", "La Digue", "Seychelles" ],
    [ "3965B", "Praslin", "Seychelles" ],
    [ "3965", "Baie Curieuse", "Seychelles" ],
    [ "3967", "Port Victoria", "Seychelles" ],
    [ "3970", "Bancs Africains", "Seychelles" ],
    [ "3970A", "Eagle Island", "Seychelles" ],
    [ "3971", "D'Arros Island", "Seychelles" ],
    [ "3971A", "Iles Desroches", "Seychelles" ],
    [ "3972", "Marie Louise Island", "Seychelles" ],
    [ "3972A", "Alphonse Island", "Seychelles" ],
    [ "3973", "St. Pierre Island", "Seychelles" ],
    [ "3975", "Farquhar Islands", "Seychelles" ],
    [ "3976", "Cosmoledo Islands", "Seychelles" ],
    [ "3977", "Assomption Island", "Seychelles" ],
    [ "3978", "Aldabra Islands", "Seychelles" ],
    [ "3979", "Iles Glorieuses", "Comoro Islands" ],
    [ "3981", "Moutsamoudou", "Comoro Islands" ],
    [ "3982", "Fomboni", "Comoro Islands" ],
    [ "3983", "Moroni", "Comoro Islands" ],
    [ "3984", "Ruvuma Bay", "Tanzania" ],
    [ "3985", "Mtwara Bay", "Tanzania" ],
    [ "3986", "Lindi", "Tanzania" ],
    [ "3988", "Kiswere Haven", "Tanzania" ],
    [ "3990", "Kilwa Masoko", "Tanzania" ],
    [ "3993", "Chole Bay", "Tanzania" ],
    [ "3995", "Simba Uranga", "Tanzania" ],
    [ "3996", "Salale", "Tanzania" ],
    [ "3997", "Batja", "Tanzania" ],
    [ "3998", "Usimbe", "Tanzania" ],
    [ "4000A", "Ras Rangoni", "Tanzania" ],
    [ "4000", "Latham Island", "Tanzania" ],
    [ "4001", "Dar Es Salaam", "Tanzania" ],
    [ "4002", "Bagamoyo", "Tanzania" ],
    [ "4005", "Ras Kizimkazi", "Tanzania" ],
    [ "4006", "Zanzibar", "Tanzania" ],
    [ "4007", "Mkokotoni Harbour", "Tanzania" ],
    [ "4008", "Pangani Bay", "Tanzania" ],
    [ "4009", "Mchengangazi Pass", "Tanzania" ],
    [ "4010", "Mkoani", "Tanzania" ],
    [ "4011", "Mesali Island", "Tanzania" ],
    [ "4013", "Msuka Bay", "Tanzania" ],
    [ "4014", "Tanga Bay", "Tanzania" ],
    [ "4015", "Wasini Island", "Kenya" ],
    [ "4017", "Kilindini", "Kenya" ],
    [ "4022", "Kilifi", "Kenya" ],
    [ "4024", "Malindi", "Kenya" ],
    [ "4026", "Mwamba Wa Ziwaiu", "Kenya" ],
    [ "4027", "Ziwa La Juu", "Kenya" ],
    [ "4028", "Shela", "Kenya" ],
    [ "4031", "Kiunga", "Kenya" ],
    [ "4032", "Buur Gaabo", "Somalia" ],
    [ "4036", "Baraawe (Brava)", "Somalia" ],
    [ "4037", "Marka", "Somalia" ],
    [ "4040", "Cadale (Itala)", "Somalia" ],
    [ "4048", "Raas Xaafuun", "Somalia" ],
    [ "4050", "Shiq", "Suqutra" ],
    [ "4051", "Ra'S Qalansiyah", "Suqutra" ],
    [ "4052", "Ghubba Di-Net", "Suqutra" ],
    [ "4055", "Kal Farun", "Suqutra" ],
    [ "4056", "Raas Caseyr (Capo Guardafui)", "Somalia" ],
    [ "4057", "Caluula", "Somalia" ],
    [ "4060", "Laasqoray", "Somalia" ],
    [ "4062", "Xiis", "Somalia" ],
    [ "4065", "Berbera", "Somalia" ],
    [ "4067", "Saylac", "Somalia" ],
    [ "4069", "Ghoubbet Kharab", "Djibouti" ],
    [ "4070", "Obock", "Djibouti" ],
    [ "4072", "Aseb", "Eritrea" ],
    [ "4074", "Ed", "Eritrea" ],
    [ "4076", "Anfile Bay", "Eritrea" ],
    [ "4087", "Sawakin", "Sudan" ],
    [ "4091", "Muhammad Qol", "Sudan" ],
    [ "4094", "Marsa Sha'B", "Egypt" ],
    [ "4095", "Barnis (Berenice)", "Egypt" ],
    [ "4100", "Hurghada (Al Ghardaqah)", "Egypt" ],
    [ "4115", "Sharm Ash Shaykh (Sharm El Sheikh)", "Egypt" ],
    [ "4117", "Khalij Al Qarah (Dhahab)", "Egypt" ],
    [ "4118", "Eilat", "Israel" ],
    [ "4119", "Al 'Aqaba", "Jordan" ],
    [ "4120", "Humaydah", "Saudi Arabia" ],
    [ "4122", "Tiran Island (Johnson Point)", "Saudi Arabia" ],
    [ "4123", "Umm Qusur", "Saudi Arabia" ],
    [ "4125", "Sharm An Nu'Man", "Saudi Arabia" ],
    [ "4127", "Mardunah", "Saudi Arabia" ],
    [ "4129", "Al Hasani", "Saudi Arabia" ],
    [ "4131", "Yanbu Al Bahr", "Saudi Arabia" ],
    [ "4131A", "Madinat Yanbu As Sinaiyah", "Saudi Arabia" ],
    [ "4133", "Rabigh", "Saudi Arabia" ],
    [ "4135", "Jeddah (Ghubbat Asharah)", "Saudi Arabia" ],
    [ "4138", "Sanak Island, Saudi Arabia", "Saudi Arabia" ],
    [ "4139", "Al Qunfudhah", "Saudi Arabia" ],
    [ "4140", "Hadarah  Island", "Saudi Arabia" ],
    [ "4142", "Jizan", "Saudi Arabia" ],
    [ "4144", "Tiqfash", "Republic Of Yemen" ],
    [ "4146", "Ras Al Katib", "Republic Of Yemen" ],
    [ "4146A", "Al Hudaydah", "Republic Of Yemen" ],
    [ "4147", "Ras Mujamila", "Republic Of Yemen" ],
    [ "4149", "Abu Ali Islands", "Republic Of Yemen" ],
    [ "4150", "Jazirat Al Hanish Al Kabir", "Republic Of Yemen" ],
    [ "4151", "Al Mukha", "Republic Of Yemen" ],
    [ "4155", "Aden", "Republic Of Yemen" ],
    [ "4156", "Shuqra", "Republic Of Yemen" ],
    [ "4157", "Magatinal Saghir", "Republic Of Yemen" ],
    [ "4159", "Ras Safwan", "Republic Of Yemen" ],
    [ "4160", "Balhaf", "Republic Of Yemen" ],
    [ "4162", "Al Mukalla", "Republic Of Yemen" ],
    [ "4163", "Ras Sharmah", "Republic Of Yemen" ],
    [ "4165", "Qishn", "Republic Of Yemen" ],
    [ "4166", "Nishtun", "Republic Of Yemen" ],
    [ "4172", "Hamr An Nafur", "Oman" ],
    [ "4174", "Ghubbat Hashish", "Oman" ],
    [ "4178", "Ras Sheiblah", "Oman" ],
    [ "4180", "Ras Al Hadd", "Oman" ],
    [ "4186A", "Port Sultan Qaboos", "Oman" ],
    [ "4187", "Seeb", "Oman" ],
    [ "4188", "Jazair Suwadi", "Oman" ],
    [ "4190", "Suhar", "Oman" ],
    [ "4191A", "Fujairah", "United Arab Emirates" ],
    [ "4192", "Khawr Fakkan", "United Arab Emirates" ],
    [ "4198", "Khawr Al Quway", "Oman" ],
    [ "4199B", "Bukha", "Oman" ],
    [ "4200", "Saqr Port (Mina Saqr)", "United Arab Emirates" ],
    [ "4201", "Ras Al Khaymah", "United Arab Emirates" ],
    [ "4202", "Al Jazeera Port", "United Arab Emirates" ],
    [ "4203", "Umm Al-Qaiwain", "United Arab Emirates" ],
    [ "4204", "Ajman", "United Arab Emirates" ],
    [ "4205", "Sharjah", "United Arab Emirates" ],
    [ "4206", "Dubai (Al Maktoum Bridge)", "United Arab Emirates" ],
    [ "4206A", "Dubai", "United Arab Emirates" ],
    [ "4207", "Jebel Ali", "United Arab Emirates" ],
    [ "4208", "Khawr Ghanadah", "United Arab Emirates" ],
    [ "4208A", "Khawr Ghurabi", "United Arab Emirates" ],
    [ "4208B", "Khalifa Port", "United Arab Emirates" ],
    [ "4209", "Khawr Sa'Diyat", "United Arab Emirates" ],
    [ "4209A", "Khawr Laffan", "United Arab Emirates" ],
    [ "4210", "Mina Zayid", "United Arab Emirates" ],
    [ "4210A", "Umm Ad Dalkh", "United Arab Emirates" ],
    [ "4210B", "Mina Zayid Approaches", "United Arab Emirates" ],
    [ "4210C", "Sas An Nakhl", "United Arab Emirates" ],
    [ "4210D", "Mina Zayid (New Free Port)", "United Arab Emirates" ],
    [ "4211", "Sir Abu Nu'Ayr", "United Arab Emirates" ],
    [ "4211A", "New Musaffah Channel (Outer)", "United Arab Emirates" ],
    [ "4211B", "New Musaffah Channel (Inner)", "United Arab Emirates" ],
    [ "4212", "Ras Al Ghaf", "United Arab Emirates" ],
    [ "4213", "Abu Al Abyad", "United Arab Emirates" ],
    [ "4213A", "Fasht Al Bazam", "United Arab Emirates" ],
    [ "4214", "Halat Al Mubarraz", "United Arab Emirates" ],
    [ "4215", "Zaqqum Oilfield (Platform Zws)", "United Arab Emirates" ],
    [ "4219", "Zirku", "United Arab Emirates" ],
    [ "4220", "Zirku Terminal", "United Arab Emirates" ],
    [ "4221", "Jazirat Das", "United Arab Emirates" ],
    [ "4221A", "El Bunduq Oilfield", "United Arab Emirates" ],
    [ "4221B", "Ar Ru'Ays (United Arab Emirates)", "United Arab Emirates" ],
    [ "4222", "Jabal Az Zannah", "United Arab Emirates" ],
    [ "4223", "Sir Bani Yas", "United Arab Emirates" ],
    [ "4223A", "Ghasha Light Buoy", "United Arab Emirates" ],
    [ "4224", "Jazirat Arzanah", "United Arab Emirates" ],
    [ "4228", "Jazirat Shuwayhat", "United Arab Emirates" ],
    [ "4229", "Jazirat Dalma", "United Arab Emirates" ],
    [ "4230", "Jazair Al Yasat", "United Arab Emirates" ],
    [ "4231", "Umm Al Hatab", "United Arab Emirates" ],
    [ "4232", "Jazair Ghaghah", "United Arab Emirates" ],
    [ "4233", "Jazirat Shara'Iwah", "Qatar" ],
    [ "4234", "Jazirat Halul", "Qatar" ],
    [ "4235", "Ras Abu Qumayyis", "Qatar" ],
    [ "4235A", "Khawr Al Udayd", "Qatar" ],
    [ "4236", "Mesaieed Outer Channel Entrance", "Qatar" ],
    [ "4237", "Mesaieed (Musay'Id)", "Qatar" ],
    [ "4238", "Al Wakrah", "Qatar" ],
    [ "4239", "Doha (Ad Dawhah)", "Qatar" ],
    [ "4239A", "Al Jazirah Al Aliyah", "Qatar" ],
    [ "4240", "Sumaysimah", "Qatar" ],
    [ "4241", "Khawr Shaqiq", "Qatar" ],
    [ "4242", "Ras Laffan", "Qatar" ],
    [ "4243", "Jabal Al Fuwayrit", "Qatar" ],
    [ "4244", "Ar Ru'Ays", "Qatar" ],
    [ "4246", "Ras 'Ushayrij", "Qatar" ],
    [ "4247", "Nagiyah", "Qatar" ],
    [ "4247B", "Zikrit", "Qatar" ],
    [ "4247C", "Dukhan", "Qatar" ],
    [ "4247D", "Umm Bab", "Qatar" ],
    [ "4247E", "Al Khraij", "Qatar" ],
    [ "4247F", "Ghar Al Buraid", "Qatar" ],
    [ "4248", "Hawar Island (North East)", "Bahrain" ],
    [ "4249", "Az Zallaq", "Bahrain" ],
    [ "4249A", "Mutarid", "Bahrain" ],
    [ "4250", "Ras Al Jamal", "Bahrain" ],
    [ "4250B", "Umm Jalid", "Bahrain" ],
    [ "4250C", "Umais", "Bahrain" ],
    [ "4250D", "Ne Fasht Al Adhm", "Bahrain" ],
    [ "4250E", "Bahrain Approach Buoy", "Bahrain" ],
    [ "4252", "Mina Salman", "Bahrain" ],
    [ "4253", "Mina Al Manama", "Bahrain" ],
    [ "4253A", "Khawr Fasht", "Bahrain" ],
    [ "4253B", "Al Budayyi", "Bahrain" ],
    [ "4253C", "Al Jasser Island", "Bahrain" ],
    [ "4253D", "Qurayyah Pier", "Bahrain" ],
    [ "4253E", "Al Khubar", "Saudi Arabia" ],
    [ "4253F", "Ad Dammam (K.A.A.P.)", "Saudi Arabia" ],
    [ "4253G", "Dawhat At Tarut", "Saudi Arabia" ],
    [ "4254A", "Abu Sa'Fah", "Saudi Arabia" ],
    [ "4254C", "Ju'Aymah Boat Pier", "Saudi Arabia" ],
    [ "4255", "Al Jubayl", "Saudi Arabia" ],
    [ "4255A", "Abu Ali", "Saudi Arabia" ],
    [ "4255B", "Jazirat Al Jurayd", "Saudi Arabia" ],
    [ "4256", "Jazirat Al Arabiyah", "Saudi Arabia" ],
    [ "4257A", "Tanajib Pier", "Saudi Arabia" ],
    [ "4260", "Marjan Oilfield", "Saudi Arabia" ],
    [ "4260A", "Lawhah Oilfield", "Saudi Arabia" ],
    [ "4260D", "Khafji Oilfield", "Saudi Arabia" ],
    [ "4260E", "Hout Oilfield", "Saudi Arabia" ],
    [ "4260G", "Jazirat Umm Al Maradim", "Kuwait" ],
    [ "4261", "Mina Az Zawr (Mina Saud)", "Kuwait" ],
    [ "4261A", "Jazirat Qaru", "Kuwait" ],
    [ "4261B", "Jazirat Kubbar", "Kuwait" ],
    [ "4262", "Mina Al Ahmadi", "Kuwait" ],
    [ "4262A", "Al Fintas", "Kuwait" ],
    [ "4263", "Ash Shuwaykh", "Kuwait" ],
    [ "4264", "Mina Ad Dawhah", "Kuwait" ],
    [ "4265", "Ras Al Barshah (Beacon No. 2)", "Kuwait" ],
    [ "4266", "Hadd Warbah", "Kuwait" ],
    [ "4266A", "Umm Al-Aseed (Beacon No. 15)", "Kuwait" ],
    [ "4267", "Umm Qasr", "Iraq" ],
    [ "4268", "Shatt Al Arab Outer Bar", "Iraq" ],
    [ "4268A", "Al Basrah (Al Bakr) Terminal", "Iraq" ],
    [ "4269", "Al Faw", "Iraq" ],
    [ "4271", "Al Basrah", "Iraq" ],
    [ "4272", "Qarmat Ali Bar", "Iraq" ],
    [ "4273", "Nahr Umr", "Iraq" ],
    [ "4274", "Shafi Creek", "Iraq" ],
    [ "4275", "Odin Point", "Iraq" ],
    [ "4276B", "Khowr-E Musa Approaches", "Iran" ],
    [ "4276A", "Abadan", "Iraq" ],
    [ "4276", "Qurna", "Iraq" ],
    [ "4277", "Khowr-E Musa Bar", "Iran" ],
    [ "4279", "Bandar-E Mahshahr", "Iran" ],
    [ "4280", "Bandar Deylam", "Iran" ],
    [ "4282", "Jazireh-Ye Khark", "Iran" ],
    [ "4283", "Bushehr", "Iran" ],
    [ "4283A", "Halileh", "Iran" ],
    [ "4284", "Bandar-E Ameri", "Iran" ],
    [ "4285", "Lavar-E Saheli", "Iran" ],
    [ "4285A", "Jazirat Al Farisiyah", "Iran" ],
    [ "4285B", "Bordekhun", "Iran" ],
    [ "4286", "Nakhilu", "Iran" ],
    [ "4288", "Asaluyeh", "Iran" ],
    [ "4290", "Jazireh-Ye-Lavan", "Iran" ],
    [ "4293", "Jazireh-Ye Qeys", "Iran" ],
    [ "4295", "Jazireh-Ye Forur", "Iran" ],
    [ "4296", "Jazireh-Ye Sirri", "Iran" ],
    [ "4297", "Bandar-E Lengeh", "Iran" ],
    [ "4298", "Jazireh-Ye Tonb-E Bozorg", "Iran" ],
    [ "4299", "Jazireh-Ye Hengam", "Iran" ],
    [ "4301", "Basa'Idu", "Iran" ],
    [ "4302", "Laft", "Iran" ],
    [ "4303", "Bandar-E Shahid Rajai", "Iran" ],
    [ "4303A", "Bandar-E Shahid Bahonar", "Iran" ],
    [ "4303B", "Bandar Abbas", "Iran" ],
    [ "4307", "Bandar-E Sirik", "Iran" ],
    [ "4308", "Gonari Creek", "Iran" ],
    [ "4309", "Ras Al Kuh", "Iran" ],
    [ "4310", "Khalij-E Jask", "Iran" ],
    [ "4311", "Gugsar", "Iran" ],
    [ "4313", "Ras-E Tang", "Iran" ],
    [ "4314", "Chah Bahar", "Iran" ],
    [ "4315", "Gwatar Bay", "Iran" ],
    [ "4321", "Sonmiani Harbour", "Pakistan" ],
    [ "4322", "Karachi (Entrance)", "Pakistan" ],
    [ "4322A", "Ghizri Creek", "Pakistan" ],
    [ "4322C", "Hasan Point", "Pakistan" ],
    [ "4322E", "Jhari Creek", "Pakistan" ],
    [ "4323", "Hajambro Creek", "Pakistan" ],
    [ "4324", "Sir Mouth", "Pakistan" ],
    [ "4325", "Kori Creek Entrance", "India West Coast" ],
    [ "4340A", "Diu Head", "India West Coast" ],
    [ "4345", "Piram Island", "India West Coast" ],
    [ "4348", "Khambhat (Cambay)", "India West Coast" ],
    [ "4351", "Mehegam", "India West Coast" ],
    [ "4352", "Bharuch", "India West Coast" ],
    [ "4353A", "Hazira", "India West Coast" ],
    [ "4353", "Suvali", "India West Coast" ],
    [ "4356A", "Tarapur", "India West Coast" ],
    [ "4361", "Thana", "India West Coast" ],
    [ "4371", "Angria Bank", "India West Coast" ],
    [ "4399", "Cherbaniani Reef", "Lakshadweep" ],
    [ "4400", "Kadmat", "Lakshadweep" ],
    [ "4400A", "Androth Island", "Lakshadweep" ],
    [ "4402", "Ihavandhoo", "Maldive Islands" ],
    [ "4404", "Goidhoo Atoll", "Maldive Islands" ],
    [ "4404A", "Girifushi", "Maldive Islands" ],
    [ "4405", "Male", "Maldive Islands" ],
    [ "4406", "Vattaru", "Maldive Islands" ],
    [ "4407", "Hadhdunmathi Atoll", "Maldive Islands" ],
    [ "4408", "North Huvadhu", "Maldive Islands" ],
    [ "4410", "Addoo Atoll", "Maldive Islands" ],
    [ "4412", "Salomon Islands", "Chagos Archipelago" ],
    [ "4413", "Peros Banhos", "Chagos Archipelago" ],
    [ "4418", "Eagle Island, Chagos Archipelago", "Chagos Archipelago" ],
    [ "4419", "Egmont Islands", "Chagos Archipelago" ],
    [ "4420", "Diego Garcia (Observatory Point)", "Chagos Archipelago" ],
    [ "4427", "Kalpitiya", "Sri Lanka" ],
    [ "4428", "Colombo", "Sri Lanka" ],
    [ "4430", "Galle", "Sri Lanka" ],
    [ "4431", "Mirissa", "Sri Lanka" ],
    [ "4431A", "Tangalla", "Sri Lanka" ],
    [ "4432", "Hambantota", "Sri Lanka" ],
    [ "4435", "Batticaloa Roads", "Sri Lanka" ],
    [ "4439", "Point Pedro", "Sri Lanka" ],
    [ "4440", "Jaffna", "Sri Lanka" ],
    [ "4441", "Kayts Lagoon", "Sri Lanka" ],
    [ "4443", "Delft Island", "Sri Lanka" ],
    [ "4444", "Kachchaitivu", "Sri Lanka" ],
    [ "4446", "Kottaippattanam", "India East Coast" ],
    [ "4453", "Pulicat", "India East Coast" ],
    [ "4455", "Vadarevu", "India East Coast" ],
    [ "4456", "Nizampatam", "India East Coast" ],
    [ "4457", "Machilipatnam", "India East Coast" ],
    [ "4461", "Kakinada", "India East Coast" ],
    [ "4471", "Chilka Mouth", "India East Coast" ],
    [ "4473", "Devi River Entrance", "India East Coast" ],
    [ "4475", "Shortt Island", "India East Coast" ],
    [ "4478", "Burhabalang River Entrance", "India East Coast" ],
    [ "4480", "The Sandheads", "India East Coast" ],
    [ "4482", "Gangra Semaphore", "India East Coast" ],
    [ "4482A", "Haldia", "India East Coast" ],
    [ "4483", "Balari Semaphore", "India East Coast" ],
    [ "4485", "Hugli Point Semaphore", "India East Coast" ],
    [ "4486", "Moyapur", "India East Coast" ],
    [ "4487", "Akra Semaphore", "India East Coast" ],
    [ "4490", "Sandhead", "India East Coast" ],
    [ "4491", "Canning Town", "India East Coast" ],
    [ "4495", "Jefford Point", "Bangladesh" ],
    [ "4496", "Pussur River Entrance", "Bangladesh" ],
    [ "4497", "Sundarkota Reach", "Bangladesh" ],
    [ "4498A", "Mongla", "Bangladesh" ],
    [ "4498", "Jayman Reach", "Bangladesh" ],
    [ "4499", "Chalna Reach", "Bangladesh" ],
    [ "4501", "Tiger Point", "Bangladesh" ],
    [ "4502", "Dhulasar", "Bangladesh" ],
    [ "4503", "Rabnabad Channel (Patua)", "Bangladesh" ],
    [ "4505", "D'Apres Shoal", "Bangladesh" ],
    [ "4506", "Hatia Bar", "Bangladesh" ],
    [ "4507", "Sandwip Island", "Bangladesh" ],
    [ "4507A", "Ilsa Ghat", "Bangladesh" ],
    [ "4508", "Chandpur", "Bangladesh" ],
    [ "4509", "Narayanganj", "Bangladesh" ],
    [ "4510", "Norman'S Point", "Bangladesh" ],
    [ "4511", "Khal No.18", "Bangladesh" ],
    [ "4512", "Chittagong", "Bangladesh" ],
    [ "4514", "Kutubdia Island", "Bangladesh" ],
    [ "4515", "Cox'S Bazar", "Bangladesh" ],
    [ "4517", "St. Martin'S Island", "Bangladesh" ],
    [ "4520", "Sittwe", "Burma" ],
    [ "4525", "Kyaukpyu", "Burma" ],
    [ "4526", "Searle Point", "Burma" ],
    [ "4529", "Sagu Kyun", "Burma" ],
    [ "4532", "Andrew Bay", "Burma" ],
    [ "4534", "Gwa Bay", "Burma" ],
    [ "4536", "Chaungtha Kyun", "Burma" ],
    [ "4537", "Goyangyi Kyun", "Burma" ],
    [ "4540", "Chaunggwa", "Burma" ],
    [ "4541", "Bassein", "Burma" ],
    [ "4542", "Pyinsalu", "Burma" ],
    [ "4543", "Ama", "Burma" ],
    [ "4544", "Pymbong Beacon", "Burma" ],
    [ "4545", "Tinmahlwe", "Burma" ],
    [ "4545A", "Thandeik", "Burma" ],
    [ "4546", "Dagon (Old Light)", "Burma" ],
    [ "4547", "Sin Min Point (Elephant Point)", "Burma" ],
    [ "4548", "Yangon (Rangoon)", "Burma" ],
    [ "4552", "Kyaikkami (Amherst)", "Burma" ],
    [ "4553", "Feronia Crossing", "Burma" ],
    [ "4555", "Moulmein", "Burma" ],
    [ "4556", "Double Island", "Burma" ],
    [ "4558", "Bentinck Sound", "Burma" ],
    [ "4559", "Wa Kyun (Stag Island)", "Burma" ],
    [ "4560", "Sidaw Point", "Burma" ],
    [ "4561", "Ye Town", "Burma" ],
    [ "4562", "Heinze Chaung", "Burma" ],
    [ "4562A", "Ne Of North Ledge", "Burma" ],
    [ "4563", "Heinze Bok (Long Island)", "Burma" ],
    [ "4566", "Myinkwa-Aw", "Burma" ],
    [ "4568", "Sinbyubyin", "Burma" ],
    [ "4569", "Tavoy", "Burma" ],
    [ "4571", "Mali Kyun (Fisher Bay)", "Burma" ],
    [ "4573", "Padaw-Aw", "Burma" ],
    [ "4576", "Port Maria", "Burma" ],
    [ "4579", "Thar Myar Ami", "Burma" ],
    [ "4580", "Jack Island", "Burma" ],
    [ "4581", "Myauk Gaung Island", "Burma" ],
    [ "4582", "Thatchaung", "Burma" ],
    [ "4584", "Pawei Kyun", "Burma" ],
    [ "4585", "Ka Mar Island", "Burma" ],
    [ "4587", "Kyunn Tann Shey (Bulet-Aw)", "Burma" ],
    [ "4589", "Hastings Harbour", "Burma" ],
    [ "4590", "Za Det Gyi Island (South Bay)", "Burma" ],
    [ "4592", "Pulau Besin", "Burma" ],
    [ "4595", "Mingalakyun", "Coco Group" ],
    [ "4597", "Temple Sound", "Andaman Islands" ],
    [ "4598", "Hoare Bay", "Andaman Islands" ],
    [ "4600", "Port Anson", "Andaman Islands" ],
    [ "4602", "Boat Island", "Andaman Islands" ],
    [ "4604", "Cleugh Passage", "Andaman Islands" ],
    [ "4605", "Port Cornwallis", "Andaman Islands" ],
    [ "4606", "Stewart Sound", "Andaman Islands" ],
    [ "4607", "Long Island", "Andaman Islands" ],
    [ "4608", "Strait Island", "Andaman Islands" ],
    [ "4609", "Jalebar", "Andaman Islands" ],
    [ "4612", "Cinque Islands", "Andaman Islands" ],
    [ "4615", "Little Andaman", "Andaman Islands" ],
    [ "4620", "Dring Harbour", "Nicobar Islands" ],
    [ "4620A", "Expedition Harbour", "Nicobar Islands" ],
    [ "4621", "Nancowry Harbour", "Nicobar Islands" ],
    [ "4625", "South (Galatea) Bay", "Nicobar Islands" ],
    [ "4632", "Ko Surin", "Thailand West Coast" ],
    [ "4634", "Chang Ko Phra Thong", "Thailand West Coast" ],
    [ "4636", "Ko Miang", "Thailand West Coast" ],
    [ "4637", "Ao Kaulak", "Thailand West Coast" ],
    [ "4639", "Ko Taphao Noi (Phuket)", "Thailand West Coast" ],
    [ "4645", "Ko Sukon", "Thailand West Coast" ],
    [ "4646", "Ko Phetra", "Thailand West Coast" ],
    [ "4648", "Ko Don", "Thailand West Coast" ],
    [ "4649", "Ko Lela", "Thailand West Coast" ],
    [ "4650", "Ko Butang", "Thailand West Coast" ],
    [ "4654", "Pelabuhan Kuah", "Peninsular Malaysia West Coast" ],
    [ "4655", "Pulau Beras Basah", "Peninsular Malaysia West Coast" ],
    [ "4656", "Teluk Datai", "Peninsular Malaysia West Coast" ],
    [ "4657", "Teluk Ewa", "Peninsular Malaysia West Coast" ],
    [ "4658A", "Sungai Kedah", "Peninsular Malaysia West Coast" ],
    [ "4658", "Kuala Perlis", "Peninsular Malaysia West Coast" ],
    [ "4659", "Pulau Bidan", "Peninsular Malaysia West Coast" ],
    [ "4660", "Tanjung Dawai", "Peninsular Malaysia West Coast" ],
    [ "4663", "Pinang (Georgetown)", "Peninsular Malaysia West Coast" ],
    [ "4664", "Pulau Rimau", "Peninsular Malaysia West Coast" ],
    [ "4670", "Port Weld", "Peninsular Malaysia West Coast" ],
    [ "4674", "Lumut Pier", "Peninsular Malaysia West Coast" ],
    [ "4675", "Pulau Katak", "Peninsular Malaysia West Coast" ],
    [ "4676", "Pulau Jarak", "Peninsular Malaysia West Coast" ],
    [ "4678", "Bagan Datuk", "Peninsular Malaysia West Coast" ],
    [ "4679", "Teluk Intan", "Peninsular Malaysia West Coast" ],
    [ "4680", "Kuala Bernam", "Peninsular Malaysia West Coast" ],
    [ "4683", "Kuala Selangor", "Peninsular Malaysia West Coast" ],
    [ "4684", "Pulau Angsa", "Peninsular Malaysia West Coast" ],
    [ "4686", "Pelabuhan Klang", "Peninsular Malaysia West Coast" ],
    [ "4688", "Pintu Gedong", "Peninsular Malaysia West Coast" ],
    [ "4695", "Port Dickson", "Peninsular Malaysia West Coast" ],
    [ "4696", "Cape Rachado", "Peninsular Malaysia West Coast" ],
    [ "4698", "Tanjung Keling", "Peninsular Malaysia West Coast" ],
    [ "4699", "Melaka", "Peninsular Malaysia West Coast" ],
    [ "4701", "Pulau Undan", "Peninsular Malaysia West Coast" ],
    [ "4702", "Muar", "Peninsular Malaysia West Coast" ],
    [ "4703", "Parit Jawa", "Peninsular Malaysia West Coast" ],
    [ "4703A", "Tanjung Tohor", "Peninsular Malaysia West Coast" ],
    [ "4704", "Kuala Batu Pahat", "Peninsular Malaysia West Coast" ],
    [ "4705", "Tanjung Laboh", "Peninsular Malaysia West Coast" ],
    [ "4707A", "Kukup", "Peninsular Malaysia West Coast" ],
    [ "4713A", "Johor Bahru (East Side Of Causeway)", "Peninsular Malaysia South Coast" ],
    [ "4730", "Teluk Sengat", "Peninsular Malaysia South Coast" ],
    [ "4731", "Tanjung Surat", "Peninsular Malaysia South Coast" ],
    [ "4733", "Tanjung Serindet", "Peninsular Malaysia South Coast" ],
    [ "4734", "Sungai Belungkor", "Peninsular Malaysia South Coast" ],
    [ "4735", "Tanjung Pengelih", "Peninsular Malaysia South Coast" ],
    [ "4737", "Ramunia Jetty", "Peninsular Malaysia South Coast" ],
    [ "4738", "Horsburgh Lighthouse", "Singapore Strait" ],
    [ "4743", "Selat Kijang Entrance (North)", "Riau Kepulauan" ],
    [ "4746A", "Pulau Sambu", "Riau Kepulauan" ],
    [ "4746B", "Sekupang", "Riau Kepulauan" ],
    [ "4829", "Teluk Bayur (Emma Haven)", "Sumatera South West Coast" ],
    [ "4848", "Sungai Palembang (Outer Bar)", "Sumatera East Coast" ],
    [ "4879", "Tanjung Penawar", "Peninsular Malaysia East Coast" ],
    [ "4881", "Tanjung Sedili Kechil", "Peninsular Malaysia East Coast" ],
    [ "4886", "Pulau Babi Besar", "Peninsular Malaysia East Coast" ],
    [ "4889", "Teluk Tekek", "Peninsular Malaysia East Coast" ],
    [ "4892", "Kuala Rompin", "Peninsular Malaysia East Coast" ],
    [ "4894", "Pulau Berhala", "Peninsular Malaysia East Coast" ],
    [ "4895", "Kuala Pahang", "Peninsular Malaysia East Coast" ],
    [ "4896", "Kuantan", "Peninsular Malaysia East Coast" ],
    [ "4896A", "Pelabuhan Kuantan", "Peninsular Malaysia East Coast" ],
    [ "4897", "Sungai Kemaman", "Peninsular Malaysia East Coast" ],
    [ "4899", "Kuala Dungun", "Peninsular Malaysia East Coast" ],
    [ "4901", "Chendering", "Peninsular Malaysia East Coast" ],
    [ "4902", "Kuala Terengganu", "Peninsular Malaysia East Coast" ],
    [ "4904", "Setiu", "Peninsular Malaysia East Coast" ],
    [ "4907", "Sungai Besut", "Peninsular Malaysia East Coast" ],
    [ "4910", "Tumpat", "Peninsular Malaysia East Coast" ],
    [ "4911", "Geting", "Peninsular Malaysia East Coast" ],
    [ "4917", "North Danger Reef", "Central China Sea Reefs" ],
    [ "4918", "Scarborough Shoal", "Central China Sea Reefs" ],
    [ "4922", "Eran Bay", "Philippine Islands" ],
    [ "4924", "Pankol", "Philippine Islands" ],
    [ "4925", "Paly Island", "Philippine Islands" ],
    [ "4927", "Island Bay", "Philippine Islands" ],
    [ "4929", "Linapakan Island", "Philippine Islands" ],
    [ "4931", "Coron", "Philippine Islands" ],
    [ "4932", "Cuyo Island", "Philippine Islands" ],
    [ "4934", "Apo Island", "Philippine Islands" ],
    [ "4937", "Paluan", "Philippine Islands" ],
    [ "4939", "Mansalay", "Philippine Islands" ],
    [ "4940", "Port Balanacan", "Philippine Islands" ],
    [ "4941", "Maestre De Campo Island", "Philippine Islands" ],
    [ "4943", "Romblon Island", "Philippine Islands" ],
    [ "4945", "Tibiao", "Philippine Islands" ],
    [ "4946", "Anini-Y", "Philippine Islands" ],
    [ "4948", "Banate", "Philippine Islands" ],
    [ "4949", "Estancia", "Philippine Islands" ],
    [ "4952", "Cadiz", "Philippine Islands" ],
    [ "4953", "Bacolod", "Philippine Islands" ],
    [ "4954", "Himamaylan", "Philippine Islands" ],
    [ "4955", "Campomanes Bay", "Philippine Islands" ],
    [ "4956", "Bonbonon", "Philippine Islands" ],
    [ "4958", "San Carlos", "Philippine Islands" ],
    [ "4959", "Bantayan Island", "Philippine Islands" ],
    [ "4960", "Balamban Bay", "Philippine Islands" ],
    [ "4961", "Moalbual", "Philippine Islands" ],
    [ "4962", "Bolhoon", "Philippine Islands" ],
    [ "4963", "Cebu", "Philippine Islands" ],
    [ "4964", "Bogo Bay", "Philippine Islands" ],
    [ "4966", "Garcia Hernandez", "Philippine Islands" ],
    [ "4968", "Larena", "Philippine Islands" ],
    [ "4969", "Cataingan", "Philippine Islands" ],
    [ "4970", "Nin Bay", "Philippine Islands" ],
    [ "4971", "Port Barrera", "Philippine Islands" ],
    [ "4972", "San Pascual", "Philippine Islands" ],
    [ "4974", "Butag Bay", "Philippine Islands" ],
    [ "4975", "Bagatao Island", "Philippine Islands" ],
    [ "4976", "Sorsogon", "Philippine Islands" ],
    [ "4978", "Pasacao", "Philippine Islands" ],
    [ "4979", "Guinayangan", "Philippine Islands" ],
    [ "4981", "Aguasa Bay", "Philippine Islands" ],
    [ "4985", "Port Tilic", "Philippine Islands" ],
    [ "4987", "Manila", "Philippine Islands" ],
    [ "4990", "Port Masinloc", "Philippine Islands" ],
    [ "5004", "Aparri", "Philippine Islands" ],
    [ "5007", "Basco", "Philippine Islands" ],
    [ "5009", "Babuyan Island", "Philippine Islands" ],
    [ "5013", "Port San Pio Quinto", "Philippine Islands" ],
    [ "5020", "Baler Bay", "Philippine Islands" ],
    [ "5026", "Atimonan", "Philippine Islands" ],
    [ "5027", "Port Jose Panganiban", "Philippine Islands" ],
    [ "5028", "Kabgan Island", "Philippine Islands" ],
    [ "5030", "Port Anajao", "Philippine Islands" ],
    [ "5032", "Legaspi", "Philippine Islands" ],
    [ "5039", "Laoang", "Philippine Islands" ],
    [ "5040", "Hilaban Island", "Philippine Islands" ],
    [ "5046", "Liloan", "Philippine Islands" ],
    [ "5048", "Maasin", "Philippine Islands" ],
    [ "5049", "Baybay", "Philippine Islands" ],
    [ "5050", "Palompon", "Philippine Islands" ],
    [ "5052", "Puerto Princesa", "Philippine Islands" ],
    [ "5053", "Port Pilar", "Philippine Islands" ],
    [ "5056", "Tandag", "Philippine Islands" ],
    [ "5057", "Hinatuan", "Philippine Islands" ],
    [ "5059", "Caraga", "Philippine Islands" ],
    [ "5061", "Sigaboy", "Philippine Islands" ],
    [ "5062", "Davao", "Philippine Islands" ],
    [ "5064", "Port Lebak", "Philippine Islands" ],
    [ "5065", "Pollok Harbour", "Philippine Islands" ],
    [ "5067", "Ticauan Point", "Philippine Islands" ],
    [ "5068", "Zamboanga", "Philippine Islands" ],
    [ "5069", "Sibuco Bay", "Philippine Islands" ],
    [ "5071", "Dapitan", "Philippine Islands" ],
    [ "5072", "Plaridel", "Philippine Islands" ],
    [ "5073", "Ozamiz", "Philippine Islands" ],
    [ "5074", "Iligan", "Philippine Islands" ],
    [ "5075", "Cagayan De Oro", "Philippine Islands" ],
    [ "5076", "Mambajao", "Philippine Islands" ],
    [ "5077", "Nasipit Harbour", "Philippine Islands" ],
    [ "5088", "Port Siasi", "Sulu Archipelago" ],
    [ "5099", "Tawau", "Sabah" ],
    [ "5101", "Pakalangan", "Sabah" ],
    [ "5103", "Semporna", "Sabah" ],
    [ "5105", "Kunak", "Sabah" ],
    [ "5107", "Lahad Datu", "Sabah" ],
    [ "5108", "Bakapit", "Sabah" ],
    [ "5111", "Pulau Tambisan", "Sabah" ],
    [ "5113", "Kinabatangan", "Sabah" ],
    [ "5115", "Sandakan", "Sabah" ],
    [ "5117", "Labuk Bay", "Sabah" ],
    [ "5118", "Pulau Lankayan", "Sabah" ],
    [ "5121", "Pulau Tigabu", "Sabah" ],
    [ "5122", "Pulau Banggi", "Sabah" ],
    [ "5125", "Kudat", "Sabah" ],
    [ "5127", "Pulau Mantanani Besar", "Sabah" ],
    [ "5130", "Pulau Mangalum", "Sabah" ],
    [ "5132", "Kota Kinabalu", "Sabah" ],
    [ "5133", "Kuala Papar", "Sabah" ],
    [ "5134", "Tiga", "Sabah" ],
    [ "5137", "Labuan (Victoria Harbour)", "Sabah" ],
    [ "5138", "Weston", "Sabah" ],
    [ "5139", "Sipitang", "Sabah" ],
    [ "5139A", "Kuala Lawas", "Sarawak" ],
    [ "5139B", "Pasar Lawas", "Sarawak" ],
    [ "5140", "Punang", "Sarawak" ],
    [ "5141", "Kuala Limbang", "Sarawak" ],
    [ "5141A", "Bandar Limbang", "Sarawak" ],
    [ "5141B", "Dato Gandi", "Brunei" ],
    [ "5142", "Tanjung Ujong Sapoh", "Brunei" ],
    [ "5143", "Muara", "Brunei" ],
    [ "5144", "Lumut", "Brunei" ],
    [ "5145", "Seria", "Brunei" ],
    [ "5145A", "Kuala Belait", "Brunei" ],
    [ "5146", "Kuala Baram", "Sarawak" ],
    [ "5147", "Miri", "Sarawak" ],
    [ "5148", "Kuala Niah", "Sarawak" ],
    [ "5149", "Kuala Similajau", "Sarawak" ],
    [ "5150", "Kuala Bintulu", "Sarawak" ],
    [ "5151", "Kuala Tatau", "Sarawak" ],
    [ "5152", "Kuala Balingian", "Sarawak" ],
    [ "5153", "Kuala Mukah", "Sarawak" ],
    [ "5153B", "Kuala Oya", "Sarawak" ],
    [ "5154", "Kuala Igan", "Sarawak" ],
    [ "5155", "Kuala Matu", "Sarawak" ],
    [ "5155A", "Daro", "Sarawak" ],
    [ "5155C", "Singat", "Sarawak" ],
    [ "5155B", "Tanjung Sidau", "Sarawak" ],
    [ "5156", "Kuala Paloh", "Sarawak" ],
    [ "5156A", "Tanjung Bekakong", "Sarawak" ],
    [ "5156B", "Kampung Sepenah", "Sarawak" ],
    [ "5156C", "Tanjung Kamis", "Sarawak" ],
    [ "5157", "Kuala Rajang", "Sarawak" ],
    [ "5158", "Sarikei", "Sarawak" ],
    [ "5158A", "Leba An", "Sarawak" ],
    [ "5159", "Sibu", "Sarawak" ],
    [ "5159A", "Kanowit", "Sarawak" ],
    [ "5160", "Kabong", "Sarawak" ],
    [ "5162", "Pusa", "Sarawak" ],
    [ "5164", "Triso Darat", "Sarawak" ],
    [ "5167", "Kuala Sadong", "Sarawak" ],
    [ "5168", "Sungai Ensengie", "Sarawak" ],
    [ "5169", "Simunjan", "Sarawak" ],
    [ "5170", "Pending", "Sarawak" ],
    [ "5170A", "Ulu Kuap", "Sarawak" ],
    [ "5171A", "Batu Kitang", "Sarawak" ],
    [ "5172", "Sungai Sarawak (Pulau Lakei)", "Sarawak" ],
    [ "5173", "Santubong", "Sarawak" ],
    [ "5174", "Pulau Satang Besar", "Sarawak" ],
    [ "5174A", "Kuala Lundu", "Sarawak" ],
    [ "5174B", "Pasar Lundu", "Sarawak" ],
    [ "5175", "Sematan", "Sarawak" ],
    [ "5176", "Tanjung Serabang", "Sarawak" ],
    [ "5177", "Selat Peninting", "Tudjuh Kepulauan" ],
    [ "5214", "Sungai Barito (Outer Bar)", "Kalimantan" ],
    [ "5228", "Balikpapan", "Kalimantan" ],
    [ "5233", "Sungai Kutei (Muara Bayur)", "Kalimantan" ],
    [ "5237A", "Bontang", "Kalimantan" ],
    [ "5237B", "Lhotuan Approaches", "Kalimantan" ],
    [ "5321", "Bitung", "Sulawesi East Coast" ],
    [ "5341A", "Pulau Pari", "Jawa North Coast" ],
    [ "5365", "Surabaya (Tanjungperak)", "Jawa East Coast" ],
    [ "5367", "Pulau Karangjamuang", "Jawa East Coast" ],
    [ "5382", "Benoa", "Bali" ],
    [ "5435", "Bandanaira", "Sermata Eilanden" ],
    [ "5549", "Omati", "Papua New Guinea" ],
    [ "5553", "Kerema", "Papua New Guinea" ],
    [ "5566", "Samarai Island", "Papua New Guinea" ],
    [ "5571", "Duchateau Islands", "Louisiade Archipelago" ],
    [ "5575", "Hati Lawi Harbour", "Louisiade Archipelago" ],
    [ "5599", "Dreger Harbour", "Papua New Guinea" ],
    [ "5618", "Talasea", "Bismarck Archipelago" ],
    [ "5636", "Choiseul Bay", "Solomon Islands" ],
    [ "5636A", "Sasamungga", "Solomon Islands" ],
    [ "5639", "Sikopo Island", "Solomon Islands" ],
    [ "5639A", "Maleivona Island", "Solomon Islands" ],
    [ "5646", "Gizo Harbour", "Solomon Islands" ],
    [ "5647", "Blackett Strait", "Solomon Islands" ],
    [ "5648A", "Roviana Lagoon (Mbaraulu)", "Solomon Islands" ],
    [ "5649", "Viru Harbour", "Solomon Islands" ],
    [ "5651", "Marovo Lagoon (Karunohu Island)", "Solomon Islands" ],
    [ "5652", "Monggo Passage", "Solomon Islands" ],
    [ "5654", "Lolomo Passage", "Solomon Islands" ],
    [ "5655", "Lever Harbour", "Solomon Islands" ],
    [ "5656", "Hathorn Sound", "Solomon Islands" ],
    [ "5667A", "Lambi Bay", "Solomon Islands" ],
    [ "5657", "Yandina", "Solomon Islands" ],
    [ "5669", "Nughu Island", "Solomon Islands" ],
    [ "5671", "Mbungana Island", "Solomon Islands" ],
    [ "5678", "Thousand Ships Bay", "Solomon Islands" ],
    [ "5682", "Malaghara Island", "Solomon Islands" ],
    [ "5696", "Kwai Harbour", "Solomon Islands" ],
    [ "5702", "Uki Ni Masi Island", "Solomon Islands" ],
    [ "5713", "Ndendo Island", "Santa Cruz Islands" ],
    [ "5721", "Luganville (Santo)", "Vanuatu" ],
    [ "5727", "Port Sandwich", "Vanuatu" ],
    [ "5729", "Ringdove Bay", "Vanuatu" ],
    [ "5731", "Sulva Bay", "Vanuatu" ],
    [ "5732", "Port Vila", "Vanuatu" ],
    [ "5759", "Noumea", "New Caledonia" ],
    [ "5819", "Round Island", "Australia" ],
    [ "5828", "Bampfield Head", "Australia" ],
    [ "5834", "Herald Camp", "Australia" ],
    [ "5839", "Possession Island", "Australia" ],
    [ "5847", "Frederick Point", "Australia" ],
    [ "5859", "Hannibal Island", "Australia East Coast" ],
    [ "5865", "Piper Island", "Australia East Coast" ],
    [ "5867", "Restoration Island", "Australia East Coast" ],
    [ "5891", "Low Wooded Isle", "Australia East Coast" ],
    [ "5899", "Bailay Creek", "Australia East Coast" ],
    [ "5916", "Clump Point", "Australia East Coast" ],
    [ "5936", "Double Bay", "Australia East Coast" ],
    [ "5938", "Molle Island", "Australia East Coast" ],
    [ "5946", "Carlisle Island", "Australia East Coast" ],
    [ "5948", "St. Bees Island", "Australia East Coast" ],
    [ "5949", "Scawfell Island", "Australia East Coast" ],
    [ "5958", "Flock Pigeon Island", "Australia East Coast" ],
    [ "5977", "Clews Point", "Australia East Coast" ],
    [ "5979", "Lady Elliot Island", "Australia East Coast" ],
    [ "6007", "Point Danger", "Australia East Coast" ],
    [ "6030", "Salamander Bay", "Australia East Coast" ],
    [ "6087", "Stack Island", "Tasmania" ],
    [ "6088", "Three Hummock Island", "Tasmania" ],
    [ "6112", "Eddystone Point", "Tasmania" ],
    [ "6120", "Parsons Bay", "Tasmania" ],
    [ "6121", "Impression Bay", "Tasmania" ],
    [ "6130", "Cape Sorell (Pilot Bay)", "Tasmania" ],
    [ "6132", "Pieman River", "Tasmania" ],
    [ "6147", "Kingston", "Australia South Coast" ],
    [ "6153", "Kingscote", "Australia South Coast" ],
    [ "6154", "American River", "Australia South Coast" ],
    [ "6173", "Stenhouse Bay", "Australia South Coast" ],
    [ "6246", "Serrurier (Long) Island", "Australia North Coast" ],
    [ "6248", "Large Islet", "Australia North Coast" ],
    [ "6263", "Lagrange Bay", "Australia North Coast" ],
    [ "6268", "Red Bluff", "Australia North Coast" ],
    [ "6275", "Karrakatta Bay", "Australia North Coast" ],
    [ "6290", "Browse Island", "Australia North Coast" ],
    [ "6300A", "Cassini Island", "Australia North Coast" ],
    [ "6320", "Tapa Bay", "Australia North Coast" ],
    [ "6429A", "Mahanga", "New Zealand North Island" ],
    [ "6442", "Makara Beach", "New Zealand North Island" ],
    [ "6485", "Cape Campbell", "New Zealand South Island" ],
    [ "6497", "Port Chalmers", "New Zealand South Island" ],
    [ "6500", "Nugget Point", "New Zealand South Island" ],
    [ "6502", "Waipapa Point", "New Zealand South Island" ],
    [ "6506", "Colac Bay (Oraka)", "New Zealand South Island" ],
    [ "6524", "Greymouth", "New Zealand South Island" ],
    [ "6544", "Isla De Pascua (Hanga Piko)", "Pacific Ocean Islands" ],
    [ "6553", "Iles Gambier (Rikitea)", "Tuamoto (Low) Archipelago" ],
    [ "6580", "Papeete", "Iles De La Societe" ],
    [ "6590", "Hiva Oa", "Iles Marquises" ],
    [ "6598", "Rarotonga (Avarua Harbour)", "Cook Islands South" ],
    [ "6603", "Aitutaki", "Cook Islands South" ],
    [ "6604", "Niue Island", "Cook Islands South" ],
    [ "6605", "Suwarrow Island", "Cook Islands North" ],
    [ "6606", "Tongareva (Penrhyn Island)", "Cook Islands North" ],
    [ "6607", "Manihiki", "Cook Islands North" ],
    [ "6610", "Pukapuka", "Cook Islands North" ],
    [ "6616", "Jarvis Island", "Line Islands" ],
    [ "6617", "Christmas Island", "Line Islands" ],
    [ "6618", "Fanning Island", "Line Islands" ],
    [ "6620", "Palmyra Island", "Line Islands" ],
    [ "6649", "French Frigate Shoals", "Hawaiian Islands" ],
    [ "6654", "Sand Island", "Hawaiian Islands" ],
    [ "6660", "Nuku'Alofa", "Tonga Islands" ],
    [ "6664", "Nomuka", "Tonga Islands" ],
    [ "6666", "Lifuka Island (Pangai)", "Tonga Islands" ],
    [ "6671", "Neiafu", "Tonga Islands" ],
    [ "6683", "Mulifanua", "Samoa Islands" ],
    [ "6697", "Hull Island", "Phoenix Islands" ],
    [ "6701", "Canton Island", "Phoenix Islands" ],
    [ "6705", "Suva Harbour", "Fiji Islands" ],
    [ "6706", "Rukua", "Fiji Islands" ],
    [ "6708", "Manuqila Bay", "Fiji Islands" ],
    [ "6708A", "Nabukeru", "Fiji Islands" ],
    [ "6708B", "Vatia Wharf", "Fiji Islands" ],
    [ "6709", "Manava Cay", "Fiji Islands" ],
    [ "6710", "Ellington Wharf", "Fiji Islands" ],
    [ "6710A", "Nanukuloa", "Fiji Islands" ],
    [ "6710B", "Naigani", "Fiji Islands" ],
    [ "6711", "Tailevu", "Fiji Islands" ],
    [ "6711A", "Leleuvia Island", "Fiji Islands" ],
    [ "6713", "Levuka", "Fiji Islands" ],
    [ "6718", "Yadua Island", "Fiji Islands" ],
    [ "6718A", "Koroinasolo Inlet", "Fiji Islands" ],
    [ "6718B", "Dreketi", "Fiji Islands" ],
    [ "6719A", "Naduri", "Fiji Islands" ],
    [ "6720", "Malau", "Fiji Islands" ],
    [ "6721", "Visonggo", "Fiji Islands" ],
    [ "6722", "Natewa", "Fiji Islands" ],
    [ "6724", "Nakama Creek", "Fiji Islands" ],
    [ "6725", "Muanicula", "Fiji Islands" ],
    [ "6726", "Veitalacagi Point", "Fiji Islands" ],
    [ "6730A", "Wainiyabia", "Fiji Islands" ],
    [ "6740", "Rotuma Island", "Fiji Islands" ],
    [ "6744", "Funafuti", "Tuvalu" ],
    [ "6750", "Arorae", "Kiribati" ],
    [ "6756", "Abemama", "Kiribati" ],
    [ "6758", "Tarawa (Bairiki)", "Kiribati" ],
    [ "6759", "Tarawa (Betio)", "Kiribati" ],
    [ "6760", "Abaiang Atoll", "Kiribati" ],
    [ "6763", "Banaba", "Kiribati" ],
    [ "6764", "Nauru", "Kiribati" ],
    [ "6768", "Djarrit", "Marshall Islands" ],
    [ "6795", "Pohnpei Harbour", "Caroline Islands" ],
    [ "6796", "Kapingamarangi", "Caroline Islands" ],
    [ "6798", "Nomoi Islands", "Caroline Islands" ],
    [ "6804", "Puluwat Island", "Caroline Islands" ],
    [ "6815", "Yap Island", "Caroline Islands" ],
    [ "6820", "Malakal Harbour", "Palau Islands" ],
    [ "6827", "Guam", "Marianas Islands" ],
    [ "6830", "Saipan", "Marianas Islands" ],
    [ "6876", "Ko Lak (Prachuap Khiri Khan)", "Thailand" ],
    [ "6878", "Hua Hin", "Thailand" ],
    [ "6882", "Bangkok Bar", "Thailand" ],
    [ "6886", "Ko Si Chang", "Thailand" ],
    [ "6909", "Hon Rai", "Vietnam" ],
    [ "6913", "Cua Song Bai Hap (Off)", "Vietnam" ],
    [ "6979", "Dong Hoi", "Vietnam" ],
    [ "6983", "Cua Hoi", "Vietnam" ],
    [ "7003", "Ile Bach Long Vi", "Vietnam" ],
    [ "7043", "Mulan Tou (Hainan Head)", "China" ],
    [ "7080", "Huangpu (Whampoa Dock)", "China" ],
    [ "7086", "Wailingding Dao", "China" ],
    [ "7092", "Tsim Bei Tsui", "China" ],
    [ "7093", "Tap Shek Kok", "China" ],
    [ "7094", "Tsing Shan Wan", "China" ],
    [ "7094A", "Lok On Pai", "China" ],
    [ "7097", "Tai O", "China" ],
    [ "7099", "Chi Ma Wan", "China" ],
    [ "7102", "Tsing Yi", "China" ],
    [ "7102A", "Tsuen Wan", "China" ],
    [ "7106", "Yung Shue Wan", "China" ],
    [ "7109", "Heung Kong Tsai Wan (Aberdeen)", "China" ],
    [ "7122", "Waglan Island", "China" ],
    [ "7124", "Sai Kung Hoi", "China" ],
    [ "7129", "Ko Lau Wan", "China" ],
    [ "7132", "Tai Po Kau", "China" ],
    [ "7141", "Tsang Chau", "China" ],
    [ "7147", "Jieshi Wan", "China" ],
    [ "7159", "Zhao'An Wan", "China" ],
    [ "7163", "Xiamen Gang", "China" ],
    [ "7176A", "T'Ai-Chung Kang", "T'Ai-Wan" ],
    [ "7206", "Ren Yu", "China" ],
    [ "7219", "Sandu Dao", "China" ],
    [ "7239", "Shipu Gang", "China" ],
    [ "7249", "Yangxiaomao Dao", "China" ],
    [ "7262", "Yuxingnao Dao", "China" ],
    [ "7334", "Longxu Wan", "China" ],
    [ "7335", "Malan Wan", "China" ],
    [ "7397", "Bayuquan", "China" ],
    [ "7753", "Aburatsu", "Japan Kyushu East Coast" ],
    [ "7948", "Mera", "Japan Honshu South Coast" ],
    [ "7953", "Chichi Shima (Futami)", "Japan Nanpo Shoto" ],
    [ "7964", "Miyake Shima", "Japan Nanpo Shoto" ],
    [ "7992", "Ofunato", "Japan Honshu East Coast" ],
    [ "8105", "Kushiro", "Japan Hokkaido East Coast" ],
    [ "9371", "Ensenada", "Mexico" ],
    [ "9401", "Loreto", "Mexico" ],
    [ "9432", "Acapulco", "Mexico" ],
    [ "9439", "Puerto Chiapas", "Mexico" ],
    [ "9463", "Quepos", "Costa Rica" ],
    [ "9468", "Golfito", "Costa Rica" ],
    [ "9507", "Buenaventura", "Colombia" ],
    [ "9520", "Santa Cruz (Galapagos Is)", "Ecuador" ],
    [ "9521", "Caleta Aeolian", "Ecuador" ],
    [ "9539", "La Libertad", "Ecuador" ],
    [ "9555", "Lobos De Afuera", "Peru" ],
    [ "9564", "Bahia Ferrol", "Peru" ],
    [ "9573", "Callao", "Peru" ],
    [ "9594", "Arica", "Chile" ],
    [ "9610", "Antofagasta", "Chile" ],
    [ "9620", "Chanaral De Las Animas", "Chile" ],
    [ "9622", "Puerto Caldera", "Chile" ],
    [ "9648", "Isla Robinson Crusoe", "Chile" ],
    [ "9665", "Puerto Lebu", "Chile" ],
    [ "9671", "Puerto Corral", "Chile" ],
    [ "9675", "Caleta Mansa", "Chile" ],
    [ "9749", "Bahia Kelly", "Chile" ],
    [ "9893", "Primera Angostura", "Chile" ] ]