#!/bin/bash
#
# Build the DEBIAN source files for upload to LaunchPad PPA.
#
# Ensure the version number below also matches:
#	src/indicator-lunar.py
#	packaging/debian/changelog.  


NAME="indicator-lunar"
VERSION="1.0.93"

source=( $NAME".py" astrobase.py astropyephem.py eclipse.py orbitalelement.py twolineelement.py ) # List of source files.
hicolorIcons=( $NAME".svg" "indicator-lunar-satellite.svg" ) # List of hicolor icons.
hicolorColours=( fff200 ) # List of colours in all the hicolor icons.

. ../indicator-base/build-debian-common
doStandardBuild source hicolorIcons hicolorColours
