#!/bin/bash
#
# Build the DEBIAN source files for upload to LaunchPad PPA.
#
# Ensure the version number below also matches:
#	src/indicator-tide.py
#	packaging/debian/changelog.  


NAME="indicator-tide"
VERSION="1.0.29"

source=( $NAME".py" tide.py tidedatagetterbase.py ) # List of source files.
hicolorIcons=( $NAME".svg" ) # List of hicolor icons.
hicolorColours=( 0000aa ) # List of colours in all the hicolor icons.

. ../indicator-base/build-debian-common
doStandardBuild source hicolorIcons hicolorColours
