#!/bin/bash


# Common code for the build-debian script for all indicators.
#
# Install the packages:
#   sudo apt install devscripts dh-make build-essential lintian gpg
#
#
# Import secret key into gpg.  In a terminal, change to the directory containing the files
#
#	'Bernard Giannetti.asc' pubring.pkr secring.skr
#
# and run
#
#	gpg --import secring.skr
#
#
# When running a build, if the warning 'ancient-standards-version' arises,
# edit the debian/control file and change the value for the field 'Standards-Version'
# to be a value from the Debian policy
#	https://www.debian.org/doc/debian-policy/upgrading-checklist.html
# which was just before the release of the oldest supported version of Ubuntu.
# For example, if Ubuntu 18.04 is the oldest supported version, choose the standards version 4.1.3
#
#
# References for building a Debian package for PPA...
#    http://askubuntu.com/questions/27715/create-a-deb-package-from-scripts-or-binaries
#    http://askubuntu.com/questions/28562/how-do-i-create-a-ppa-for-a-working-program
#    http://askubuntu.com/questions/90764/how-do-i-create-a-deb-package-for-a-single-python-script
#	 https://stackoverflow.com/questions/65117979/problems-using-debuild-to-upload-a-python-gtk-program-to-launchpad
#	 https://askubuntu.com/questions/399552/how-to-create-a-deb-package-for-a-python3-script
#    http://blog.garethj.com/2009/06/02/building-deb-packages-for-python-applications
#    http://developer.ubuntu.com/packaging/html/debian-dir-overview.html
#    http://help.launchpad.net/Packaging/PPA/Uploading
#    http://help.ubuntu.com/community/PythonRecipes/DebianPackage
#    http://savetheions.com/2010/01/20/packaging-python-applicationsmodules-for-debian
#    http://shallowsky.com/blog/programming/packaging-launchpad-ppas.html
#    http://ubuntulinuxtipstricks.blogspot.com.au/2010/08/is-packaging-new-software-hard.html
#    http://wiki.debian.org/Python/Packaging
#    http://wiki.ubuntu.com/MOTU/School/PackagingWithoutCompiling
#    http://wiki.ubuntu.com/PackagingGuide/HandsOn
#    http://wiki.ubuntu.com/PackagingGuide/Python
#    http://www.debian.org/doc/manuals/maint-guide
#    http://www.debian.org/doc/packaging-manuals/python-policy
#    http://www.debian-administration.org/articles/336
#    http://news.softpedia.com/news/How-to-Repack-Deb-Files-on-Debian-and-Ubuntu-404930.shtml
#    http://blog.packagecloud.io/debian/debuild/packaging/2015/06/08/buildling-deb-packages-with-debuild
#    https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
#    https://developer.gnome.org/icon-theme-spec/


# Common to all indicators.
INDICATOR_BASE=../indicator-base


# Supported themes and corresponding colours.
themeNames=(   "Adwaita" "elementary-xfce-darker" "Lubuntu" "ubuntu-mono-dark" "ubuntu-mono-light"  "Yaru"  )
themeColours=(  bebebe             f3f3f3          4c4c4c          dfdbd2             3c3c3c        dbdbdb )


# Arguments: 
#   Array of source files present in the src directory.
#   Array of hicolor icon names present in the icons directory.
#   Array of hicolor colours present across ALL hicolor icons.
doStandardBuild()
{
  copyTopLevelAndSource $1
  copyHicolorCreateThemed $2 $3
  copyPOCreateMO
  createOrigTarGz
  copyDebian
  setEndYearInCopyright
  addIconsToDebianInstall $2
  addMOToDebianInstall
  buildDeb
  cleanUp
}


# Arguments:
#   Array of source files present in the src directory.
copyTopLevelAndSource()
{
  local -n _source=$1

  # Check .py files (and others) for a TODO.
  foundTODO="false"
  for item in "${_source[@]}"; do
    if [ -n "$(grep -i TODO src/$item)" ]
    then
      echo "Found one or more TODO in src/$item"
      foundTODO="true"
    fi
    done

  nonSource=( "$INDICATOR_BASE/src/indicatorbase.py" "packaging/debian/changelog" "packaging/debian/control" "packaging/debian/install" )
  for item in "${nonSource[@]}"; do
    if [ -n "$(grep -i TODO $item)" ]
    then
      echo "Found one or more TODO in $item"
      foundTODO="true"
    fi
    done

  if "$foundTODO"
  then
    exit
  fi

  # No TODOs...so continue and copy source files.
  rm -rf build
  mkdir -p build/$NAME-$VERSION

  cp $NAME.py.desktop build/$NAME-$VERSION

  mkdir -p build/$NAME-$VERSION/src
  cp $INDICATOR_BASE/src/indicatorbase.py build/$NAME-$VERSION/src

  for item in "${_source[@]}"; do
    cp src/"$item" build/$NAME-$VERSION/src
  done
}



# Arguments:
#   Array of hicolor icons names present in the icons directory.
#   Array of hicolor colours present across ALL hicolor icons.
copyHicolorCreateThemed()
{
  local -n _hicolorIcons=$1
  local -n _hicolorColours=$2

  # Copy hicolor icon(s)...
  mkdir -p build/$NAME-$VERSION/icons/hicolor
  for (( i = 0; i < "${#_hicolorIcons[*]}"; i++ )); do
    sourceIcon=icons/"${_hicolorIcons[ $i ]}"
    cp $sourceIcon build/$NAME-$VERSION/icons/hicolor

    # ...and create themed icons...
    for (( j = 0; j < ${#themeNames[@]}; j++ )); do
     destPath=build/$NAME-$VERSION/icons/${themeNames[ $j ]}
     mkdir -p $destPath
     cp $sourceIcon $destPath

      # ...by substituting each hicolor colour(s) for the current theme colour.
      for (( k = 0; k < "${#_hicolorColours[*]}"; k++ )); do
        sed -i s/"${_hicolorColours[ $k ]}"/${themeColours[ $j ]}/g $destPath/"${_hicolorIcons[ $i ]}"
      done
    done
  done
}


copyPOCreateMO()
{
  # Copy entire po directory.
  rsync -ar --exclude=.svn po build/$NAME-$VERSION

  # Copy README from indicator-base.
  cp $INDICATOR_BASE/po/README build/$NAME-$VERSION/po

  # Append translations from indicatorbase to POT.
  msgcat --use-first build/$NAME-$VERSION/po/$NAME.pot $INDICATOR_BASE/po/indicatorbase.pot --output-file=build/$NAME-$VERSION/po/$NAME.pot

  # Append translations from indicatorbase to PO files.
  for PO_FILE in $(find build/$NAME-$VERSION/po -type f -name '*.po') ; do

    # Get the language code.  Split the PO_FILE into an array using / as the delimiter.
    array=(`echo $PO_FILE | sed 's/\//\n/g'`)
    languageCode=${array[${#array[@]}-2]}

    msgcat --use-first $PO_FILE $INDICATOR_BASE/po/$languageCode/indicatorbase.po --output-file=$PO_FILE
  done

  # Create .mo files.
  for PO_FILE in $(find build/$NAME-$VERSION/po -type f -name '*.po') ; do
    msgfmt $PO_FILE --output-file ${PO_FILE%\.po}.mo
  done
}


createOrigTarGz()
{
  cd build
  tar -czf "${NAME}_${VERSION}.orig.tar.gz" $NAME-$VERSION
  cd ..
}


copyDebian()
{
  rsync -ar --exclude=.svn packaging/debian build/$NAME-$VERSION
}


setEndYearInCopyright()
{
  sed -i "s/ENDYEAR/$(date '+%Y')/" build/$NAME-$VERSION/debian/copyright
}


# Arguments:
#   Array of hicolor icons names present in the icons directory.
#
# Between Ubuntu 12.04 and 16.04, a change occurred in how icons are located.
# Unsure if it is a bug in earlier versions that was fixed in later versions,
# or a bug was introduced in later versions.
#
# In 12.04/14.04, SVG icons were loaded, regardless if the directories
# in which they were located were listed or not in the index.theme file.
# In 16.04 and later, the SVG icons are not located.
#
# Ideally, each icon theme would be specifically handled so that icons
# are placed in directories which exist for that theme.
#
# For example, hicolor/Adwaita does not have an apps/22, apps/24, ...
# and so on but does have scalable/apps directory.  Therefore, icons would
# be placed only into scalable/apps.
# For ubuntu-mono-dark/ubuntu-mono-light, the reverse is true.
#
# However, to keep functionality simple/generic and not have specific code
# for each icon theme, place icons in multiple directories to ensure that
# for a given icon theme, at least one of the directories exists in the index.theme file.
addIconsToDebianInstall()
{
  # Update debian/install with icons.
  local -n _hicolorIcons=$1

  for (( i = 0; i < "${#_hicolorIcons[*]}"; i++ )); do
    for (( j = 0; j < ${#themeNames[@]}; j++ )); do

      line="icons/${themeNames[ $j ]}/${_hicolorIcons[ $i ]} usr/share/icons/${themeNames[ $j ]}/scalable/apps"
      echo $line >> build/$NAME-$VERSION/debian/install

      line="icons/${themeNames[ $j ]}/${_hicolorIcons[ $i ]} usr/share/icons/${themeNames[ $j ]}/apps/16"
      echo $line >> build/$NAME-$VERSION/debian/install

      line="icons/${themeNames[ $j ]}/${_hicolorIcons[ $i ]} usr/share/icons/${themeNames[ $j ]}/apps/22"
      echo $line >> build/$NAME-$VERSION/debian/install

      line="icons/${themeNames[ $j ]}/${_hicolorIcons[ $i ]} usr/share/icons/${themeNames[ $j ]}/apps/24"
      echo $line >> build/$NAME-$VERSION/debian/install

      line="icons/${themeNames[ $j ]}/${_hicolorIcons[ $i ]} usr/share/icons/${themeNames[ $j ]}/apps/48"
      echo $line >> build/$NAME-$VERSION/debian/install

    done
  done
}


addMOToDebianInstall()
{
  # Update debian/install file with .mo
  echo ""
  cd build/$NAME-$VERSION
  for MO_FILE in $(find po -type f -name '*.mo') ; do
    FIRST_SLASH=`expr index "$MO_FILE" /`
	STRING_AFTER_FIRST_SLASH=${MO_FILE:FIRST_SLASH}
    SECOND_SLASH=`expr index "$STRING_AFTER_FIRST_SLASH" /`
    MO_CODE=${STRING_AFTER_FIRST_SLASH:0:SECOND_SLASH-1}
    echo "$MO_FILE /usr/share/locale/${MO_CODE}/LC_MESSAGES" >> debian/install
  done
  cd ../..
}


buildDeb()
{
  # Build DEB source (or binary).
  cd build/$NAME-$VERSION
  debuild -S -sa         # Builds a DEB source file.
#  debuild -sa -us -uc   # Builds a DEB binary file.
  cd ..
}


cleanUp()
{
  rm -rf $NAME-$VERSION
  echo -e "\nTo upload to LaunchPad, change to the 'build' directory and run:\n"
  echo -e "    dput ppa:thebernmeister/ppa ${NAME}_${VERSION}-1_source.changes\n"
}