#!/bin/bash

#Refer to 
#	https://pip.pypa.io/en/stable/cli/pip_uninstall/

sudo pip3 uninstall -y ephem sgp4 || true


# Perhaps only bother with this (uninstall via PIP) for the next few months, 
# until 24.04 is close to release?
# Thinking is, by April 2024 should have a solution to install ephem/sgp4 to a venv
# and so the postinst/postrm will have to change anyway.

#sudo pip3 install --ignore-installed --upgrade ephem sgp4 || true

#DEBHELPER#