# THIS IS THE TEMPLATE USED BY THE BUILD WHEEL SCRIPT
# TO CREATE A PYPROJECT.TOML FOR EACH INDICATOR.
[build-system]
requires = [ "setuptools >= 61.0" ]
build-backend = "setuptools.build_meta"

[project]
version = "1.0.1"
authors = [
  { name = "Bernard Giannetti", email = "thebernmeister@hotmail.com" } ]
maintainers = [
  { name = "Bernard Giannetti", email = "thebernmeister@hotmail.com" } ]
license = "GPL-3.0-or-later"  #TODO See if this builds under Debian 12 and Ubunru 20.04   All good on Debian 12.  Error on Ubuntu 20.04.  See build_wheel.py for details.
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "packaging" ]
classifiers = [
  "Development Status :: 6 - Mature",
  "Environment :: X11 Applications :: GTK",
  "Intended Audience :: End Users/Desktop",
#  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",  #TODO This is deprecated.
  "Natural Language :: English",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.8" ]

[project.urls]
homepage = "https://appindicators.sourceforge.io"

[tool.setuptools.packages.find]
where = [ "src" ]
