# THIS IS THE TEMPLATE USED BY THE BUILD WHEEL SCRIPT
# TO CREATE A PYPROJECT.TOML FOR EACH INDICATOR.
[build-system]
requires = [ "setuptools >= 61.0" ]
build-backend = "setuptools.build_meta"

[project]
version = "1.0.1"
authors = [
  { name = "Bernard Giannetti", email = "thebernmeister@hotmail.com" } ]
maintainers = [
  { name = "Bernard Giannetti", email = "thebernmeister@hotmail.com" } ]
#TODO Does not build on Ubuntu 20.04;
# for an actual release to upload to PyPI,
# must uncomment and build on Debian 12+ (laptop is fine) or Ubuntu 22.04+
#
#TODO Build a wheel on the laptop and
# see if that wheel will install on Ubuntu 20.04
#license = "GPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
  "Development Status :: 6 - Mature",
  "Environment :: X11 Applications :: GTK",
  "Intended Audience :: End Users/Desktop",
  "Natural Language :: English",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.8" ]

[project.urls]
homepage = "https://appindicators.sourceforge.io"  #TODO This page/repository was deleted by SourceForge because I had not submitted code/releases.  Maybe think about Github instead (and even migrate Stardate System Tray and World Time System Tray too).  https://sourceforge.net/p/forge/site-support/26844/
[tool.setuptools.packages.find]
where = [ "src" ]
