# THIS IS THE TEMPLATE USED BY THE BUILD WHEEL SCRIPT
# TO CREATE A PYPROJECT.TOML FOR EACH INDICATOR.
[build-system]
requires = [ "setuptools >= 61.0" ]
build-backend = "setuptools.build_meta"

[project]
version = "1.0.1"
authors = [
  { name = "Bernard Giannetti", email = "thebernmeister@hotmail.com" } ]
maintainers = [
  { name = "Bernard Giannetti", email = "thebernmeister@hotmail.com" } ]
#TODO The license line below is unsupported on Ubuntu 20.04.
# When building for a release to PyPI / TestPyPI,
# uncomment the license line and build on Ubuntu 22.04+
#license = "GPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
  "Development Status :: 6 - Mature",
  "Environment :: X11 Applications :: GTK",
  "Intended Audience :: End Users/Desktop",
  "Natural Language :: English",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.8" ]

#TODO The repository URL specified below was deleted by
# SourceForge because I had not uploaded code nor done a release.
#   https://sourceforge.net/p/forge/site-support/26844/
# Despite the URL being reinstated and then deleted again,
# this is a concern.
# 
# So can either not include a project URL or look to some other host.
#
# Could use Github or Gitlab, including migrating both
# Stardate System Tray and World Time System Tray.
#
# Figure out if moving to Git or staying with SourceForge (and possibly
# moving later to Git) or just have no project (for now).
[project.urls]
homepage = "https://appindicators.sourceforge.io"

[tool.setuptools.packages.find]
where = [ "src" ]
