# THIS IS THE TEMPLATE USED BY THE BUILD WHEEL SCRIPT
# TO CREATE A PYPROJECT.TOML FOR EACH INDICATOR.
[build-system]
requires = [ "setuptools >= 61.0" ]
build-backend = "setuptools.build_meta"

[project]
version = "1.0.1"
authors = [
  { name = "Bernard Giannetti", email = "thebernmeister@hotmail.com" } ]
maintainers = [
  { name = "Bernard Giannetti", email = "thebernmeister@hotmail.com" } ]
#license = "GPL-3.0-or-later"  #TODO Does not build on Ubuntu 20.04; must uncomment and build on Debian 12+ or Ubuntu 22.04+
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "pip" ]
  #TODO Need to remove the dependencies tag completely,
  # but ensure build wheel works with all indicators including indicatorlunar.
  # TODO work out why packaging is included in the venv_build.
classifiers = [
  "Development Status :: 6 - Mature",
  "Environment :: X11 Applications :: GTK",
  "Intended Audience :: End Users/Desktop",
  "Natural Language :: English",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.8" ]

[project.urls]
homepage = "https://appindicators.sourceforge.io"

[tool.setuptools.packages.find]
where = [ "src" ]
