# THIS IS AN INCOMPLETE PYPROJECT.TOML USED BY THE BUILD WHEEL SCRIPT
# TO CREATE A COMPLETE PYPROJECT.TOML.
version = "1.0.101"
description = "Application indicator for the home astronomer."
dependencies = [
  "ephem",
  "requests",
  "sgp4"
]
classifiers = [
  "Topic :: Scientific/Engineering :: Astronomy"
]
