#!/bin/bash


BUILD_DIR="build"
NAME="indicator-lunar"
VERSION=1.0.18

rm -rf $BUILD_DIR

mkdir -p $BUILD_DIR/$NAME-$VERSION
cp $NAME.desktop $BUILD_DIR/$NAME-$VERSION
cp build-debian $BUILD_DIR/$NAME-$VERSION

mkdir -p $BUILD_DIR/$NAME-$VERSION/src
cp src/indicator-lunar.py $BUILD_DIR/$NAME-$VERSION/src

mkdir -p $BUILD_DIR/$NAME-$VERSION/icons/elementary
cp icons/elementary/*.svg $BUILD_DIR/$NAME-$VERSION/icons/elementary

mkdir -p $BUILD_DIR/$NAME-$VERSION/icons/hicolor
cp icons/hicolor/*.svg $BUILD_DIR/$NAME-$VERSION/icons/hicolor

mkdir -p $BUILD_DIR/$NAME-$VERSION/icons/lubuntu
cp icons/lubuntu/*.svg $BUILD_DIR/$NAME-$VERSION/icons/lubuntu

mkdir -p $BUILD_DIR/$NAME-$VERSION/icons/ubuntu-mono-dark
cp icons/ubuntu-mono-dark/*.svg $BUILD_DIR/$NAME-$VERSION/icons/ubuntu-mono-dark

mkdir -p $BUILD_DIR/$NAME-$VERSION/icons/ubuntu-mono-light
cp icons/ubuntu-mono-light/*.svg $BUILD_DIR/$NAME-$VERSION/icons/ubuntu-mono-light

cd $BUILD_DIR
tar -czf "${NAME}_${VERSION}.orig.tar.gz" $NAME-$VERSION
cd ..

mkdir -p $BUILD_DIR/$NAME-$VERSION/debian
cp -r packaging/debian $BUILD_DIR/$NAME-$VERSION

cd $BUILD_DIR/$NAME-$VERSION
debuild -S -sa
cd ..
rm -rf $NAME-$VERSION

echo "Now run from the build directory: dput ppa:thebernmeister/ppa ${NAME}_${VERSION}-1_source.changes"
