#!/bin/bash
#
# Build the DEBIAN source files for upload to LaunchPad PPA.
#
# Ensure the version number below also matches:
#	src/indicator-tide.py
#	packaging/debian/changelog.  


VERSION="1.0.4"
NAME="indicator-tide"

source=( $NAME".py" locationData.py locations.py tide.py )
hicolorIcons=( $NAME".svg" ) # List of hicolor icons belonging to the indicator (contents of the icons directory).
hicolorColours=( 0000aa ) # List of colours present across ALL the hicolor icons.

. ./test-common
copyTopLevelAndSource source
copyHicolorCreateThemed hicolorIcons hicolorColours
copyPOCreateMO
createOrigTarGz
copyDebian
addIconsToDebianInstall hicolorIcons
addMOToDebianInstall
buildDeb
cleanUp