# THIS IS AN INCOMPLETE PYPROJECT.TOML USED BY THE BUILD WHEEL SCRIPT
# TO CREATE A COMPLETE PYPROJECT.TOML.
version = "1.0.16"
description = "Application indicator which converts domain names between Unicode and ASCII."
classifiers = [
  "Topic :: Utilities" ]
