#!/bin/bash
#
# Build the DEBIAN source files for upload to LaunchPad PPA.
#
# Ensure the version number below also matches:
#	src/indicator-test.py
#	packaging/debian/changelog.  


NAME="indicator-test"
VERSION="1.0.6"

source=( $NAME".py" ) # List of source files.
hicolorIcons=( $NAME".svg" ) # List of hicolor icons.
hicolorColours=( 6496dc ) # List of colours in all the hicolor icons.

. ../indicator-base/build-debian-common
doStandardBuild source hicolorIcons hicolorColours
