# THIS IS AN INCOMPLETE PYPROJECT.TOML USED BY THE BUILD WHEEL SCRIPT
# TO CREATE A COMPLETE PYPROJECT.TOML.
version = "1.0.44"
description = "Application indicator which displays fortunes."
classifiers = [
  "Topic :: Games/Entertainment :: Fortune Cookies" ]
