#!/bin/bash
#
# Build the DEBIAN source files for upload to LaunchPad PPA.
#
# Ensure the version number below also matches:
#	src/indicator-ppa-download-statistics.py
#	packaging/debian/changelog.  


NAME="indicator-ppa-download-statistics"
VERSION="1.0.80"

source=( $NAME".py" ppa.py ) # List of source files.
hicolorIcons=( $NAME".svg" ) # List of hicolor icons.
hicolorColours=( 6496dc ) # List of colours present across all the hicolor icons.

. ../indicator-base/build-debian-common
doStandardBuild source hicolorIcons hicolorColours
