#!/bin/bash
#
# Build the DEBIAN source files for upload to LaunchPad PPA.
#
# Ensure the version number below also matches:
#	src/indicator-punycode.py
#	packaging/debian/changelog.  


NAME="indicator-punycode"
VERSION="1.0.13"

source=( $NAME".py" ) # List of source files.
hicolorIcons=( $NAME".svg" ) # List of hicolor icons.
hicolorColours=( 78dc96 6496dc ) # List of colours in all the hicolor icons.

. ../indicator-base/build-debian-common
copyTopLevelAndSource source
copyHicolorCreateThemed hicolorIcons hicolorColours

# Specific code to handle opacity.
sed -i 's/"opacity:0.2"/"opacity:0.3"/' build/$NAME-$VERSION/icons/Adwaita/indicator-punycode.svg
sed -i 's/"opacity:0.2"/"opacity:0.15"/' build/$NAME-$VERSION/icons/elementary-xfce-darker/indicator-punycode.svg
sed -i 's/"opacity:0.2"/"opacity:0.3"/' build/$NAME-$VERSION/icons/Lubuntu/indicator-punycode.svg
sed -i 's/"opacity:0.2"/"opacity:0.3"/' build/$NAME-$VERSION/icons/ubuntu-mono-dark/indicator-punycode.svg
sed -i 's/"opacity:0.2"/"opacity:0.3"/' build/$NAME-$VERSION/icons/ubuntu-mono-light/indicator-punycode.svg

copyPOCreateMO
createOrigTarGz
copyDebian
addIconsToDebianInstall hicolorIcons
addMOToDebianInstall
buildDeb
cleanUp
