#!/bin/bash
#
# Build the DEBIAN source files for upload to LaunchPad PPA.
#
# Ensure the version number below also matches:
#	src/indicator-stardate.py
#	packaging/debian/changelog.  


NAME="indicator-stardate"
VERSION="1.0.41"

source=( $NAME".py" example.py stardate.py ) # List of source files.
hicolorIcons=( $NAME".svg" ) # List of hicolor icons.
hicolorColours=( fff700 ) # List of colours in all the hicolor icons.

. ../indicator-base/build-debian-common
doStandardBuild source hicolorIcons hicolorColours
