#!/bin/bash
#
# Build the DEBIAN source files for upload to LaunchPad PPA.
#
# Ensure the version number below also matches:
#	src/indicator-script-runner.py
#	packaging/debian/changelog.  


NAME="indicator-script-runner"
VERSION="1.0.24"

source=( $NAME".py" script.py ) # List of source files.
hicolorIcons=( $NAME".svg" ) # List of hicolor icons.
hicolorColours=( 6999b9 ) # List of colours in all the hicolor icons.

. ../indicator-base/build-debian-common
doStandardBuild source hicolorIcons hicolorColours
