# THIS IS AN INCOMPLETE PYPROJECT.TOML
# USED BY THE BUILD WHEEL SCRIPT
# TO CREATE A COMPLETE PYPROJECT.TOML.
[project]
version = "1.0.17"
description = "Application indicator which displays calendar events."
classifiers = [
  "Topic :: Games/Entertainment" ]
